### ISSUE TITLE
cython is a requirment for this package

### ISSUE THREAD

**Issue by isofer** [benfred/implicit#10]
Hi,
Great package. Thanks for sharing it.
I just want to note that cython is a requirement for this package, and I had problems installing it until I discover that.

thanks.
Imri

**Comment by benfred** [comment]
Could you post the output of your build without cython? 

You should be able to compile without cython using the pregenerated _implicit.c file thats checked in. Also it should detect if cython isn't installed and skip the cython step (https://github.com/benfred/implicit/blob/master/setup.py#L19).

thanks!

**Comment by isofer** [comment]
Sorry, I could not reproduce this problem. I Don't know why it was an issue for me.
closing this.
