### ISSUE TITLE
AlternatingLeastSquares rank_items doesnt work

### ISSUE THREAD

**Issue by oppaquan** [benfred/implicit#104]
Hello,

I am trying to use the rank_items method from AlternatingLeastSquares as stated in the documentation but when I try to use it to rank items for a specific user I'm getting a **AttributeError: 'AlternatingLeastSquares' object has no attribute 'rank_items'**. So does this mean that this method doesn't exist for AlternatingLeastSquares and the documentation is wrong or am I missing something?

#setting up the model
model = implicit.als.AlternatingLeastSquares(factors = 10, regularization = 10, iterations = 50)

#setting alpha = 15
alpha = 15

#confidence matrix
confidence = item_user * alpha

#model fit
model.fit(confidence)

ranked_items = model.rank_items(idx, user_item, items)

Any help will be gladly appreciated! Thanks.

**Comment by ita9naiwa** [comment]
Hi, are you using version '0.3.5'?
```
>>> implicit.__version__
'0.3.5'
```
I tested installing using pip and cloning this repository, both worked.

**Comment by oppaquan** [comment]
Thank you so much for the response. It seems that I currently have 0.3.4. That could be the problem. I will try to update to the latest version and try it again.
