### ISSUE TITLE
Installing with GPU on windows

### ISSUE THREAD

**Issue by varunsaboo** [benfred/implicit#109]
Hi,
I am trying to install implicit on windows with GPU but I have no idea how to start with it. Any suggestions?

Thanks!

**Comment by benfred** [comment]
What's the issue you are seeing?

You'll need to download the CUDA toolkit (https://developer.nvidia.com/cuda-toolkit), but once that's installed you should be able to just go 'pip install implicit' and it should work.

**Comment by varunsaboo** [comment]
I have CUDA 8.0 installed. However implicit is not identifying the CUDA installation. 
implicit.cuda.HAS_CUDA is False

**Comment by benfred** [comment]
When installing - implicit tries to find the cuda installation by looking for nvcc.exe in the path, then falls back to looking at the  CUDA_PATH environment variable. Can you check that nvcc.exe is in your path?

Also - whats the output of running the implicit install?

**Comment by varunsaboo** [comment]
This was the issue:
In cuda_setup.py, at line 55, you are assigning cudaconfig['lib64'] to os.path.join(home, 'lib64').
But that directory does not exist for win32 system. The function returns No Cuda installation because of missing directory.
By adding the following lines before the directory check, the issue can be resolved!
`if sys.platform == "win32":
        cudaconfig['lib64'] = os.path.join(home, 'lib', 'x64')`

**Comment by benfred** [comment]
awesome! thanks for tracking this down.

I have a windows machine at home, will verify that your fix works there and if so will get into the next release. I definitely had this working at one point (but I think I was testing against cuda9 on windows iirc, and maybe the cuda installation layout is different? or I messed up at one point =).

thanks again,

**Comment by varunsaboo** [comment]
However, I ran into another problem:
matrix.cu
    warning: I don't know what to do with 'runtime_library_dirs': ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\lib\\x64']
    error: don't know how to set runtime library search path for MSVC++
error
Cleaning up...
  Removing source in C:\Users\SABOO~1.VAR\AppData\Local\Temp\pip-install-1not9rlr\implicit
Command "c:\users\saboo.varun\anaconda2\envs\tensorflow\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\SABOO~1.VAR\\AppData\\Local\\Temp\\pip-install-1not9rlr\\implicit\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\SABOO~1.VAR\AppData\Local\Temp\pip-record-2utfvud1\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\SABOO~1.VAR\AppData\Local\Temp\pip-install-1not9rlr\implicit\

I have no idea how to fix this.

**Comment by benfred** [comment]
can you try commenting out line 68 of implicit\setup.py and trying again ? (the line going ```runtime_library_dirs=[CUDA['lib64']]``` I mean).

**Comment by varunsaboo** [comment]
That works! Thank you!

**Comment by benfred** [comment]
great! It seems like there were a couple of issues with running cuda 8 on windows here, will get fixes in soon-ish.

**Comment by benfred** [comment]
I believe this PR fixes: https://github.com/benfred/implicit/pull/113 

Sorry about the hassle here, I don't develop on windows normally and the windows CI doesn't test the GPU code.
