### ISSUE TITLE
Python SDK Install failed in Windows 10

### ISSUE THREAD

**Issue by mathubhalan** [benfred/implicit#123]
Hi Team,
I have Visual C++ Redistributable 14.0.23918, but still facing issue in installing  the python SDK. 
Python Version 3.6

 package init file 'acouchbase\tests\__init__.py' not found (or not a regular file)
    creating build\lib.win-amd64-3.6\acouchbase\tests
    copying acouchbase\tests\asyncio_tests.py -> build\lib.win-amd64-3.6\acouchbase\tests
    copying acouchbase\tests\fixtures.py -> build\lib.win-amd64-3.6\acouchbase\tests
    copying acouchbase\tests\py34only.py -> build\lib.win-amd64-3.6\acouchbase\tests
    copying acouchbase\tests\py35only.py -> build\lib.win-amd64-3.6\acouchbase\tests
    package init file 'acouchbase\py34only\__init__.py' not found (or not a regular file)
    creating build\lib.win-amd64-3.6\acouchbase\py34only
    copying acouchbase\py34only\iterator.py -> build\lib.win-amd64-3.6\acouchbase\py34only
    running build_ext
    building 'couchbase._libcouchbase' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "c:\programdata\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\mathu_gopalan\\AppData\\Local\\Temp\\pip-install-2_v42p9e\\couchbase\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\mathu_gopalan\AppData\Local\Temp\pip-record-twq4ywxa\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\mathu_gopalan\AppData\Local\Temp\pip-install-2_v42p9e\couchbase\

**Comment by benfred** [comment]
If you're having problems building couchbase - you should probably ping the maintainer there.

Having said that - the problem seems to be that you need to install visual c++ build tools. The link in the error message is dead, but I believe you can download here: https://visualstudio.microsoft.com/visual-cpp-build-tools/
