### ISSUE TITLE
Influence of number of factors on performance

### ISSUE THREAD

**Issue by ionelhosu** [benfred/implicit#127]
Hi,

I've been using both ALS and BPR for implicit feedback on a dataset of about 150k users and 20k items (about 99% sparse), and the performance by means of precision at k on test degrades fast above 50 factors using ALS (from 0.02 using 25 factors to about 0.0005 for 200 factors) and doesn't seem to be influenced a lot by the number of factors using BPR (about 0.025 constantly from 50 to 200 factors). Is this behaviour normal?

Thank you very much.

**Comment by ita9naiwa** [comment]
Larger number of factors brings less generalization.
https://www.quora.com/What-is-generalization-in-machine-learning

**Comment by benfred** [comment]
It could be overfitting more in the ALS model as the number of factors grows, I would try increasing the regularization parameter here.
