### ISSUE TITLE
Shut off progress bar when fitting ALS model

### ISSUE THREAD

**Issue by sharongail** [benfred/implicit#129]
Recently I find out that a progress bar appears after using the command model.fit shown as follows:

100%|██████████| 15.0/15 [00:00<00:00, 38.72it/s]

How can I shut if off?

**Comment by ita9naiwa** [comment]
there is `show_progress` field. set this false like
`
model = blahblahModel()
model.show_progress = False
`
https://github.com/benfred/implicit/blob/a258824aac6d87e73fdd294ea80f0fd65081951c/tests/recommender_base_test.py

**Comment by benfred** [comment]
Right now the only way to disable is like @ita9naiwa suggested - but I'm thinking of changing to put as a parameter on the 'fit' method (like ```model.fit(data, show_progress=False)``` to disable). I think this will be more consistent with disabling in the evaluation methods

**Comment by benfred** [comment]
The last commit there changes show_progress to be a argument on the fit method (instead of a member of the class). Will be in the next version.
