### ISSUE TITLE
installation of the latest als.py

### ISSUE THREAD

**Issue by franktma** [benfred/implicit#135]
Hi all,

I'm really excited that the latest update of als.py can take negative preferences!! I would like to use it.
(https://github.com/benfred/implicit/commit/b6f670b296ad2c15ecc3f0102da59524d087b73b)

But I realized that it is not in the latest pip install (v0.3.6)

Do you think it's possible to create a new pip install version with the update? I tried to clone + setup the head version myself, but couldn't get the cython compilation to work. :( If you have advice in setup of the head, that's equally appreciated.

thanks!

Frank

**Comment by ita9naiwa** [comment]
try 
```
python setup.py build # it re-builds cython
python setup.py install
```

**Comment by franktma** [comment]
Thanks for the help @ita9naiwa, the build ran!

One more question:  How can I use the newly built package? (I am new to using setup ... really appreciate the help.)

If I run python in the implicit directory:
>> import _als

I get:
  File "als.py", line 14, in <module>
    from . import _als
ImportError: attempted relative import with no known parent package

Frank

**Comment by benfred** [comment]
@franktma you need to run this in a different directory than in implicit/implicit (even just changing to the parent directory will work).

There are a couple PR's here that I'm going through, will push a new version to pypi afterwards

**Comment by franktma** [comment]
That worked. Thanks for all your help @benfred @ita9naiwa !!
