### ISSUE TITLE
How can I add side information like user's age, gender to solve the cold start problem

### ISSUE THREAD

**Issue by wyfoffice** [benfred/implicit#137]
I wish to add the user's demographics to get a better prediction, can I do it with our library?

**Comment by ita9naiwa** [comment]
This library does not support that but...

I'm not the maintainer of this library, but hmm...
I think its because user/item metadata has no unified format like user-item interaction matrix.

**Comment by wyfoffice** [comment]
@ita9naiwa okay... Maybe we can make the metadatas of user/item as a one-hot vector, thus this might be more convenient to continue the next operation

**Comment by srcolinas** [comment]
@wyfoffice  I think you would like to have a look at this other library: https://github.com/lyst/lightfm
Nonetheless, make some tests to see which one is better.

**Comment by benfred** [comment]
Agree with @srcolinas here, if you need this in the short term - you're probably better off with lightfm for now. There is another issue to track this feature here https://github.com/benfred/implicit/issues/55 so I'm going to close this
