### ISSUE TITLE
"RuntimeError: Cuda Error: unspecified launch failure" after upgrading graphic card

### ISSUE THREAD

**Issue by Antossio** [benfred/implicit#141]
Hi.
I've changed GTX 760 to GTX1060 and _model.fit_ method begin to crashes with "RuntimeError: Cuda Error: unspecified launch failure". I removed and deleted all related to nvidia software and installed it from the scratch but it doesn't help. I use CUDA 9.0 and run code in jupyter notebook. Tensorflow and Keras works normally.
Each time it crashes on different percentage of completion. Training takes ~ 2 min and in jupyter notebook it crashed in 100% cases not reaching 40% completion.
If I run same code from cmd, it crashes in ~50% cases reaching 80-99%.

On first launch error is following:

RuntimeError                              Traceback (most recent call last)
<ipython-input-15-4cd35792a9e3> in <module>()
     46 
     47     # train the model
---> 48 model.fit(ratings)
     49 
     50 user_items = ratings.T.tocsr()

c:\users\johnu\appdata\local\programs\python\python36\lib\site-packages\implicit\als.py in fit(self, item_users)
    148 
    149         if self.use_gpu:
--> 150             return self._fit_gpu(Ciu, Cui)
    151 
    152         solver = self.solver

c:\users\johnu\appdata\local\programs\python\python36\lib\site-packages\implicit\als.py in _fit_gpu(self, Ciu_host, Cui_host)
    199                 solver.least_squares(Cui, X, Y, self.regularization, self.cg_steps)
    200                 progress.update(.5)
--> 201                 solver.least_squares(Ciu, Y, X, self.regularization, self.cg_steps)
    202                 progress.update(.5)
    203 

implicit/cuda/_cuda.pyx in implicit.cuda._cuda.CuLeastSquaresSolver.least_squares()

RuntimeError: Cuda Error: unspecified launch failure (implicit/cuda/als.cu:137)

**But second time error appears in another class:**

RuntimeError                              Traceback (most recent call last)
<ipython-input-16-4cd35792a9e3> in <module>()
     46 
     47     # train the model
---> 48 model.fit(ratings)
     49 
     50 user_items = ratings.T.tocsr()

c:\users\johnu\appdata\local\programs\python\python36\lib\site-packages\implicit\als.py in fit(self, item_users)
    148 
    149         if self.use_gpu:
--> 150             return self._fit_gpu(Ciu, Cui)
    151 
    152         solver = self.solver

c:\users\johnu\appdata\local\programs\python\python36\lib\site-packages\implicit\als.py in _fit_gpu(self, Ciu_host, Cui_host)
    187             self.user_factors = self.user_factors.astype(np.float32)
    188 
--> 189         Ciu = implicit.cuda.CuCSRMatrix(Ciu_host)
    190         Cui = implicit.cuda.CuCSRMatrix(Cui_host)
    191         X = implicit.cuda.CuDenseMatrix(self.user_factors.astype(np.float32))

implicit/cuda/_cuda.pyx in implicit.cuda._cuda.CuCSRMatrix.__cinit__()

RuntimeError: Cuda Error: unspecified launch failure (implicit/cuda/matrix.cu:47)

**Comment by benfred** [comment]
Hmm - I don't know what could be causing this to be honest. Does this also happen with the BPR model or just the ALS model?

In the short term, you can probably use the CPU version instead (pass use_gpu=False to the model constructor).

**Comment by Antossio** [comment]
It happens with ALS, rest of the models works fine.
CPU version of ALS also works fine.

**Comment by Antossio** [comment]
Finally, I find the reason and solution
https://training.acceleware.com/blog/timeout-detection-windows-display-driver-model-when-running-cuda-kernels-symptoms-solutions-and

**Comment by benfred** [comment]
awesome! good to know
