### ISSUE TITLE
Getting new recommendations

### ISSUE THREAD

**Issue by arundasK** [benfred/implicit#145]
Hi, I am relatively new to recommendation systems and implicit library. I tried a tutorial program for music recommendation using implicit library. But every time I train model, I am getting different recommendations for same training data and user id. Please help me to understand what causes this issue. Thanks in advance.

**Comment by benfred** [comment]
It's probably random initialization leading to different results, more info here: https://github.com/benfred/implicit/issues/96#issuecomment-387150932
