### ISSUE TITLE
A bug with Implicit ALS Alternating Least Squares

### ISSUE THREAD

**Issue by jessiejc23** [benfred/implicit#146]
Hi Ben,

I have been using the implicit.als.AlternatingLeastSquares class for a few months but today when I ran it, it gave the error: 

> model = implicit.als.AlternatingLeastSquares( factors = 80, regularization = 0.1, iterations =50)
> AttributeError: module 'implicit' has no attribute 'als'

Is this possibly a bug? Does it happen the same on your side?

Thanks.

**Comment by jessiejc23** [comment]
Nope there is no directory of either implicit or als. This implicit library is installed using pip then at the top I would just type "import implicit".

**Comment by benfred** [comment]
@jessiejc23 what does this print out for you?

```python
import os
import implicit
print(implicit.__file__)
print(os.listdir(os.path.dirname(implicit.__file__)))
```

The first line should have the install directory of this package, and the second should have a list of files there (including als.py).

**Comment by y-tee** [comment]
similar issue. tried the codes above. showed same error 
```
AttributeError: module 'implicit' has no attribute 'als'
```

**Comment by jessiejc23** [comment]
The cause of the problem I had last time was that I named the file as implicit.py.

**Comment by vladfulgeanu** [comment]
This issue still happens.

Output of the commands suggested by @benfred :
```
/home/vagrant/venv/lib/python3.5/site-packages/implicit/__init__.py
['_nearest_neighbours.cpython-35m-x86_64-linux-gnu.so', 'als.py', '__pycache__', 'cuda', 'lmf.cpython-35m-x86_64-linux-gnu.so', 'datasets', 'approximate_als.py', 'nearest_neighbours.py', 'recommender_base.cpython-35m-x86_64-linux-gnu.so', '_als.cpython-35m-x86_64-linux-gnu.so', 'utils.py', 'evaluation.cpython-35m-x86_64-linux-gnu.so', '__init__.py', 'bpr.cpython-35m-x86_64-linux-gnu.so']
```
