### ISSUE TITLE
evaluation module crashes

### ISSUE THREAD

**Issue by kolomietsdv** [benfred/implicit#149]
Hello! 
First of all- thank you for your work! 
I trying to use FaissAlternatingLeastSquares model and evaluate it checking map and precision metrics from your evaluate module. 
While it works good with cpu model it always crashes the jupyter kernels in gpu mode spilling an error 
"Faiss assertion 'k <= 1024' failed in void faiss::gpu::IVFFlat::query(faiss::gpu::Tensor<float, 2, true>&, int, int, faiss::gpu::Tensor<float, 2, true>&, faiss" 
I use all default parameters and k=23, (rank=32, alpha=4, regularization=4, 10 iterations)
Can you check the possibility of measuring metrics on FaissALS, Im not good and programming, so I couldnt figured out the problem...
Thank you.

**Comment by XiangYongzhou** [comment]
Hi there,
Please look at the code in approximate_als.py
line 383 - line 395
implicit is filtering liked item from recommendation result.
```python
 user = self._user_factor(userid, user_items, recalculate_user)

        # calculate the top N items, removing the users own liked items from
        # the results
        liked = set(user_items[userid].indices)
        if filter_items:
            liked.update(filter_items)
        count = N + len(liked)
```
if count size is greater than 1024. It will exceeds faiss GPU limitation.
I work around the issue by using CPU version if the size is greater than 1024. 
You can also control the size of input query as well.

**Comment by benfred** [comment]
@XiangYongzhou Nice catch!

I've fixed up the faiss/gpu code here https://github.com/benfred/implicit/commit/e4817ab1596a935d4eb89f9dd4944623b760736e to fall back to using the exact CPU version if we are asking for more than 1K items. This should fix the problem here .

This will be in the next release, but you can pull from master here to get this fix in the meantime
