### ISSUE TITLE
Difference between rank_items and recommend

### ISSUE THREAD

**Issue by oliviernguyenquoc** [benfred/implicit#151]
Hi everyone,

I would like to know what is the difference between those two function.

Is rank_items the same than recommend function with a white list of items and N=number of items in the white list ?

If not, I don't understand the role of rank_item.

**Comment by benfred** [comment]
The recommend method will return the top N results from all possible items, and rank_items takes a list of itemids - and will rank every single one of them for the user.  rank_items will usually be quite a bit slower than recommend ...

**Comment by oliviernguyenquoc** [comment]
Thank you for all. 
If I understand well if I use recommend method with blacklist and rank_item with a whitelist (the opposite to the blacklist) I should have the same result. 
I will test that. In my usecase, I have better performance with rank_item (maybe due to the size of my blacklist).

Can suggest a modification of the doc (if I find a better wording) ?

**Comment by ita9naiwa** [comment]
There are no big performance gap between rank_items and recommend for ALS model and BPR model but rank_items is quite slow for nearest neighbors method. 

and Yes. you should get same results if you do as you mentioned.

**Comment by oliviernguyenquoc** [comment]
I confirm I have the same results but rank_item is much more performant, in my case, when the blacklist is big (80% of all items).

Thank you.
