### ISSUE TITLE
cython_lapack.posv error

### ISSUE THREAD

**Issue by tosolveit** [benfred/implicit#153]
Hi,
I have python 2.7.13 with the following packages:
- Cython = 0.25.2
- Scipy = 1.1.0

When I want to fit a model with some parameters I get this error:

> Traceback (most recent call last):
  File "code/optimize.py", line 185, in <module>
    regularization=0.4)
  File "code/optimize.py", line 75, in calculate_recommendations
    model.fit(plays)
  File "/Users/ilker/anaconda/lib/python2.7/site-packages/implicit/approximate_als.py", line 211, in fit
    super(AnnoyAlternatingLeastSquares, self).fit(Ciu)
  File "/Users/ilker/anaconda/lib/python2.7/site-packages/implicit/als.py", line 164, in fit
    num_threads=self.num_threads)
  File "implicit/_als.pyx", line 55, in implicit._als.least_squares
  File "implicit/_als.pyx", line 119, in implicit._als._least_squares
ValueError: cython_lapack.posv failed (err=1) on row 3. Try increasing the regularization parameter.

In the last line of the error output it says that ValueError is at row 3, when I run it different times I get this error for different rows in my data set, instead of using my data I tried using movie-lens 100k and got the similar error, In the [source code ](https://github.com/benfred/implicit/blob/master/implicit/_als.pyx) comment says that it may happen due to missing regularization parameter, I'm sure that I pass the parameter, what might be the other possible problems? How can I solve this problem?

Thanks

**Comment by benfred** [comment]
Interesting. This works with the movielens 100k dataset for me (running  the movielens example included here:```python examples/movielens.py --variant 100k``` ). Do you have source code to reproduce the problem?

**Comment by tosolveit** [comment]
Hi @benfred , I think It was my mistake, I fixed the error by changing parameters, probably it was related to gpu parameter and that caused the problem, you can close the issue, sorry for taking your time.
