### ISSUE TITLE
Can not install on google colaboratory

### ISSUE THREAD

**Issue by leilanorouzi** [benfred/implicit#160]
Hi,
I am working on google colaboratory. After new updating, the package can not be installed. It seems it has a problem in bdist_wheel. 
Running setup.py bdist_wheel for implicit ... error
Failed building wheel for implicit

**Comment by benfred** [comment]
Can you post the full error message?  Also what version of python are you trying to build for?

The implicit v0.3.8 update addresses a problem with installing with python 3.7.  It shouldn't break anything, it's just bumping the cython version used to generate the .cpp files.

**Comment by teguhash** [comment]
google colab uses python 3.6.6
I think this is what caused the failed installation:
```
implicit/cuda/als.cu:5:10: fatal error: cublas_v2.h: No such file or directory
     #include "cublas_v2.h"
              ^~~~~~~~~~~~~
    compilation terminated.
```
here is the link to the colab notebook that has the full errors
https://colab.research.google.com/drive/1F1jdTIMeS83BJBudKGrJS0h-wD9A6mXS

**Comment by huyhoang17** [comment]
```bash
!apt install cuda
!pip install implicit==0.3.8
```
solved the problem, thanks @teguhash

**Comment by divya074** [comment]
on google colab i tried to install MIDI module
!pip install -q python-midi
library is not installing
output i got is
Collecting python-midi
Using cached https://files.pythonhosted.org/packages/8d/e1/fd34aa05508d907449fb2d66a679d4f98eeeacdb4b3c7e6af87d91c4fa21/python-midi-v0.2.4.tar.gz
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-2bqotnco/python-midi/

**Comment by dimka11** [comment]
Nowadays implicit can't build in Colab

**Comment by benfred** [comment]
@dimka11 there were some issues with setuptools in google colab (see https://github.com/benfred/implicit/issues/499) : . Can you try building w/ `pip install git+https://github.com/benfred/implicit.git@18a8010b07e8a86f8eb37f837b5bbda11647501f` ?

**Comment by lucascalero** [comment]
That fixed it for me! I first installed apt installed cuda, not sure if that made a difference. Thanks!

**Comment by benfred** [comment]
I've verified that implicit v0.5.1 can be installed on google colab here https://github.com/benfred/implicit/issues/533#issuecomment-1024507928 - closing this issue

**Comment by bulat15g** [comment]
That works! TY @benfred

**Comment by benfred** [comment]
There are also binary wheels up on pypi now - so installing on colab with `pip install implicit` won't require compiling from source and should complete in a couple seconds now
