### ISSUE TITLE
Can not install Implicit on Windows 7

### ISSUE THREAD

**Issue by martisaju** [benfred/implicit#162]
Hello, 
I'm using python 3.6.6 on Windows 7 and I am trying to install implicit package v0.3.6 using

pip install implicit==0.3.6

It seems I'm getting an errors but I don't know what can I do to solve it. I downloaded and installed Microsoft Visual C++ 14.0 but I don't know if I have to add it to PATH or how can I install implicit package using it:

![error1](https://user-images.githubusercontent.com/29142274/47284645-647f6680-d5e8-11e8-9f19-77bb525684b8.png)

Any idea? Thanks!

**Comment by benfred** [comment]
I haven't tried on windows 7 - but I think it should work. 

You will need the compiler (cl.exe etc) on the PATH, which should have happened as part of the VS install.

There are a bunch of notes here: https://github.com/benfred/implicit/issues/76 that might be of help.

If you are using anaconda, the easiest way is to probably install like ```conda install -c conda-forge implicit``` . This grabs prebuilt binaries from conda-forge, meaning that you won't need to compile on your own system.

**Comment by ruojol** [comment]
I ran into the same error in win 10 although I have the build tools for c++ 14 installed. I noticed that the condaforge version doesn't have support for GPU which would have been superb...
