### ISSUE TITLE
recommend() throws TypeError for K-NearestNeighbors

### ISSUE THREAD

**Issue by ftroeman** [benfred/implicit#167]
```
model = implicit.nearest_neighbours.TFIDFRecommender()
model.fit(plays)
model.recommend(1,plays.T.tocsr())
```

Does not work (for CosineRecommender() or BM25Recommender() as well). The following error is thrown:

```
~\Anaconda3\lib\site-packages\implicit\nearest_neighbours.py in recommend(self, userid, user_items, N, filter_already_liked_items, filter_items, recalculate_user)
     36         indices, data = self.scorer.recommend(userid, user_items.indptr, user_items.indices,
     37                                               user_items.data, K=items,
---> 38                                               remove_own_likes=filter_already_liked_items)
     39         best = sorted(zip(indices, data), key=lambda x: -x[1])
     40 

implicit/_nearest_neighbours.pyx in implicit._nearest_neighbours.NearestNeighboursScorer.__pyx_fused_cpdef()

TypeError: No matching signature found
```

similar_items() and rank_items() work just fine, and plays is a CSR matrix with dimensions (Number of Users, Number of Items) as required. Would really appreciate some advice regarding this!

**Comment by benfred** [comment]
what does ```plays.T.tocsr().dtype``` show ? If it's not a float32 or float64 can you convert and try again?

**Comment by ftroeman** [comment]
Hey Ben, thanks for the swift response!

Indeed, it showed 'int32' and worked as soon as it was converted. Must have been something I missed while studying the Cython code. Thanks for the help!
