### ISSUE TITLE
Scores in recommend and rank_items does not match?

### ISSUE THREAD

**Issue by BlueAce17** [benfred/implicit#172]
Hi Benfred!

I'm having an issue in the recommendation process. I'm using your library for making songs recommendations to playlists, I have 50446 playlists and 20635 possible tracks. I tried the it and it works just great! I wanted to include it in my hybrid model and in order to do this I just need a numpy array with a score for each item. 
I tried:
- using the recommend function like this "recommended_items = model.recommend(user_id, user_items_matrix, 20635)"; in this case the top recommendations work really fine, but the problem is that the recommend function does not output a list of 20635 elements (as it should do, I guess) but a shorter list with less elements (between 20600 and 20630), so I'm not able to use its result (I need an array of length 20635...)
- using the rank_items function; in this case the function correctly outputs a list of the desired length, but the problem here is that the recommendation works a lot worse! I tried to have a look at the scores for some items and they do not match with the recommend function (neither in the score number neither in the order between scores)... I call the function as "rank_items(userid, user_items, all_items)" where all_items is a list of all 20635 tracks.

I'm 100% sure that I'm missing something here, but I really cannot figure out what it is! I'd really appreciate a hint.

Thank you in advance

**Comment by BlueAce17** [comment]
Yes, but it does not solve the issue... I actually solved my problem giving an arbitrarily negative score to non listed tracks (I assumed that they were not listed because unrelevant), but if someone has some idea on why this does not work for me I'd appreciate it :)

**Comment by Kai-42** [comment]
@BlueAce17 

The recommend function drops items which the user (or rather the playlist in the context of your post) has already 'liked'.

Copypasta from the codebase:
`def recommend(self, userid, user_items,
                  N=10, filter_already_liked_items=True, filter_items=None, recalculate_user=False):`

You'll note that the default parameter of filter_alread_liked_items defaults to True. Might be a case of RTFM vs TLDR.

I recommend this topic closed.

**Comment by BlueAce17** [comment]
Yeah, that was clearly it! I don't know how I missed it. 
Thanks a lot man.

I'm closing the topic.
