### ISSUE TITLE
wrong dimension in safety check?

### ISSUE THREAD

**Issue by orenshk** [benfred/implicit#182]
https://github.com/benfred/implicit/blob/6b16c50d1d514a814f2e5b8cf2a829ff23dbba63/implicit/recommender_base.py#L168

Shouldn't this be `max(selected_items) >= user.items.shape[0]...` since `fit` expects `user_items` to row items and column users?

**Comment by benfred** [comment]
It's a little confusing, but the fit method expects a item_users  matrix (row items and column users) and the rank_items and recommend methods expect an user_items matrix (row users and column items).  The lastfm example handles this appropiately by taking the transpose after fitting: https://github.com/benfred/implicit/blob/master/examples/lastfm.py#L129

I've been thinking about changing the fit method to be consistent for a while, but this will break dependencies =(
