### ISSUE TITLE
AttributeError: 'AlternatingLeastSquares' object has no attribute 'predict_for_customers'

### ISSUE THREAD

**Issue by christhng** [benfred/implicit#183]
If you could advise, please

Error as per below
AttributeError: 'AlternatingLeastSquares' object has no attribute 'predict_for_customers'

**Comment by benfred** [comment]
The methods on the ALS class are listed here : https://implicit.readthedocs.io/en/latest/als.html - and there isn't a 'predict_for_customers' method. Maybe try the [recommend](https://implicit.readthedocs.io/en/latest/als.html#implicit.als.AlternatingLeastSquares.recommend) method instead?
