### ISSUE TITLE
scores in rank_items 

### ISSUE THREAD

**Issue by tepeal** [benfred/implicit#186]
Hi, 

Thanks for this package. I try to use ALS in my project. How should i approach to the scores returned by rank_items? Is treating them as probabilities makes sense?

**Comment by jvalle3** [comment]
Hi @tepeal, did you come up with any idea/tip? I am wondering how to set a consistent threshold to discriminate whether the recommendations are "good enough" to give them back to a user. The returned scores seem to depend on the number of latent factors and the confidence value used in the train matrix (alpha).

**Comment by tepeal** [comment]
Hi @jvalle3. In my project, I try to recommend one specific item to family members. So, for a family sized 4 people, I have scores like -0.4, 0.3, 0.8, 1.3. To calculate probabilities, I have added absolute value of the minimum score (0.4 for this home) to all scores then divided this new scores by sum of all scores.
I hope it helps.
