### ISSUE TITLE
Return the completed item_user matrix

### ISSUE THREAD

**Issue by fwmeng88** [benfred/implicit#187]
Dear Ben. I am using `implicit` for my own project. Thank you for making such a good package! My problem is how can I get a completed item_user matrix or user_item matrix after done `model.fit()`? Thank you!

**Comment by rwinklerwilkes** [comment]
The fitted model object will have user_factors and item_factors arrays which can be matrix multiplied together:

import numpy as np
user_item_matrix = np.dot(model.user_factors,model.item_factors.T)

**Comment by fwmeng88** [comment]
Thank you very much for the solution! @rwinklerwilkes
