### ISSUE TITLE
How to get user's latent vector with userid?

### ISSUE THREAD

**Issue by pymoon** [benfred/implicit#194]
I am trying to get all user's latent vector after training the model, with the method model.user_factors. However, the result does not contain the userid. So how can i get a specific user's latent vector?
for example, userid = 90239, but the user_factor.shape[0] is below 50000;

need your help.

**Comment by jvalle3** [comment]
Hi @pymoon, depending on what you call userid:

If your **userid** is an index of the input matrix (item-user matrix, a.k.a. Riu), then you should check the shape of that matrix. The userid should be an index of the **columns** of the Riu matrix: 
    
    # this should be true
    model.fit(Riu)
    Riu.shape[1] == model.user_factor.shape[0]
    Riu.shape[0] == model.item_factor.shape[0]

If your **userid** is a custom id string, and you are generating the Riu matrix in some preprocessing step, you should store the mapping userid -> index. For example:
    
    user_map = list(df['user_id'].unique())
    ...
    userid = '90239'
    idx = user_map.index(userid)
    factors = model.user_factor[idx]

Hope it helps

**Comment by pymoon** [comment]
@jvalle3 this method works well, thanks !
