### ISSUE TITLE
BPR ignores the weight value of the matrix

### ISSUE THREAD

**Issue by lucidyan** [benfred/implicit#197]
I wanted to use the BPR model on my data, but I discovered that the model ignores weights. 
https://github.com/benfred/implicit/blob/ed4fb0ae3d62972b956d7c94d495d198ec6185fe/implicit/bpr.pyx#L130-L131
Is there any chance that this will be done in the future? And I didn't see any implementations of BPR that support that functionality.

**Comment by benfred** [comment]
The [BPR paper](https://arxiv.org/ftp/arxiv/papers/1205/1205.2618.pdf) ignores weights - and I've just implemented as described. 

Fwiw, I think [lightfm](https://github.com/lyst/lightfm) has extended BPR w/ a weighted version. You might want to check it out.
