### ISSUE TITLE
Using alpha parameter from Yifan Hu's paper

### ISSUE THREAD

**Issue by Jesse-Kerr** [benfred/implicit#199]
Hi, I want to use the alpha parameter as used in Yifan Hu's paper, but it appears to not be in the model.fit() function? I don't mind implementing it myself, but I'm not entirely clear whether that will adversely affect the ALS algorithm. 

In Hu's paper, they implement alpha as c_ui = 1 + (alpha(r_ui), where r_ui is the # of interactions for a user_item and c_ui is the confidence for that user_item pair. If we follow that equation, the zeros turn to 1's- will this algorithm still work in that case?

I saw in jessesxw's blog post(A gentle introduction to recommenders) that he added it in himself, but his implementation was slightly different from Yifan Hu. 

Thanks a lot for any advice.

Jesse

**Comment by avanY** [comment]
We use alpha by multiplying the rating(r_ui) before passing the matrix to the model.

**Comment by Jesse-Kerr** [comment]
Thank you @avanY , that helps to explain. Do you know what happens if we only have binary 0 and 1 data, how the ALS algorithm treats that? Thank again

**Comment by avanY** [comment]
@Jesse-Kerr I'm not completely sure, but using alpha should help. But it might be better if there is any way we can associate some strength to the preference and use this instead of binary preference, as these are the conditions where this model will perform the best.
