### ISSUE TITLE
pip installing version 0.1.5

### ISSUE THREAD

**Issue by sessinger** [benfred/implicit#20]
`pip install implicit`  Successfully installed implicit-0.1.7
`import implicit`
`implicit.__version__` '0.1.5'

Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Dec  6 2015, 18:08:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2

**Comment by benfred** [comment]
I've uploaded the most recent version to pypi - should be installing v0.2.1 now
