### ISSUE TITLE
Support configurable progress meters

### ISSUE THREAD

**Issue by mdekstrand** [benfred/implicit#200]
Over in LensKit, we are using configurable progress meters in various places; for example [BiasedMF](http://lkpy.lenskit.org/en/latest/mf.html#lenskit.algorithms.als.BiasedMF) takes such an option.

A progress meter is expected to be a TQDM-compatible progress function (the precise feature set required varies from system to system). What this lets us do, though, is pass `tqdm_notebook` when running code from a Jupyter notebook, yielding a nicely GUI progress bar.

It seems like it should not be very difficult to make the trainers, such as `BPR`, take a configurable progress function. Then notebooks would be pretty :)

**Comment by ita9naiwa** [comment]
It would be nice!
If you make PR, I'll check it, or I'll modify code if i have some time to do that.

**Comment by benfred** [comment]
Good idea!

For getting a GUI progress bar in jupyter, I'm using ```tqdm.auto``` here https://github.com/benfred/implicit/pull/240 to switch between tqdm_notebook and tqdm as appropiate. This will be in the next release
