### ISSUE TITLE
Score interpretation

### ISSUE THREAD

**Issue by pwierzgala** [benfred/implicit#202]
Could you explain how score returned by ALS recommend method should be interpreted? I trained a model with user-item ratings ranging from 1 to 5 and got correct recommendations but with very low scores like 0.012 or 0.008.

(1) Should I expect recommendations with scores ranging from 1 to 5?
(2) Should I care about the score value or only about order or recommendations?
(3) Does it tell me anything when the score is low?

**Comment by ita9naiwa** [comment]
Refer http://yifanhu.net/PUB/cf.pdf

ALS does not take explicit scores, but interactions as 0 or 1.
elements in the matrix is interpreted as intensity, or confidence of the observation.

**Comment by pwierzgala** [comment]
Thanks for the paper. I read it and here are my answers to my questions:

(1) No. 
- Implicit library expects user_items matrix to contain implicit ratings like number of times an item was bought, viewed or added to a basket. From my understanding of equation (3) from the paper, which is implemented in implicit library, the values returned by the ALS model should be close to 0-1 range.
- For explicit ratings like score, thumbs or stars, equation (2) form the paper should be used, which is slightly different than the one for implicit data. 
-  If explicit ratings are used with implicit library, we can't expect the model to return values in range of explicit ratings.
(2) The higher the score is the more likely the item should be recommended. The score value itself (without context) doesn't tell you much.
(3) This was answered in (2).

**Comment by ita9naiwa** [comment]
Great!
The paper isn't easy to read (at least for the first time). You got through it!
I'm glad that you've understand the concept of ALS.
