### ISSUE TITLE
Getting error while installing pyaudio on Windows

### ISSUE THREAD

**Issue by RaghavSaggu** [benfred/implicit#206]
![Capture](https://user-images.githubusercontent.com/17244350/57581724-322c4c80-74d9-11e9-9cba-c9e66ba17f73.JPG)

I don't want to install Microsoft Visual Studio of size 1.3GB, Please suggest me how I can install Microsoft Visual C++ 14.0 only?

**Comment by benfred** [comment]
This project has nothing to do with pyaudio
