### ISSUE TITLE
[question] is there a way to plot train and validation loss with implicit ? 

### ISSUE THREAD

**Issue by karthikraja95** [benfred/implicit#209]
Any help is appreciated.

**Comment by ita9naiwa** [comment]
`recommender.fit` iterates `self.iterations` times. First you set iteration=1 when you initialize recommender object. Then call `recommender.fit` one time and gather loss.

Things might go like this

```python
recommender = AlternatingLeastSquares(iterations=1, )
n_iter = 100 
precisions = []
for i in range(n_iter):
    recommender.fit(train_data, show_progress=False) # iterate one time
    
    precision = calc_precision(recommender, validation_data) # you can define this part
    precisions.append(precision)
plot(precisions)
```
I know this isn't quite beautiful but it's only way to do that as far as I know.
