### ISSUE TITLE
install from source to enable GPU

### ISSUE THREAD

**Issue by lethaiq** [benfred/implicit#216]
Please fix the README file to instal from source to enable GPU training.
Install from pip repository: pip install implicit -> would not enable GPU.
I think it does not have some recent fixes.

**Comment by ita9naiwa** [comment]
I'll update soon

**Comment by benfred** [comment]
Installing from pip should be able to enable GPU training (it does a source install). It's just installing from conda that won't have GPU enabled. I added a note to the readme here: https://github.com/benfred/implicit/commit/38f4da210b738efae28714a071eb1a373141ad62
