### ISSUE TITLE
AttributeError: module 'implicit.evaluation' has no attribute 'ndcg_at_k'

### ISSUE THREAD

**Issue by valepog** [benfred/implicit#220]
Hi.
I am trying to use the evaluations methods in order to test my recommender system.
When I use precision_at_k and mean_average_precision_at_k everything seems to run just fine.
Unfortunately, when I try to use the ndcg_at_k method I get the following error:
AttributeError: module 'implicit.evaluation' has no attribute 'ndcg_at_k'

Is there anything I am missing on the use of this method?Any idea on why I get this error? 
Thank you for your time.

**Comment by ita9naiwa** [comment]
Hi. latest pip version of implicit does not have `ndcg_at_k` yet.

If you want to use ndcg@k, install this library manually and install by `python setup.py install`.

We'll update the version but I don't know when.

**Comment by ita9naiwa** [comment]
I'd like to update the version of implicit after I finished to code some other mterics, such as AUC.

**Comment by data-steve** [comment]
I've downloaded this package from git and used `python setup.py install`, then checked in ipython shell but I can't seem to find support for any of the `implicit.evaluation` functionality. Where do I get access to this?

**Comment by benfred** [comment]
Changes are in the latest version (v0.3.9).

**Comment by Muniuliuma** [comment]
> I'd like to update the version of implicit after I finished to code some other mterics, such as AUC.

I want to know when new evaluation indicators can be added

**Comment by ita9naiwa** [comment]
AUC added
