### ISSUE TITLE
[HELP] Getting top 10 recommendations given a userID and particular ItemID 

### ISSUE THREAD

**Issue by karthikraja95** [benfred/implicit#221]
Hello Everyone!

I have two questions?

1. How to get top 10 recommended items given a userID and a ItemID?
Example : UserID - 1001 and that user say purchased itemID 1234, Then how do we get the top 10 recommendations based on the UserID -1001 and itemID 1234.

2. Is there a way to get hit ratio and ndcg for the data?

Thanks for helping.

**Comment by GerrBert** [comment]
Hello.
i think that there have an error.
for one user this work. But if i change this to another "user_id", it won't work.

def user_items(items):
    item_ids = [offer_ids[s] for s in items if s in offer_ids]
    data = [1 for _ in item_ids]
    rows = [0 for _ in item_ids]
    shape = (1, model.item_factors.shape[0])
    return scipy.sparse.coo_matrix((data, (rows, item_ids)), shape=shape).tocsr()
xxx = user_items([9148955329465708066])
model.recommend(userid=0, user_items=xxx)

**Comment by karthikraja95** [comment]
Hi @GerrBert Let me try this and get back to you

**Comment by GerrBert** [comment]
@karthikraja95 it means, that for me it don't work ( but maybe i am not cool enough with implicit), but i think it should work.
If it will be work for you, let me know, please.

**Comment by GerrBert** [comment]
Also have this problem. Can't have user prediction with 
xxx = user_items([9148955329465708066])
model.recommend(userid=0, user_items=xxx)
if userid is not zero. 

Error is IndexError: index (2) out of range

**Comment by Maartenraaij** [comment]
Hi @GerrBert,

I had a similar problem before. 
You must make sure that all of the item_ids and all of the user_ids are consecutive and start from zero before you fit your ALS model. This is due to the fact that spicy matrices cannot store index labels, so it creates a reset numerical index. That is, the first user_ids in your data will get index = 0, the second user_id will get index = 1 and so on.

Let me know if this is clear enough and if it helps!

**Comment by GerrBert** [comment]
@Maartenraaij , hi, thank you. 
A don't understand docs right. I gave in this function new items of user and think, that in this function i should indicate userid of the original matrix.

**Comment by karthikraja95** [comment]
> Hello.
> i think that there have an error.
> for one user this work. But if i change this to another "user_id", it won't work.
> 
> def user_items(items):
> item_ids = [offer_ids[s] for s in items if s in offer_ids]
> data = [1 for _ in item_ids]
> rows = [0 for _ in item_ids]
> shape = (1, model.item_factors.shape[0])
> return scipy.sparse.coo_matrix((data, (rows, item_ids)), shape=shape).tocsr()
> xxx = user_items([9148955329465708066])
> model.recommend(userid=0, user_items=xxx)
