### ISSUE TITLE
AttributeError: 'AlternatingLeastSquares' object has no attribute 'recommend_all'

### ISSUE THREAD

**Issue by silentknight0** [benfred/implicit#222]
The directory of als and bpr don't have the feature recommend all, the code is there in recommender_base but it is not incorporated in the library.

**Comment by ita9naiwa** [comment]
Hi. the latest version of implicit in pypi does not have recommend_all yet.

We'll update the version soon!

**Comment by benfred** [comment]
in 0.3.9
