### ISSUE TITLE
Update version to 0.3.9

### ISSUE THREAD

**Issue by ita9naiwa** [benfred/implicit#223]
There are some changes on this lib

Add recommend_all function for factor based recommender systems
Add NDCG@K as evaluation metric

I know this is not a big change, but someone made issues on them so I thought its time to to update the version of Implicit and update PYPI.

AttributeError: ‘AlternatingLeastSquares’ object has no attribute ‘recommend_all
#222 
AttributeError: module ‘implicit.evaluation’ has no attribute ‘ndcg_at_k
#220

**Comment by ita9naiwa** [comment]
I want to listen to your thought about updating.

Regards

**Comment by LouisdeBruijn** [comment]
pip install implicit --upgrade or pip install implicit==0.3.9 show that 0.3.8 is still the most up-to-date version ?

**Comment by benfred** [comment]
Pushed 0.3.9 with those changes
