### ISSUE TITLE
Expected in: flat namespace

### ISSUE THREAD

**Issue by yananchen1989** [benfred/implicit#23]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-9eae7608d57c> in <module>()
----> 1 import implicit

/Users/yanan.chen/anaconda/lib/python2.7/site-packages/implicit/__init__.py in <module>()
      1 from .als import alternating_least_squares
      2
----> 3 from . import nearest_neighbours
      4 from . import als
      5

/Users/yanan.chen/anaconda/lib/python2.7/site-packages/implicit/nearest_neighbours.py in <module>()
      5 from scipy.sparse import coo_matrix, csr_matrix
      6
----> 7 from ._nearest_neighbours import all_pairs_knn
      8 from .recommender_base import RecommenderBase
      9 from .utils import nonzeros

ImportError: dlopen(/Users/yanan.chen/anaconda/lib/python2.7/site-packages/implicit/_nearest_neighbours.so, 2): Symbol not found: __ZdlPvm
  Referenced from: /Users/yanan.chen/anaconda/lib/python2.7/site-packages/implicit/_nearest_neighbours.so
  Expected in: flat namespace
 in /Users/yanan.chen/anaconda/lib/python2.7/site-packages/implicit/_nearest_neighbours.so

**Comment by yananchen1989** [comment]
How to solve this problem.

**Comment by benfred** [comment]
The same error seemed to be occuring for a bunch of Theano users too: http://stackoverflow.com/questions/42729958/python-theano-undefined-symbol-zdlpvm-error/42832716#42832716

The issue there seems to be a problem with a too new version of GCC. Can you try the steps there, I can't reproduce this on my machine.

**Comment by benfred** [comment]
I had this same error on my ubuntu v16.04 when running gcc6 and anaconda3 - downgrading to gcc 5 fixed.
