### ISSUE TITLE
recommend_all map back to users matrix

### ISSUE THREAD

**Issue by LouisdeBruijn** [benfred/implicit#233]
recommend_all function has come back to the ALS model with v/ 0.3.9, but I don't understand how to map back this numpy 2d array back to the recommendation per user.  I've got a numpy array with top-10 recommendations from model.recommend_all(N=10, user_items=sparse_user_item), but how can I see which recommendation is for which user?

**Comment by ita9naiwa** [comment]
It should return (n_users, topk) sized 2d array,

https://github.com/benfred/implicit/blob/fbed6211547e676ba414fdf734432aa3252ac90b/implicit/recommender_base.pyx#L217-L221

doesn't it?

**Comment by LouisdeBruijn** [comment]
Yes I've got it thanks!
