### ISSUE TITLE
No CUDA extension has been built, can't train on GPU.

### ISSUE THREAD

**Issue by fporrata** [benfred/implicit#235]
Hello benfred, 
I found this problem in other issues but they are closed.  Below are the settings of my evironment.

I have Windows 10. I am using implicit 0.3.9 but still I cannot build. I tried CUDAHOME = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0 and CUDAHOME = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin but did not work. My Path variable has C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64 for the library. Please let me know if you can help. I am in the middle of a big project and need to use the GPU to get results faster. Thank you very much

**Comment by Lihengwannafly** [comment]
This issue also occurs in Ubuntu.

**Comment by Lihengwannafly** [comment]
> This issue also occurs in Ubuntu.
The following commands solve the issus for me:
```
git clone https://github.com/benfred/implicit.git
python setup.py install
python cuda_setup.py install
```
