### ISSUE TITLE
MatrixFactorizationBase.recommend requires user_items

### ISSUE THREAD

**Issue by MartinThoma** [benfred/implicit#236]
If `filter_already_liked_items` is False, then `user_items` is not required. Hence it would be desirable to set `user_items` by default to `None` and throw an exception if `filter_already_liked_items` is True.

**Comment by ita9naiwa** [comment]
You're right.

It seems because of compatibility with KNN recommender.

**Comment by benfred** [comment]
Yeah - we need the user_items parameter for API compatibility with the KNN models, and for filter_already_liked_items (which is default True) and for recalculate_user. You can pass in a None value in some cases, but I'm not in favour of changing the API
