### ISSUE TITLE
Question about evaluation train/test split

### ISSUE THREAD

**Issue by Ellyuca** [benfred/implicit#239]
Hi.
I have a question about the train/test split function used for evaluation.
The functions is the following: 
def train_test_split(ratings, train_percentage=0.8):
    """ Randomly splits the ratings matrix into two matrices for training/testing.

What do you mean by ratings matrix? Is it the item_users matrix that we use for model fitting?

Thanks you.
Have a nice day.

**Comment by ita9naiwa** [comment]
Yes. either user_item matrix or transposed item_user matrix is okay.

**Comment by Ellyuca** [comment]
Thank you very much!
