### ISSUE TITLE
Does model.recommend_all() use GPU?

### ISSUE THREAD

**Issue by Lihengwannafly** [benfred/implicit#244]
When I use model.recommend_all() to predict for all users, then the error memory error. Then I set the num_threads=2 and then it works. But it computes very slowly.

**Comment by ita9naiwa** [comment]
No... it does not use GPU.  could you share the error message exactly?

**Comment by Lihengwannafly** [comment]
> No... it does not use GPU. could you share the error message exactly?

It should be a oom error. But I found that the user martirx and item matirx can be extracted, so i can use tensorflow to do recommendation.
`tf.tensordot(user_tensor, item_factors, axes=[1, 1])`
