### ISSUE TITLE
when model is training, GPU runs out of memory.

### ISSUE THREAD

**Issue by dongdong865** [benfred/implicit#247]
i use aws g3.4xlarge machine. GPU memory is 8G and users number is 40 million. Then GPU runs out of memory. How to solve it? Can it run on multiple GPUS?

**Comment by benfred** [comment]
It can't run on multiple GPU's right now. 

You're probably running out of memory on storing the user factors. Assuming num_factors=64 - the factor storage alone for your data would be 10GB.  I'd try pruning out inactive users during model fitting, and then infer the values during prediction using recalculate_user=True. This probably won't hurt the accuracy of predictions (see http://technocalifornia.blogspot.com/2012/07/more-data-or-better-models.html). 

Alternatively you could run this on the CPU using a high memory instance
