### ISSUE TITLE
the cython.parallel of precision_at_k, why not occupy almost all the CPU

### ISSUE THREAD

**Issue by sodamnsure** [benfred/implicit#251]
I see two cores 50% being used, and eight cores 25% being used ,why? I want see that using multi-thread will occupy almost all the CPU . Apparently it's not a good way out. 

I pasted and copied the contents above. To be honest, my English is not very good

**Comment by ita9naiwa** [comment]
https://github.com/benfred/implicit/blob/b0a2da0a6a56b03464d2c9f448ff9c55194bec5e/implicit/evaluation.pyx#L104-L121

the parallelism blocked by gil during making recommendations. I think this is the reason why the `precision_at_k` function cannot occupy 100% of CPU time...

**Comment by sodamnsure** [comment]
Although did not solve the problem, but at least explained the problem wrong place, thank you very much for your answer!
