### ISSUE TITLE
ALS works not true

### ISSUE THREAD

**Issue by nmtruong93** [benfred/implicit#252]
I installed the implicit version 0.4.0, after training model with ALS, I received all nan item_factors and user_factors.

I tried to train with Bayesian Personalized Ranking and it works well.

Could you check whether the ALS algorithm has a problem?

**Comment by ita9naiwa** [comment]
Could you show me the error message and your input data?

I checked and it works fine for me.

**Comment by nmtruong93** [comment]
I just run again today, it works fine. Thank you
