### ISSUE TITLE
Prediction on a particular item for a selected user

### ISSUE THREAD

**Issue by karthikraja95** [benfred/implicit#253]
Hi all,

I am new to recommender systems; I used ALS and BPR methods from implicit code base for my recommendations. My question is, let's say I want to predict the value of a particular item for a selected user.

For example: 
UserID - 4307
ItemID - 9024
Ground_truth - 1.0
Prediction_Output - ?

How do I find the prediction score for the above problem? Is there any inbuilt function available in implicit in doing that? If not, can you suggest a way to do that? 

Thanks

**Comment by pangeran-bottor** [comment]
Would be this https://implicit.readthedocs.io/en/latest/als.html#implicit.als.AlternatingLeastSquares.explain suit your problem?

**Comment by karthikraja95** [comment]
Loaded a trained model, and tried to use explain function, but I got the following error? Do you have any idea?



**loaded_als_model.explain(72927,sparse_user_item,7062)**


TraceBack:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-42-118aca71636c> in <module>
----> 1 loaded_als_model.explain(72927,sparse_user_item,7062)

C:\ProgramData\Anaconda3\lib\site-packages\implicit\als.py in explain(self, userid, user_items, itemid, user_weights, N)
    253             A, _ = user_linear_equation(self.item_factors, self.YtY,
    254                                         user_items, userid,
--> 255                                         self.regularization, self.factors)
    256             user_weights = scipy.linalg.cho_factor(A)
    257         seed_item = self.item_factors[itemid]

C:\ProgramData\Anaconda3\lib\site-packages\implicit\als.py in user_linear_equation(Y, YtY, Cui, u, regularization, n_factors)
    334 
    335     for i, confidence in nonzeros(Cui, u):
--> 336         factor = Y[i]
    337 
    338         if confidence > 0:

IndexError: index 91237 is out of bounds for axis 0 with size 86448

**Comment by ita9naiwa** [comment]
```
user_index = 4307
item_index = 9024

model.user_factor[user_index].dot(model.item_factor[item_index]) 
```
will give the result what you want.

**Comment by ita9naiwa** [comment]
or you can use `rank_items` function

please refer 
https://implicit.readthedocs.io/en/latest/als.html#implicit.als.AlternatingLeastSquares.rank_items

**Comment by ita9naiwa** [comment]
I'm sorry about that we don't have example code like calculating scores of specific items w.r.t specific users.

**Comment by ita9naiwa** [comment]
Or, you can use `rank_items` function

https://implicit.readthedocs.io/en/latest/als.html#implicit.als.AlternatingLeastSquares.rank_items

```
rank_items(4307, user_item_matrix, [9024)
```
will return  [(9024, score)]

**Comment by karthikraja95** [comment]
Thanks, @ita9naiwa, rank_items function works for both ALS and BPR, and it returns [(item_id, score)] that's what I want to calculate and compare different metrics of different algorithms. 

Thanks Again
