### ISSUE TITLE
[Request] Additional filter for items

### ISSUE THREAD

**Issue by ds2268** [benfred/implicit#26]
Hi @benfred,

Can you add in the official library the option for recommend method to accept additional list of items, that you don't want to include in the recommendations. Therefore we would still get for example top N items (excluding the items from given list) instead of filtering afterwards where you prune given recommendations and get less than the number of requested recommendations.

Thanks!

**Comment by benfred** [comment]
This shouldn't be too hard to add - we are already filtering out items that the user has viewed from the result set: https://github.com/benfred/implicit/blob/master/implicit/als.py#L88-L89 and extending that for other items should be pretty easy.

**Comment by ds2268** [comment]
@benfred I agree, I can prepare PR because I need this functionality anyway :)

**Comment by ds2268** [comment]
@benfred thank you for your fast response. It is possible to make this version accessible through pip repository. I guess new version tag is needed for this.

**Comment by benfred** [comment]
You're right - the version needs updated and I need to push changes to pypi.

I'll do this this weekend - I won't really have an opportunity before tomorrow night.

**Comment by benfred** [comment]
I've bumped the version number here, and pushed to pypi: https://github.com/benfred/implicit/commit/a50fb1b8752181bf3d34574e6da9473bd33fdc0b
