### ISSUE TITLE
SSL errors when running lastfm.py

### ISSUE THREAD

**Issue by dnaeye** [benfred/implicit#261]
When running the `lastfm.py` sample script, I run into the following errors:
- `ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)`
- `urllib.error.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)>`

Being a newb, I have no idea what these mean and solutions to similar issues after Googling have not helped.

**Comment by ita9naiwa** [comment]
It seems that downloading lasftm dataset is the problem.

**Comment by benfred** [comment]
Agreed looks like a SSL problem with your python installation. Maybe check out this stackoverflow post : https://stackoverflow.com/questions/44316292/ssl-sslerror-tlsv1-alert-protocol-version
