### ISSUE TITLE
Division by zero when training matrix is very sparse (BPR)

### ISSUE THREAD

**Issue by chedatomasz** [benfred/implicit#264]
While training a BPR model on some matrices I came across an error:

  File "implicit/bpr.pyx", line 186, in implicit.bpr.BayesianPersonalizedRanking.fit
  File "implicit/bpr.pyx", line 194, in implicit.bpr.BayesianPersonalizedRanking.fit
ZeroDivisionError: float division by zero
The matrix I supplied contains a single positive interaction. It seems like the division happens while updating the progress tracker. I am not sure how exactly this should be resolved: would adding a check for zero be too big of an overhead?

**Comment by ita9naiwa** [comment]
Could you show the data used to train?
I cannot reproduce the problem now

**Comment by chedatomasz** [comment]
A minimal code sample to reproduce:
`import scipy.sparse
from implicit.bpr import BayesianPersonalizedRanking

model = BayesianPersonalizedRanking()
sparse = scipy.sparse.csr_matrix([[0, 0, 0], [0, 1, 0], [0, 0, 0]])
model.fit(sparse)
`

**Comment by chedatomasz** [comment]
I am using implicit 0.4.0 installed through pypi, if that helps

**Comment by chedatomasz** [comment]
I have added a PR fixing just this issue, as requested.

**Comment by chedatomasz** [comment]
Will this be fixed?

**Comment by ita9naiwa** [comment]
I can merge #271 , but for me it's hard to check #265 .

**Comment by ita9naiwa** [comment]
Great!
