### ISSUE TITLE
Scores higher than 1

### ISSUE THREAD

**Issue by alex-molas** [benfred/implicit#270]
I'm using ALS to perform recommendations. However, sometimes I'm getting values greater than 1. 

How can it be this possible? Shouldn't they be in the range from (-1, 1)? From the source code, we know that the score is computed as:

`user = self._user_factor(userid, user_items, recalculate_user)`
`scores = self.item_factors.dot(user)`

Maybe it should be normalized in some way to avoid values higher than 1?

Thank you for your help!

**Comment by ita9naiwa** [comment]
Its possible.
ALS can give score higher than 1, and lower than 0

**Comment by ita9naiwa** [comment]
You may want to use LMF to bound score in (0,1)(it uses sigmoid, als doesnt)

**Comment by soliverc** [comment]
Hi @alex-molas did you figure out a method to normalize the returned scores? I'm having difficulty with the scoring system too. I basically can't understand it. I'm getting scores as high as 50 when I use `model.similar_users(user_id, n_similar)`. Others are around 0.004, some are 1.5, some are negative for the `recommend()` function. 

I've tried LMF but the scores go up to 20. And it recommended totally different artists (and genre) compared to ALS.
