### ISSUE TITLE
Hello! I am trying to install pycocotools. 

### ISSUE THREAD

**Issue by khan958** [benfred/implicit#279]
(base) C:\Users\IrfanKhan>pip install pycocotools
Collecting pycocotools
  Using cached https://files.pythonhosted.org/packages/96/84/9a07b1095fd8555ba3f3d519517c8743c2554a245f9476e5e39869f948d2/pycocotools-2.0.0.tar.gz
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\irfankhan\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\IRFANK~1\\AppData\\Local\\Temp\\pip-install-mqwnu8n6\\pycocotools\\setup.py'"'"'; __file__='"'"'C:\\Users\\IRFANK~1\\AppData\\Local\\Temp\\pip-install-mqwnu8n6\\pycocotools\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\IRFANK~1\AppData\Local\Temp\pip-wheel-csawbjvf' --python-tag cp36
       cwd: C:\Users\IRFANK~1\AppData\Local\Temp\pip-install-mqwnu8n6\pycocotools\
  Complete output (13 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-3.6\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.6\pycocotools
  copying pycocotools\mask.py -> build\lib.win-amd64-3.6\pycocotools
  copying pycocotools\__init__.py -> build\lib.win-amd64-3.6\pycocotools
  running build_ext
  building 'pycocotools._mask' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for pycocotools
  Running setup.py clean for pycocotools
Failed to build pycocotools
Installing collected packages: pycocotools
  Running setup.py install for pycocotools ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\irfankhan\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\IRFANK~1\\AppData\\Local\\Temp\\pip-install-mqwnu8n6\\pycocotools\\setup.py'"'"'; __file__='"'"'C:\\Users\\IRFANK~1\\AppData\\Local\\Temp\\pip-install-mqwnu8n6\\pycocotools\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\IRFANK~1\AppData\Local\Temp\pip-record-i65bxi3i\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\IRFANK~1\AppData\Local\Temp\pip-install-mqwnu8n6\pycocotools\
    Complete output (13 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\pycocotools
    copying pycocotools\coco.py -> build\lib.win-amd64-3.6\pycocotools
    copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.6\pycocotools
    copying pycocotools\mask.py -> build\lib.win-amd64-3.6\pycocotools
    copying pycocotools\__init__.py -> build\lib.win-amd64-3.6\pycocotools
    running build_ext
    building 'pycocotools._mask' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\irfankhan\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\IRFANK~1\\AppData\\Local\\Temp\\pip-install-mqwnu8n6\\pycocotools\\setup.py'"'"'; __file__='"'"'C:\\Users\\IRFANK~1\\AppData\\Local\\Temp\\pip-install-mqwnu8n6\\pycocotools\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\IRFANK~1\AppData\Local\Temp\pip-record-i65bxi3i\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by ita9naiwa** [comment]
why are you asking a problem with pycocotools here?

**Comment by khan958** [comment]
it's show me this error?
