### ISSUE TITLE
unable to install topicexplorer..keeps giving visual c++ required error 

### ISSUE THREAD

**Issue by vidb6** [benfred/implicit#280]
I have been trying to install topicexplorer via git cmd, but it keeps failing for this error. I install build tools and visual c++, still no improvement. Installing ujson gives the same error. 

Please help.

` Running setup.py install for ujson ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\username\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-hnyclrm2\\ujson\\setup.py'"'"'; __file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-hnyclrm2\\ujson\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\username\AppData\Local\Temp\pip-record-4vtl1lxf\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\username\AppData\Local\Temp\pip-install-hnyclrm2\ujson\
    Complete output (6 lines):
    Warning: 'classifiers' should be a list, got type 'filter'
    running install
    running build
    running build_ext
    building 'ujson' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\username\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-hnyclrm2\\ujson\\setup.py'"'"'; __file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-hnyclrm2\\ujson\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\username\AppData\Local\Temp\pip-record-4vtl1lxf\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.`

**Comment by wxkpythonwork** [comment]
I get the same error info

**Comment by benfred** [comment]
Not related to this package - closing
