### ISSUE TITLE
[HELP] Plot train loss for ALS, BPR using implicit?

### ISSUE THREAD

**Issue by karthikraja95** [benfred/implicit#281]
Is there any way to plot train loss for ALS and BPR using implicit? I was searching for some inbuilt function but couldn't find any. Can anyone tell me how do I plot it? Any help is appreciated.

Thanks
K

**Comment by ita9naiwa** [comment]
I'm looking for solution to this.

I considered Tensorboard first, but it seems to add tensorflow to dependency.

**Comment by ita9naiwa** [comment]
In another way, somehow the model gives loss during training will be Okay?

then you can plot loss graph with your tools

**Comment by ita9naiwa** [comment]
I'll try visdom.

**Comment by ita9naiwa** [comment]
check #282

**Comment by ita9naiwa** [comment]
![Uploading image.png…]()

**Comment by ita9naiwa** [comment]
https://github.com/benfred/implicit/blob/59cd5e693fef5eceda3ea0e999519c3db9fa6fca/implicit/als.py#L48-L59

**Comment by ita9naiwa** [comment]
https://github.com/benfred/implicit/blob/59cd5e693fef5eceda3ea0e999519c3db9fa6fca/implicit/als.py#L48-L59

try passing validate_step a value like 3

**Comment by karthikraja95** [comment]
> In another way, somehow the model gives loss during training will be Okay?
> 
> then you can plot loss graph with your tools like matplotlib.

That should be okay I guess, If i have the loss then I can plot it using some tools like matplotlihb

**Comment by karthikraja95** [comment]
> I'm looking for solution to this.
> 
> I considered Tensorboard first, but it seems to add tensorflow to dependency.
> 
> Could you have any idea for this?

Same, I was thinking about tensorflow or other tools like visdom but we need to add tensorflow dependency

**Comment by karthikraja95** [comment]
> https://github.com/benfred/implicit/blob/59cd5e693fef5eceda3ea0e999519c3db9fa6fca/implicit/als.py#L48-L59
> 
> try passing validate_step a value like 3

If I am correct this will give the loss for validation set right, I want to know the loss on train set

**Comment by ita9naiwa** [comment]
Training loss calculation is not implemented for BPR, LMF. It should be implemented and I'll see that

**Comment by benfred** [comment]
I've plotted the training loss as part of this post https://www.benfrederickson.com/fast-implicit-matrix-factorization/. 

I did this by using the 'fit_callback' option on the ALS model. The code to do this is here:
https://github.com/benfred/implicit/blob/45c85a126a1455c67915ae40c842b64a8cc77dfe/benchmarks/benchmark_als.py#L16-L36

**Comment by franziweindel** [comment]
Hi, 
I am trying to use the above code to plot the training loss however I get the error message 
"TypeError: inner() missing 1 required positional argument: 'loss'". I see the training loss next to the side bar while fitting the model, however I do not know how to save this output. 

Thanks for the help!

**Comment by filiptrivan** [comment]
Here's a slightly simpler scenario approach based on @benfred answer:

```
def train_model(sparse_user_product):
    model = implicit.als.AlternatingLeastSquares(factors=100, regularization=0.1, alpha=1.0, iterations=15, calculate_training_loss=True)
    losses = list()
    model.fit_callback = store_loss(losses)
    model.fit(sparse_user_product, show_progress=False)
    return model
```

```
def store_loss(output: list): 
    def inner(iteration, elapsed, loss): 
        output.append(f"Loss {loss:.5f}\n") 

    return inner
```
