### ISSUE TITLE
UnboundLocalError: local variable 'vali_user_items' referenced before assignment

### ISSUE THREAD

**Issue by filion** [benfred/implicit#286]
`factors=10
regularization=0.01
iterations=15

model = implicit.als.AlternatingLeastSquares(factors=factors,regularization=regularization,iterations=iterations)
model.fit(items_users)
`
Gives an error

/usr/local/lib/python3.6/dist-packages/implicit/als.py in fit(self, item_users, show_progress)
    175 
    176         if self.use_gpu:
--> 177             return self._fit_gpu(Ciu, Cui, vali_user_items, show_progress)
    178 
    179         solver = self.solver

UnboundLocalError: local variable 'vali_user_items' referenced before assignment

**Comment by filion** [comment]
It should be noted that the code did work until some days ago

**Comment by ita9naiwa** [comment]
Im sorry i modified some codes.

Train/validation split occurs during when train function is called.

**Comment by ita9naiwa** [comment]
Check #283

**Comment by ita9naiwa** [comment]
Pass validate_proportion parameter when initialize model, and don't pass vali_item_user in train.

**Comment by chedatomasz** [comment]
This is a major breaking api change. If a GPU is found, the code is broken if validation is not enabled, which is also the default. Please revert or at least fix and bump version. @benfred

**Comment by filion** [comment]
> 
> 
> This is a major breaking api change. If a GPU is found, the code is broken if validation is not enabled, which is also the default. Please revert or at least fix and bump version. @benfred

!pip install implicit==0.4.0 will do the trick

**Comment by ita9naiwa** [comment]
> This is a major breaking api change. If a GPU is found, the code is broken if validation is not enabled, which is also the default. Please revert or at least fix and bump version. @benfred

Sorry I made a mistake.

**Comment by ita9naiwa** [comment]
I'm testing patch right now...

**Comment by ita9naiwa** [comment]
I uploaded hotfix to this.(version 0.4.2)

thanks @filion @chedatomasz

**Comment by chedatomasz** [comment]
Could you actually deploy the fix to version 0.4.1, so that the broken version is no longer available for download?

**Comment by ita9naiwa** [comment]
@chedatomasz  I'd like to do so, but i can't find how to disable downloading 0.4.1

**Comment by benfred** [comment]
I've deleted release 0.4.1 on pypi

**Comment by benfred** [comment]
This code has been reverted from master, closing
