### ISSUE TITLE
UnboundLocalError: local variable 'vali_item_users' referenced before assignment

### ISSUE THREAD

**Issue by kwonmha** [benfred/implicit#290]
I tried using `BayesianPersonalizedRanking`.
When I run `fit()` after initializing, it says,
```
File "implicit/bpr.pyx", line 205, in implicit.bpr.BayesianPersonalizedRanking.fit
UnboundLocalError: local variable 'vali_item_users' referenced before assignment
```

1. It looks that the variable name is wrong. 
It should be `vali_user_items` as in `als.py`?

2. I changed code of `bpr.pyx` as above on my computer.
But it doesn't have any effect.
There is no file named `bpr.pyx` in `site-packages/implicit` directory.
It makes me wonder what `bpr.pyx` does the class(BayesianPersonalizedRanking) refer.
Since I'm not familiar with pyx file, I can't figure out how to make it work as I intended.

Thx.

**Comment by ita9naiwa** [comment]
check https://github.com/benfred/implicit/issues/286

1. I made mistakes. do not use implicit 0.4.1. update to 0.4.2(will be reverted), or use (0.4.0)

2.`.pyx` files are translated to cpp files and compiled as a shared object.

**Comment by kwonmha** [comment]
1.
I'm using 0.4.2 version.
Your fix assigns `None` to `vali_user_items` and my error is about `vali_item_users`.

I'll try 0.4.0.

2. Would you tell me more about why the system work as the same even though I modified pyx?

**Comment by ita9naiwa** [comment]
1. It didn't correcltly fixed seems... I made a mistake again too...
CPU version will work fine.

2. run `python setup.py install`again.

**Comment by ita9naiwa** [comment]
Could you test to reinstall implicit 0.4.2 version to occur same error message?

**Comment by kwonmha** [comment]
I reinstalled implicit.
But it still shows the same error.
The last release date is still 24, Oct when I checked pypi.
Maybe it's not updated to the server?

I'll test this again next Monday.

And I hope my pull request to be merged if it's okay - fixed as same as your fix. :)

**Comment by ita9naiwa** [comment]
I reverted PRs related to validation.  #282 

Downgrade implicit to v0.4.0 please.
 sorry.

**Comment by benfred** [comment]
This issue isn't in master anymore, and the 0.4.1 release has been deleted

**Comment by thinline72** [comment]
@benfred Sorry, I got a bit confused with versions. I'm using 0.4.2 (the latests from pip) and getting the same error if I try to use GPU. So looks like I have to downgrade to 0.4.0 to use GPU, right?

I see that you mentioned the issues isn't in the master anymore. Just wondering are there any plans to make a 0.4.3 release that would include this fix in the nearest future?

Thanks!
