### ISSUE TITLE
ImportError: cannot import name 'ranking_metrics_at_k' from 'implicit.evaluation'

### ISSUE THREAD

**Issue by ioulaki** [benfred/implicit#294]
I'm trying to import ranking_metrics_at_k, using Spyder inside Anaconda, but I'm getting the aforementioned error.

Moreover, could you please clarify what the scores returned from the recommend method indicate? the confidence in the recommendation?

Thanks a lot!

**Comment by ita9naiwa** [comment]
the latest version of implicit (0.4.0) has `ranking_metrics_at_k`.

I couldn't understand your second question. sorry...

Sorry for late response.
