### ISSUE TITLE
BPR on CUDA crashing when training matrix is empty

### ISSUE THREAD

**Issue by chedatomasz** [benfred/implicit#296]
When I try to train the bpr recommender on an empty matrix, it crashes with the following error:
  File "implicit/bpr.pyx", line 174, in implicit.bpr.BayesianPersonalizedRanking.fit
  File "implicit/bpr.pyx", line 209, in implicit.bpr.BayesianPersonalizedRanking._fit_gpu
  File "implicit/cuda/_cuda.pyx", line 60, in implicit.cuda._cuda.CuIntVector.__cinit__
IndexError: Out of bounds on buffer access (axis 0)

From what I can see, the constructor of CuIntVector tries to access the first element of the data it is passed - if there is no element, it crashes. I am not sure how it should be resolved - I looked around and the assumption that the matrix is not empty appears in quite a few places, so perhaps it would be better to just add a built in fallback to CPU training in that case? Data transfers make GPU training slower for small matrices anyway.

Also, it seems like GPU training is leaking memory. It is freed when the python process that created the recommender exits, however, creating multiple recommenders one after the other, even deleting the previous one explicitly, leads to an OOM error on the GPU (allocation fails).

**Comment by benfred** [comment]
Should be fixed in last PR - thanks!
