### ISSUE TITLE
Memory leak in BPR on CUDA

### ISSUE THREAD

**Issue by chedatomasz** [benfred/implicit#298]
When repeatedly creating and destroying recommenders, the BPRRecommender on cuda leaks memory. I have managed to identify the cause:
In line 125 of bpr.cu:
`curandGenerator_t rng;
CHECK_CURAND(curandCreateGenerator(&rng, CURAND_RNG_PSEUDO_DEFAULT));
CHECK_CURAND(curandSetPseudoRandomGeneratorSeed(rng, seed));`
the generator is created, but it is never destroyed. 
A quick fix is adding a line just before the return:
`curandDestroyGenerator(rng);`
I will submit a PR fixing this shortly.

**Comment by chedatomasz** [comment]
I added the fix to the standing PR fixing crashes on sparse matrices.

**Comment by benfred** [comment]
Should be fixed in last PR
