### ISSUE TITLE
Why I am getting this 'gcc' failed?

### ISSUE THREAD

**Issue by TedSIWEILIU** [benfred/implicit#300]
I have tried to put the code below before import
`import pyximport 
pyximport.install()`

But now it gives me the error below:

"distutils.errors.CompileError: command 'gcc' failed with exit status 1\n"

my gcc version is : gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**Comment by benfred** [comment]
Is this related to this package? Why are you using pyximport ?
