### ISSUE TITLE
Can I convert model to file for using in another languages?

### ISSUE THREAD

**Issue by maziar-manouchehry** [benfred/implicit#303]
Thanks for your great library.
I need to convert the fitted model to use in another language like Java.
Can I export the model as a PMML file (like everything [sklearn2pmml](https://github.com/jpmml/sklearn2pmml) did for the Scikit-Learn models)?

Every help on this topic will be appreciated.

**Comment by benfred** [comment]
Thanks!

For ALS and BPR you could export the item_factors and user_factors matrices and then use in other languages. This should be fairly easy to get going if you want to do this yourself, but isn't something that I'm interested in supporting as part of this library.
