### ISSUE TITLE
Price-matching Gorse

### ISSUE THREAD

**Issue by DonaldTsang** [benfred/implicit#304]
See https://github.com/zhenghaoz/gorse#recommenders as they have a good short list of recommender algorithms that may be missing from implicit.

**Comment by benfred** [comment]
Thanks for the suggestion!

Looking at the list of recommenders listed there - we have all the implicit versions aside from the popularity baseline.  This package is solely focused on implicit feedback, and we won't be implementing things like SVD++ or slope1.

**Comment by DonaldTsang** [comment]
@benfred could you offer the full list as to which are implemented and which are not?
- ItemPop
- KNN (Implicit)
- WRMF 
- BPR
