### ISSUE TITLE
Questions regarding LibRec

### ISSUE THREAD

**Issue by DonaldTsang** [benfred/implicit#305]
According to https://github.com/guoguibing/librec#features there are 70 algorithms available for recomendations, is it possible to read through each one and see if they can be re-implemented in Python (since Python is much more flexible)?

**Comment by benfred** [comment]
It's possible to do that - but I'm not going to do it =). I'm open to pull requests if you want to implement any missing algorithms that you think belong here

**Comment by DonaldTsang** [comment]
@benfred would like to put this up for public bidding though, since the more people can see this the better.
