### ISSUE TITLE
pip install of mysql fails with error 1

### ISSUE THREAD

**Issue by chuckuntulis** [benfred/implicit#306]
Earlier attempts to install generated a "error: Microsoft Visual C++ 14.0 is required." error. I installed Visual Studio successfully and I get a bit farther but now I see the following, but I can not find the log file that is mentioned at the end of the output. 

c:\>py -m pip install mysql
Collecting mysql
  Using cached https://files.pythonhosted.org/packages/bf/5f/b574ac9f70811df0540e403309f349a8b9fa1a25d3653824c32e52cc1f28/mysql-0.0.2.tar.gz
Collecting mysqlclient
  Using cached https://files.pythonhosted.org/packages/d0/97/7326248ac8d5049968bf4ec708a5d3d4806e412a42e74160d7f266a3e03a/mysqlclient-1.4.6.tar.gz
Installing collected packages: mysqlclient, mysql
    Running setup.py install for mysqlclient ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\chuck\AppData\Local\Programs\Python\Python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\chuck\\AppData\\Local\\Temp\\pip-install-i44ljdgl\\mysqlclient\\setup.py'"'"'; __file__='"'"'C:\\Users\\chuck\\AppData\\Local\\Temp\\pip-install-i44ljdgl\\mysqlclient\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\chuck\AppData\Local\Temp\pip-record-mauy4vbv\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\chuck\AppData\Local\Temp\pip-install-i44ljdgl\mysqlclient\
    Complete output (26 lines):
    C:\Users\chuck\AppData\Local\Programs\Python\Python37-32\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\MySQLdb
    copying MySQLdb\__init__.py -> build\lib.win32-3.7\MySQLdb
    copying MySQLdb\_exceptions.py -> build\lib.win32-3.7\MySQLdb
    copying MySQLdb\compat.py -> build\lib.win32-3.7\MySQLdb
    copying MySQLdb\connections.py -> build\lib.win32-3.7\MySQLdb
    copying MySQLdb\converters.py -> build\lib.win32-3.7\MySQLdb
    copying MySQLdb\cursors.py -> build\lib.win32-3.7\MySQLdb
    copying MySQLdb\release.py -> build\lib.win32-3.7\MySQLdb
    copying MySQLdb\times.py -> build\lib.win32-3.7\MySQLdb
    creating build\lib.win32-3.7\MySQLdb\constants
    copying MySQLdb\constants\__init__.py -> build\lib.win32-3.7\MySQLdb\constants
    copying MySQLdb\constants\CLIENT.py -> build\lib.win32-3.7\MySQLdb\constants
    copying MySQLdb\constants\CR.py -> build\lib.win32-3.7\MySQLdb\constants
    copying MySQLdb\constants\ER.py -> build\lib.win32-3.7\MySQLdb\constants
    copying MySQLdb\constants\FIELD_TYPE.py -> build\lib.win32-3.7\MySQLdb\constants
    copying MySQLdb\constants\FLAG.py -> build\lib.win32-3.7\MySQLdb\constants
    running build_ext
    building 'MySQLdb._mysql' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\chuck\AppData\Local\Programs\Python\Python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\chuck\\AppData\\Local\\Temp\\pip-install-i44ljdgl\\mysqlclient\\setup.py'"'"'; __file__='"'"'C:\\Users\\chuck\\AppData\\Local\\Temp\\pip-install-i44ljdgl\\mysqlclient\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\chuck\AppData\Local\Temp\pip-record-mauy4vbv\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

What do I need to do to get mysql installed?

Thanks
Chuck

**Comment by chuckuntulis** [comment]
Was this posted in the wrong place? I really have no way to figure out why
this is failing. Do I just give up or look someplace else. In the past, my
infrequent requests have been met with at least one suggestion.

Thanks

Chuck

**Comment by chuckuntulis** [comment]
It isn't, but it seemed like it at the time. How would I find the right place because I am still uncertain how to navigate and communicate with the appropriate people?

Thanks for your response.

Chuck

**Comment by chedatomasz** [comment]
Please use google and look for pages related to either mysql or microsoft visual c++ build tools. A good start might be StackOverflow or the following post: https://answers.microsoft.com/en-us/windows/forum/all/visual-c-14/f0445e6b-d461-4e40-b44f-962622628de7

**Comment by chuckuntulis** [comment]
Thanks again.
