### ISSUE TITLE
Clarity on User-based Recommendation

### ISSUE THREAD

**Issue by aditya-malte** [benfred/implicit#307]
Hi,
I'm trying to replicate the recommend() method which recommends items based on user_id.
However, it is unclear to me how exactly user-item similarity work from the code.
Is it simply a dot product of the user factor with item factors? Shouldn't it be divided by the norms to convert it to cosine similarity?
(WITH REGARDS TO ALS)
Thanks

**Comment by benfred** [comment]
The predictor in ALS is the dot product - and not cosine similarity (dot product was used in the original paper).

**Comment by aditya-malte** [comment]
Thanks,
Yeah, reading the paper clarified it
