### ISSUE TITLE
Meaning of 'correct=X%' and 'skipped' in progress bar

### ISSUE THREAD

**Issue by ljmartin** [benfred/implicit#309]
Hi all,
This library has been really useful and I appreciate that its fast and well written, so thankyou. 

What is the meaning of the `correct` and `skipped` terms that appear next to the tqdm progress bar during fitting?
Real example:
```100% 16/16 [00:00<00:00, 39.95it/s, correct=99.67%, skipped=1.82%]```

Thanks!

**Comment by benfred** [comment]
With bpr, we're sampling triples of user/positive-item/negative-items. The %-correct value is showing how many times the positive item is ranked higher than the negative item for the user (so is basically AUC on the training set). When we sample the negative item, we also check to make sure the negative item is actually negative (like the user hasn't liked it). If the user has liked the item we skip training for these samples (and report number of samples skipped as %-skipped).

**Comment by ljmartin** [comment]
Got it, thanks!
