### ISSUE TITLE
Problem instantiating implicit == 0.1.4

### ISSUE THREAD

**Issue by HanichS** [benfred/implicit#315]
I'm having this issue:

The code breaks in this line
base_model = implicit.ALS()

That's the message error
AttributeError: module 'implicit' has no attribute 'ALS'

The implicit version is 0.1.4. The code works in my peer and mine machine, but breaks when we try to run on the cloud.

**Comment by ita9naiwa** [comment]
is the version of implicit library on the cloud `0.1.4`?

try 
```
from implicit.als import AlternatingLeastSquares as ALS
```

**Comment by benfred** [comment]
Version 0.1.4 is from 2016 - and the syntax has changed since then. I'm guessing when you run in the cloud you're getting a getting version.
