### ISSUE TITLE
.recommend() ignoring first item

### ISSUE THREAD

**Issue by mattcrooksBBC** [benfred/implicit#316]
I've fitted AlternatingLeastSquares to some user data with 9 items but when I run the recommend method I only get recommendations for items 1-8 and nothing for item 0. When I run rank_items() I get all 9 items ranked. My item_factors matrix also has 9 features. I've also tried shuffling the order of the items and recommend() ignores whichever item is in the first row. Clearly the ALS is solving properly but why won't recommend work properly?

**Comment by ita9naiwa** [comment]
`recommend` automatically filters items that user already have interacted. 
In this case, setting `filter_already_liked_items=False` will recommend correclty. isn't it the case?...

**Comment by wwwbbb8510** [comment]
I met the same issue. I was confused by the behaviour of `recommend` method at the beginning. It would be good to add this point into the README examples, or add it into one of the two files in the `example` folder.

**Comment by benfred** [comment]
thanks for pointint out! I've adde some notes about the filtering functionality in the tutorial here https://benfred.github.io/implicit/tutorial_lastfm.html#Making-Recommendations -
