### ISSUE TITLE
How to interpret scores? 

### ISSUE THREAD

**Issue by soliverc** [benfred/implicit#321]
I see in issue #270 that it's OK for scores to be higher than one. 

But how much higher than 1 can they go? I'm unsure of the scale here. 

For example, below are artist recommendations for a certain user (lastFM data). We can see the range from `1.2` to `1.5` using `model.recommend()`
```python

artist | score
jon lajoie | 1.522733
hot action cop | 1.392381
ronald jenkees | 1.363762
soundtracks | 1.345460
afroman | 1.326433
transplants | 1.285385
killradio | 1.266038
lustra | 1.255350
pezz | 1.250269
south park | 1.242974
```
Is `south park` the best artist to recommend to this user? Or should I only recommend if the score is closer to zero and disregard these? 

Other users show scores ranging from `1.0` to `1.2` or even negative numbers. 

When I use the `model.similar_users()` function, the score ranges from `50` to `60` when my `n` similar users are displayed. Do these high scores mean they are not similar in the slightest? 

And for `model.similar_items()` I got scores around `0.04`.

Is there a maximum / minimum score that will allow us to figure out how confident we can be with the results? I have no idea if the score of `60` is good or bad. The scoring scale could go to `5000` for all I know. 

Also in issue #270 it was recommended to use `LogisticMatrixFactorization` to bound scores between 1 and 0 ... I tried that and got scores up to 20. It also recommended completely different lastFM artists to ALS. 
Thanks

edit: here are artists similar to metallica. Metallica itself gets a score of 0.04. I'm guessing since metallica is literally equal to metallica, a score close to zero is very good. It's much lower than the scores I got from the  `model.recommend()` function at the beginning of my post. 

```python
  artist similar to Metallica     score
0                   metallica  0.043550
1            system of a down  0.043278
2               guns n' roses  0.043231
3                   rammstein  0.043230
4                       ac/dc  0.043155
5                guns n roses  0.043151
6                 iron maiden  0.043147
7                 tenacious d  0.043136
8                        koЯn  0.043067
9               the offspring  0.043035
```
However the devs scores for metallica are much higher (closer to 1) in his writeup. You can enter Metallica into the interactive table here: https://www.benfrederickson.com/matrix-factorization/

**Comment by ita9naiwa** [comment]
so far as I know, there is no absolute measure to figure out or to be confident with the recommendation results.

scores by BPR and ALS only gives relative order respective to the user or the item. 

A higher score of jon lajoie than that of south park means the model predicts that the user prefer jon lajoie to south park. the absolute score has no meaning. It changes a lot with regularisation changes.
