### ISSUE TITLE
How to reverse recommendation and get recommended users for an item?

### ISSUE THREAD

**Issue by soliverc** [benfred/implicit#322]
Is it as simple as reversing the dot product?

In the below I am using the ALS model to find users who might like a certain `item_id`:

Get recommendation vector of users for item
```python
recommendations = model_als.item_factors[item_id,:].dot(model_als.user_factors.T)
```
Get sorted top 400 recommended users
```python
num_users = 400
user_idx = np.argsort(recommendations )[::-1][:num_users]
```
Print sorted dataframe of users and score
```python
users = []
scores = []

# Loop through our recommended user indicies and look up the user
for udx in user_idx:
    users.append(data.user.loc[data.user_id == udx].iloc[0])
    scores.append(recommend_vector[udx])
```

Create a new dataframe with recommended artist names and scores
```python
recommendations = pd.DataFrame({'user': users, 'score': scores})

                                       user                                      score
0  f3c6eda720a3bf23a80f5fbf67ce0c07efa7e879  1.489363
1  bc217c8ff899e1746d80ee92a5e11eedc894be72  1.462239
2  25cb47b46f354ee7d5dc51e65ce8137e977e5180  1.395885
3  005c6e193f0b8c173dab0029f2dab79bb906a7d3  1.382000
4  d5e020b847c04fa2345a63a171b90bb678754cda  1.365232
```

Is this the correct way to go about it? I couldn't find a built in function that does this, unless there's a hacky way to do it with function native to implicit?

Could I use the `recommend` function and swap the inputs? E.g.: put the `item_id` instead of `userid` and `item_user` matrix instead of `user_items`?

Change this:
```
 recommend(userid, user_items,N=400)
```
To this:
```
 recommend(item_id, item_users,N=400)
```
When I do this I get a different set of recommendations / scores, and I'm unsure which method to go with.

**Comment by ita9naiwa** [comment]
```
    model_als.user_factors, model_als.item_factors = model_als.item_factors, model_als.user_factors
```
will work.

**Comment by soliverc** [comment]
Should your method give the same scores as the below?:

```python

# fit model
model.fit(data)

# mutiply user vectors by item vectors
user_item_matrix_recombined = np.dot(model.user_factors,model.item_factors.T)

# get user recommendations for item
user_item_matrix_recombined[:,item_id]
```
I am getting different scores

**Comment by star-yar** [comment]
I've made a few tests. Seems like scores for your method and _ita9naiwa_ match.
