### ISSUE TITLE
Implicit installation fails

### ISSUE THREAD

**Issue by ruojol** [benfred/implicit#323]
`creating build/temp.linux-x86_64-3.7/implicit
ERROR	2020-02-04 12:32:22 +0200	master-replica-0		    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c implicit/_als.cpp -o build/temp.linux-x86_64-3.7/implicit/_als.o -Wno-unused-function -Wno-maybe-uninitialized -O3 -ffast-math -fopenmp -std=c++11
ERROR	2020-02-04 12:32:22 +0200	master-replica-0		    implicit/_als.cpp:31:20: fatal error: Python.h: No such file or directory
`
_als.cpp refers to #include Python.h is this a python 3.7 build tools related error?

**Comment by soliverc** [comment]
I had trouble installing it from pip. Did you try anaconda?

**Comment by LiangqunLu** [comment]
I had the similar gcc error when I installed using pip. However, when I used the command **conda install -c conda-forge implicit**, I installed implicit-0.4.0 successfully. Maybe you can give a try.

**Comment by benfred** [comment]
@roujol you need to install the python header files to build extensions. See https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory 
You can avoid compiling from source by using the prebuilt binaries on conda-forge
