### ISSUE TITLE
Is iterative training possible?

### ISSUE THREAD

**Issue by dakl** [benfred/implicit#325]
Hi, thanks for a great tool! I would like to investigate how model performance changes over epochs/iterations and see that ALS has an (undocumented AFAIK) callback that I could use for this. The other models however doesn't seem to have that, based on some investigation of the source code.

Is it possible to run something like this:

```
for epoch in range(10):
    model.fit(...)
    some_evaluation_function(model, some_data)
```

or will multiple calls to fit reset the model?

**Comment by SavanGowda** [comment]
I am looking for the same, I just did a multiple calls of `model.fit()` just to check what I would get from that and then checked the user factors and item factors, which keeps changing and finally ends up giving **NaN** values.

**Comment by dakl** [comment]
I guess one potential solution to this is to go through the code base and create `fit_partital` methods all over the place and then let `fit` call that `iterations` times. @benfred any insight/plans/roadmap on this?
