### ISSUE TITLE
Hyperparameter Tuning and Crossvalidation

### ISSUE THREAD

**Issue by gehongsheng** [benfred/implicit#326]
Thanks for such a great library! And I appreciate that you have added some useful tools like the evaluation methods!
However, I realized that I really needed a function to help me with hyperparameter tuning and cross-validation. For the latter one, I have my own code to do that as it is not difficult. For the hyperparameter, it is not easy to write an efficient and fast algorithm especially when you need parallel computing.
The GridSearchCV package can only be used for these scikit-learn models and I cannot find a customized function to test the implicit data.
So, I would appreciate it if anyone knows how to deal with the hyperparameter and cross-validation.

**Comment by ita9naiwa** [comment]
check hyperopt library
