### ISSUE TITLE
model.similar_items but model.similar_users function not found

### ISSUE THREAD

**Issue by shuangshui** [benfred/implicit#33]
I don't know if I get this right,
but since 
related = model.similar_items(itemid,K)
return the best K similar itemID,
how can I find get the best K similar userID list given some userID?

looking forward to your reply

**Comment by benfred** [comment]
There is no function call built into the models right now, but it should be easy to add (at least for the ALS code). 

Calling this function with an AlternatingLeastSquares model should work (basically just taking cosine distance in the user_factors):

```python
def similar_users(model, userid, N=10):
    # note: recalculating norms per call is maybe not the most efficient
    user_norms = np.linalg.norm(model.user_factors, axis=-1)

    scores = model.user_factors.dot(model.user_factors[userid]) / user_norms
    best = np.argpartition(scores, -N)[-N:]
    return sorted(zip(best, scores[best] / user_norms[itemid]), key=lambda x: -x[1])
```

**Comment by shuangshui** [comment]
thank you! And this solved my problem.
Another issue is how can I get the predicted value from given a given user and item.
My code is like this:
t_pred=model.user_factors[t_user_index,:].dot(model.item_factors.transpose())[t_item_index]
then I tried t_pred=t_pred/model.item_norms[t_item_index]...but still not right. 
Because the actual value is much bigger than I get.
Could you please give some ideas on this too! 
thanks~~~

**Comment by benfred** [comment]
for a single user/item pair - the predicted value is just the dot product of the user factors and the item factors: ```model.user_factors[userid].dot(model.item_factors[itemid])```

**Comment by shuangshui** [comment]
Thanks for your reply 
I'll check my data further~~~
