### ISSUE TITLE
ranking_metrics_at_k bug

### ISSUE THREAD

**Issue by FilipDusek** [benfred/implicit#330]
I was comparing the results of `ranking_metrics_at_k` with results of my evaluation function and noticed a mismatch caused by what I believe is a bug in this function.

I should add I have made some guesses about how some of the functions behave because I'm not familiar with Cython and I might therefore be interpreting the code wrong. 

### Description
`ids` array is first initialized to zeros and then the recommendations are filled in. If there is < K recommendations, the remaining values are kept at zero:
https://github.com/benfred/implicit/blob/68720698e2fc05b4750f8c9cc5478d1c6b1692dc/implicit/evaluation.pyx#L248-L254

The recommended `ids` array is later iterated over and its checked whether the IDs are in the `likes` set. If they are the prediction is recognized as successful. The problem here is that `ids` array contains the zeros from initialization and therefore can make the model score points for items which the model has never predicted (items with id 0).
https://github.com/benfred/implicit/blob/68720698e2fc05b4750f8c9cc5478d1c6b1692dc/implicit/evaluation.pyx#L271-L279

Possible fix could be to initialize the `ids` array to -1 instead?

**Comment by ita9naiwa** [comment]
Thanks! I made PR

**Comment by medoidai** [comment]
I need this feature!

Please merge to master! @benfred

**Comment by ita9naiwa** [comment]
@medoidai Done

**Comment by medoidai** [comment]
Thank you!
