### ISSUE TITLE
Leverage GPU for recalculate_user

### ISSUE THREAD

**Issue by Stack-Attack** [benfred/implicit#331]
Hello,

I did a quick look through the code and noticed that the recalculate_user computation has no GPU implementation. I know this method was added later on, and so I'm not sure how re-usable the CUDA code might be for this application, but being able to leverage a GPU for this scenario would definitely be a plus as far as real-time implementations are concerned.

Best,
Kyle

**Comment by benfred** [comment]
Thanks for the suggestion!

This is done w/ https://github.com/benfred/implicit/pull/515 (as well as speeding up the CPU recalculate_user/item support) and will be in the next release.
