### ISSUE TITLE
ubuntu 18.04 w / gpu: No CUDA extension has been built, can't train on GPU.

### ISSUE THREAD

**Issue by samtriolo** [benfred/implicit#332]
Hi,

I'm having trouble getting implicit to train on the gpu.  Training on the cpu works just fine.  The gpu does work for other python libs like numba.  Any help would be appreciated.

The full implicit error I receive is:
```
~/cuda-test$ python my-implicit.py 
GPU training requires factor size to be a multiple of 32. Increasing factors from 100 to 128.
Traceback (most recent call last):
  File "my-implicit.py", line 32, in <module>
    gpu_model.fit(data)
  File "/home/samuel_triolo/cuda-test/py3.8/lib/python3.8/site-packages/implicit/als.py", line 179, in fit
                X[i], X[i + 1] = X[i + 1], X[i]
    return self._fit_gpu(Ciu, Cui, vali_user_items, show_progress)
  File "/home/samuel_triolo/cuda-test/py3.8/lib/python3.8/site-packages/implicit/als.py", line 218, in _fit_gpu
    raise ValueError("No CUDA extension has been built, can't train on GPU.")
ValueError: No CUDA extension has been built, can't train on GPU.
~/cuda-test$
```

The full code of my implicit test is attached.  As stated in the title, this is running on ubuntu 18.04 (image built by google cloud platform).  Additional configuration I performed on top of the base image:
 - export CUDA_PATH=/usr/local/cuda
 - installed the following in ubuntu: [cuda](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=deblocal), nvidia-cuda-dev, nvidia-cuda-toolkit

Python info: 
Python 3.8.0 (default, Oct 28 2019, 16:14:01) 
[GCC 8.3.0] on linux

A separate, attached python script leverages the gpu via the numba library and works successfully with the following output:
~/cuda-test$ python numba-gpu-test.py 
gpu available?: <Managed Device 0>
without GPU: 4.8885357239996665
with GPU: 0.8174731399994926

My issue appears similar to [this](https://github.com/benfred/implicit/issues/85).

[numba-gpu-test.py.txt](https://github.com/benfred/implicit/files/4315848/numba-gpu-test.py.txt)

[my-implicit.py.txt](https://github.com/benfred/implicit/files/4315860/my-implicit.py.txt)

**Comment by benfred** [comment]
Did you install from conda? We don't supply prebuilt CUDA extensions - so you will have to build them yourself. 

Going ```pip install py-spy``` will force this.

**Comment by samtriolo** [comment]
Hi @benfred , 

Appreciate you getting back to me - still not working, very possible I'm missing something in my build procedure.  Here's what I'm doing, let me know if something sticks out ("apt" is shorthand for "apt-get" below):
- build vanilla ubuntu 18.04 vm from scratch with nvidia gpu (current vm using tesla k80)
- apt update
- apt install install nvidia-cuda-dev
- install cuda from / using steps outlined [here](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=deblocal)
- apt install nvidia-cuda-toolkit
- sudo apt-get install python3.7 python3.7-dev python3-pip 
- sudo -H python3.7 -m pip install py-spy implicit (implicit builds with no errors / warnings)
- run "my-implicit.py" attached in my opening comment above
- my-implicit.py crashes with exception:
```$ python3.7 test-implicit-6-23.py
GPU training requires factor size to be a multiple of 32. Increasing factors from 100 to 128.
Traceback (most recent call last):
  File "test-implicit-6-23.py", line 27, in <module>
    gpu_model.fit(data)
  File "/usr/local/lib/python3.7/dist-packages/implicit/als.py", line 179, in fit
    return self._fit_gpu(Ciu, Cui, vali_user_items, show_progress)
  File "/usr/local/lib/python3.7/dist-packages/implicit/als.py", line 218, in _fit_gpu
    raise ValueError("No CUDA extension has been built, can't train on GPU.")
ValueError: No CUDA extension has been built, can't train on GPU.```

**Comment by samtriolo** [comment]
In addition to above, based on the comments [here](https://github.com/benfred/implicit/issues/85), I tried setting `export CUDAHOME=/usr/local/cuda/`, however that didn't change anything.  I tried rebuilding implicit as well using `pip uninstall` followed by `sudo -H python3.7 -m pip install implicit --no-cache-dir`, which didn't change anything either.

Not sure if it's relevant, but `nvcc --version` uses `/usr/bin/nvcc` and outputs:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
```

Whereas `/usr/local/cuda/bin/nvcc --version` outputs:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_May__6_19:09:25_PDT_2020
Cuda compilation tools, release 11.0, V11.0.167
Build cuda_11.0_bu.TC445_37.28358933_0
```

**Comment by dougturnbull** [comment]
I am having a similar problem and can't get  Implicit + Cuda working. I'm on Ubuntu 20.04 but might revert back to 18 to try to get it working. On differences is that now nvcc is installed in /usr/bin/nvcc while the cuda directory is in /usr/lib/cuda, 

@samtriolo did you ever get Cuda working with Implicit?

**Comment by samtriolo** [comment]
Hi @dougturnbull , no, my plan was to wait for Ben.

**Comment by dougturnbull** [comment]
@samtriolo For what it is worth, I revert backed to Ubuntu 18.04 and got implicit to work with my eGPU by following this guide:
https://medium.com/@exesse/cuda-10-1-installation-on-ubuntu-18-04-lts-d04f89287130
I'm a relative newbie to GPUs but this seemed to work for me. Not really sure why.

**Comment by maratakhm** [comment]
Hi
have same problem on Ubuntu 20.04 with python 3.8

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Jan__6_16:45:21_PST_2023
Cuda compilation tools, release 12.0, V12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0
```

cuda is available from torch, but not available from implicit.

seems to me I have ImportError on implicit/gpu/__init__.py:5

**Comment by zkLyons** [comment]
Have you solved it?I encountered the same issue

**Comment by Darinochka** [comment]
I encountered the same issue

**Comment by zkLyons** [comment]
> I encountered the same issue
Maybe you can try this command. If you're working on recommendation systems or machine learning-related code, try installing these two packages. That's how I solved it.
：
conda install -c conda-forge implicit implicit-proc=*=gpu

**Comment by zkLyons** [comment]
@Darinochka ，
Maybe you can try this command. If you're working on recommendation systems or machine learning-related code, try installing these two packages. That's how I solved it.

`conda install -c conda-forge implicit implicit-proc=*=gpu`
