### ISSUE TITLE
[HELP] Using BPR how to get top 10 recommendations given a user_id and item_id?

### ISSUE THREAD

**Issue by karthikraja95** [benfred/implicit#333]
I built a recommender system using BPR. BPR has similar item function and recommend function. Similar Item function takes in item_id and recommends items similar to item_id; whereas recommend function takes in user_id and recommends items based on the history of the user_id. My question: is there a way to have a function takes in both user_id and item_id and gives recommendations based on the user_id history and items similar to item_id?

Example: Let say user_id: 1234 purchases an item_id 2345. How to give top 10 item recommendations considering the user_id 1234 bought item_id 2345?

Any idea how to implement this using implicit bpr model?

**Comment by chedatomasz** [comment]
I believe this is not currently supported as a direct option.
The purchase of item 2345 by user 1234 is reflected in the matrix that is factorized.
If you would like to give this item a higher significance, there is an indirect option:
Suppose you get a list of items recommended for user 1234 based on their history (eg. using BPR)
and a separate list of items similar to 2345 (using item-to-item kNN similarity or other methods). You can assign a score to each item based on it's position on each list, then add up the score and rank all items based on their combined score.
You could experiment with different functions, not only inverse of position.

**Comment by karthikraja95** [comment]
Thats a great idea.
