### ISSUE TITLE
Outdated docstring for AlternatingLeastSquares.fit

### ISSUE THREAD

**Issue by madcat1991** [benfred/implicit#334]
Hi @benfred ,

It seems that the documentation for `AlternatingLeastSquares.fit` is slightly outdated. In particular the part related to the `item_users` parameter:

`The negative items are implicitly defined: This code assumes that non-zero items in the item_users matrix means that the user liked the item. The negatives are left unset in this sparse matrix: the library will assume that means Piu = 0 and Ciu = 1 for all these items.`

According to the issue #119 and this [diff](https://github.com/benfred/implicit/pull/119/commits/19328a5067a5e57a2ac2b7eea9e7f26ebb2f1136) it is possible now to provide negative Ciu values to take into account explicit negative feedback. 

If so, then the documentation should be updated.

**Comment by benfred** [comment]
Thanks! updated the docstring here: https://github.com/benfred/implicit/commit/ee954967650ab00ff0c6a49cf6692872431e604e
