### ISSUE TITLE
Do we pass the original or weighted preferences matrixes to ranking_metrics_at_k?

### ISSUE THREAD

**Issue by medoidai** [benfred/implicit#337]
@benfred

I know that when using the ALS and doing model.fit() we actually pass the weighted preferences matrix and not the original preferences matrix.

eg:

```
original_train_matrix = csr_matrix(....) # implicit interactions
weighted_train_matrix = original_train_matrix * alpha
model.fit(weighted_train_matrix)
```

So, I want to ask which matrixes parameters do we use with the following function:

`evaluation.ranking_metrics_at_k()`

Specifically for the following parameters of the function:

**train_user_items:** original_train_matrix or weighted_train_matrix?
**test_user_items:** original_test_matrix or weighted_test_matrix?

**Comment by ita9naiwa** [comment]
it doesnt matters.
ranking_metrics_k only checks whether there's an value at mat[u, i]. if does, it deems it is positive.

**Comment by medoidai** [comment]
Thank you @ita9naiwa! Efstathios.
