### ISSUE TITLE
Its maybe not the most clear - but the 'Cui' matrix being passed in does double duty here. Explanation on this.

### ISSUE THREAD

**Issue by medoidai** [benfred/implicit#338]
Its maybe not the most clear - but the 'Cui' matrix being passed in does double duty here: It defines which users for each item that liked it (Pui in original paper) - as well as defines how much confidence we have that the user liked that item. 

The Pui values are implicit - the library is assuming that non-zero items in the Cui matrix means that the user liked the item (Pui = 1). The negatives are left unset in this sparse matrix: the library will assume that means Pui = 0 and Cui = 1 for all these items.  This lets us only do work on the sparse liked items by leveraging that ```YtCuY = YtY + Yt(Cu - I)Y```

_Originally posted by @benfred in https://github.com/benfred/implicit/issues/38#issuecomment-311209191_

--

So, as far as this is concerned we actually pass a sparse csr matrix.

The implicit zeros in the csr matrix refer to unknown user-item interactions and the library will handle them as Pui=0 and Cui=1.

However, the explicit user-item interactions in the csr_matrix will be handled by the library as Pui=1 and Cui=Wui where Wui the value in the csr_matrix.

The value Wui is calculated by weighting the implicit feedback Rui by any type of weighting (eg: Rui * alpha)

Rui can be just 1 for known user-item interaction or could be the number of times a user is interacted with the item.

Right? @benfred

**Comment by ita9naiwa** [comment]
As far as I know, 
Pui = either 0 or 1(user interacted or not)
Cui = 1 (user not interacted)
Cui = matrix[u, i] (in Implicit)

**Comment by ita9naiwa** [comment]
So, it seems you're correct

**Comment by medoidai** [comment]
Thanks!
