### ISSUE TITLE
0 user or item learned feature vectors, is it correct?

### ISSUE THREAD

**Issue by medoidai** [benfred/implicit#339]
@benfred

Hi, I have noticed that some item_factors or/and user_factors are filled with 0s, is this correct?

**Comment by ita9naiwa** [comment]
It's correct. users having no item interactions or items having no user interactions will have 0 vectors as their representaiton

**Comment by medoidai** [comment]
I understand.

However, the number of unique users and items derive from a pool of user-item interactions.

So, all items and users have at least 1 interaction.

So, what could be?

**Comment by medoidai** [comment]
Thanks, we have assured that 0 vectors exist when no interactions exist for the entity (eg: item, user).
