### ISSUE TITLE
Question: how can I use multiple implicit feedback? 

### ISSUE THREAD

**Issue by vuongtrannguyenkhoi** [benfred/implicit#34]
Thanks for wonderful lib,
I have a question: what if I have multiple user features like user rating, play time, play number of an item....,
How to compile these user features and apply it as an input ranking to run this algorithm?

**Comment by benfred** [comment]
You will need to combine these features into a single confidence value that a user likes an item. 

The total play time and number of plays for an item will be highly correlated together: I would probably just include one of these for simplicity, and then add in a high constant amount of confidence for users that have explicitly liked the item.
