### ISSUE TITLE
Initialize user/ item factors w/ pretrained embeddings

### ISSUE THREAD

**Issue by phiweger** [benfred/implicit#341]
Is this possible, ie can I just

```python
model = ...
model.user_factors = pretrained_user_factors
model.item_factors = pretrained_item_factors
```

?

My aim would be to add existing word2vec embeddings to the model.

Thanks a lot,
Kind regards,

Adrian

**Comment by medoidai** [comment]
Hi @phiweger,

Of course!

For example in AlternatingLeastSquares you can set the factors manually.

When model.fit() is called the user_factors and item_factors will not be initialized randomly.

Here the code with the logic: https://github.com/benfred/implicit/blob/master/implicit/als.py#L137

With all respect,

Efstathios

**Comment by benfred** [comment]
+1 to what @medoidai said: setting the factors before calling fit will use those instead of initializing randomly.
