### ISSUE TITLE
Does not install on Windows 10

### ISSUE THREAD

**Issue by rockbottom123** [benfred/implicit#346]
I am trying to install implicit on my windows 10 system with 

`pip install implicit`

It gives me following error

`Failed to build implicit
Installing collected packages: implicit
    Running setup.py install for implicit ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\51\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-sm8uplje\\implicit\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-sm8uplje\\implicit\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-record-03z1zu7x\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-sm8uplje\implicit\
    Complete output (23 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\implicit
    copying implicit\als.py -> build\lib.win-amd64-3.6\implicit
    copying implicit\approximate_als.py -> build\lib.win-amd64-3.6\implicit
    copying implicit\nearest_neighbours.py -> build\lib.win-amd64-3.6\implicit
    copying implicit\recommender_base.py -> build\lib.win-amd64-3.6\implicit
    copying implicit\utils.py -> build\lib.win-amd64-3.6\implicit
    copying implicit\__init__.py -> build\lib.win-amd64-3.6\implicit
    creating build\lib.win-amd64-3.6\implicit\cuda
    copying implicit\cuda\__init__.py -> build\lib.win-amd64-3.6\implicit\cuda
    running build_ext
    building 'implicit._als' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\implicit
    C:\Users\51\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -Ic:\users\51\anaconda3\include -Ic:\users\51\anaconda3\include -c implicit\_als.cpp -o build\temp.win-amd64-3.6\Release\implicit\_als.o /O2 /openmp
    gcc: error: /O2: No such file or directory
    gcc: error: /openmp: No such file or directory
    error: command 'C:\\Users\\51\\Anaconda3\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\51\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-sm8uplje\\implicit\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-sm8uplje\\implicit\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-record-03z1zu7x\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

Not sure how to fix this. Can you please look into this? Any help is truely appreciated.

**Comment by ita9naiwa** [comment]
you need to install openmp first.

**Comment by benfred** [comment]
It looks like the compiler you're trying to use is mingw - and the we're expecting vc++. 

Can you try install with anaconda ```conda install implicit``` ? We have precompiled windows binaries there that should work for you
