### ISSUE TITLE
Why AUC score in Implicit is so different than in LightFM?

### ISSUE THREAD

**Issue by sergiosalonso** [benfred/implicit#348]
Hello, first of all thanks for this amazing library!
I am trying to compare Implicit ALS and LightFM performance on the MovieLens 25M ratings (using 4 as min_rating to count as an interaction). 

When trying to compute the AUC metric in LightFM evaluation module, it scores 0.994 and in implicit using the AUC@5 metric 0.548. 

How does implicit calculates the AUC metric so that the results are so different than in LightFM?

I've tried using what you said on this issue [158](https://github.com/benfred/implicit/issues/158#issuecomment-434517410) and got a score of 0.529 at AUC@5.

I don't understand if that is supposed to be a good or bad performance. Why are the scores so low? Should I try to tune better the hyperparameters?

Thanks!

**Comment by ita9naiwa** [comment]
AUC@(the number of items) or AUC@infinite will be equal to AUC of lastfm.

**Comment by sergiosalonso** [comment]
Thanks for your answer.

Is there a way to get the AUC@infinite in Implicit, so I can compare both with the same metric?

**Comment by ita9naiwa** [comment]
set N to be the number of items

**Comment by sergiosalonso** [comment]
It works I achieved a 0.92. But it took around 4 hours to compute, in LightFM it takes just 20-30 mins.
