### ISSUE TITLE
Does someone know this error TypeError: cannot unpack non-iterable AlternatingLeastSquares object

### ISSUE THREAD

**Issue by AprilWang93** [benfred/implicit#350]
artist_factors, user_factors = alternating_least_squares(bm25_weight(plays), 50)
TypeError: cannot unpack non-iterable AlternatingLeastSquares object

**Comment by benfred** [comment]
Can you show the full code to reproduce?

it looks like you've created an 'alternating_least_squares' function that returns an 'AlternatingLeastSquares' object - but you're expecting the output from this function: https://github.com/benfred/implicit/blob/11833275369f06c537f8d0acf5fc4b46465a8be9/implicit/als.py#L307-L318

The object being returned there has an item_factors and user_factors attributes that are what you are looking for.
