### ISSUE TITLE
[HELP] Store training_loss in ALS

### ISSUE THREAD

**Issue by HardikLGupta** [benfred/implicit#351]
Currently while initialising `implicit.als.AlternatingLeastSquares` we can configure the parameter `calculate_training_loss` to calculate MSE per iteration. Is there a possibility to get the loss at every step as well? If we have the loss stored at every iteration, we can plot the results

**Comment by benfred** [comment]
Checkout this code : https://github.com/benfred/implicit/blob/11833275369f06c537f8d0acf5fc4b46465a8be9/benchmarks/benchmark_als.py#L28-L40

We're storing the loss at each iteration there to construct the loss plots per iteration in this post: https://www.benfrederickson.com/fast-implicit-matrix-factorization/
