### ISSUE TITLE
return of similar_items of ALS

### ISSUE THREAD

**Issue by ghk829** [benfred/implicit#353]
I clone the below project. 
https://towardsdatascience.com/recommending-github-repositories-with-google-bigquery-and-the-implicit-library-e6cce666c77
And I used ALS algorithms for building CF on my own.
``` python
[(repos[r], s) for r, s in model.similar_items(repo_ids['tensorflow/tensorflow'])]

[('tensorflow/tensorflow', 0.11004664927613485),
 ('BVLC/caffe', 0.05464596517484711),
 ('jikexueyuanwiki/tensorflow-zh', 0.0480636510575572),
 ('electron/electron', 0.03691138356963415),
 ('thejameskyle/react-loadable', 0.03448170095705296),
 ('scikit-learn/scikit-learn', 0.03383273535686292),
 ('airbnb/javascript', 0.03374395057949833),
 ('robbyrussell/oh-my-zsh', 0.03291399938623609),
 ('amark/gun', 0.03284888415799501),
 ('ResolveWang/WeiboSpider', 0.03269446296026965)]

```

I follow the guide exactly same but I got different result and I wonder what's the meaning of the result!
I guess the first item recommended by model is the same one which is equal to input.
But, the score is different the blog and **the result is not 1. _0.11 in the example_ !!**

I guess the result of the first should be 1 because the predicted item is equal to input !
Please reply the issue and correct my idea!!

**Comment by ita9naiwa** [comment]
I think this is an issue.
and I found that

```python
    def _get_similarity_score(self, factor, factors, norms, N):
        scores = factors.dot(factor) / norms
        best = np.argpartition(scores, -N)[-N:]
        return sorted(zip(best, scores[best]), key=lambda x: -x[1])
```

does not divide the norm of the given item factor itself.

```python
    def _get_similarity_score(self, factor, factors, norms, N):
        norm = np.sqrt(np.dot(factor, factor))
        scores = factors.dot(factor) / (norms * norm)
        best = np.argpartition(scores, -N)[-N:]
        return sorted(zip(best, scores[best]), key=lambda x: -x[1])
```
this might work. I'll make PR on this soon.
