### ISSUE TITLE
How to cite implicit

### ISSUE THREAD

**Issue by ljmartin** [benfred/implicit#356]
`implicit` has been very useful for me in academic research - is there a preferred reference for me to cite in articles?
Thanks!

**Comment by benfred** [comment]
Thanks for citing!  I'm glad this project has come in useful

I honestly don't have a preference on how you cite - whatever works best for you is good (I'm not an academic =). I've seen some references like  "Ben Frederickson. 2017. Fast python collaborative ltering for implicit datasets. https://github.com/benfred/implict" in some articles (https://arxiv.org/pdf/1807.06786.pdf) if that helps.

**Comment by ljmartin** [comment]
Thanks. If you wish, some software packages get a DOI using zenodo for citation credit, but citing the github link directly works too!
