### ISSUE TITLE
Microsoft Visual C++ 14.0 is required

### ISSUE THREAD

**Issue by mathijs20** [benfred/implicit#357]
i need to install pyaudio using pip but i cant quite catch how it works.
i tried to just type in cmd: pip install PyAudio which lead in the following errors:

error 1: Command errored out with exit status 1
error 2: mincrosoft visual C++ is required. Get it from https://visualstudio.microsoft.com/downloads/
error 3: Failed building wheel for pyaudio

i tried solving error 2 by just downloading visual studio from the link given, so ive downloaded the newest version but it still doesnt work.

i tried solving error 3 as well by going to an page in which was said that i needed to use a different PyAudio file. Ive tried downloading all of the different PyAudio files available but none of those worked as well.

I believe im doing something wrong regarding to the Visual studio thing but i cant seem to catch what im doing wrong.

Can anyone help me solving this problem?
thanks in regards

**Comment by benfred** [comment]
This isn't related to this project - try posting there https://github.com/jleb/pyaudio
