### ISSUE TITLE
getting dtype mismatch exception in NN models when matrix size is large

### ISSUE THREAD

**Issue by mohammad1234** [benfred/implicit#360]
hi,
 i've encountered this issue in nearest_neighbourhood based models (i.e. Cosine, TFIDF and BM25 ) where I get this following exception when my matrix size is very big (in my case 20Mx8M ):
```
  File "/home/ubuntu/.local/lib/python3.6/site-packages/implicit/nearest_neighbours.py", line 147, in fit
    ItemItemRecommender.fit(self, weighted, show_progress)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/implicit/nearest_neighbours.py", line 36, in fit
    self.scorer = NearestNeighboursScorer(self.similarity)
  File "implicit/_nearest_neighbours.pyx", line 42, in implicit._nearest_neighbours.NearestNeighboursScorer.__cinit__
ValueError: Buffer dtype mismatch, expected 'int' but got ‘long'
```
when matrix size is small, It works fine ... is there any way to make this working for a large size of matrix ?

**Comment by benfred** [comment]
What's K set to? (Like how many neighbours are you generating)? 

I'm guessing the similarity matrix that gets trained has more than 2B items, and is causing issues with the SimilarityScorer:
https://github.com/benfred/implicit/blob/4dba6dd90c4a470cb25ede34a930c56558ef10b2/implicit/_nearest_neighbours.pyx#L34-L35

You can probably fix in the short term by dropping K down to like 50 which should work. I'll get a proper fix in longer term

**Comment by mohammad1234** [comment]
Okay, i will try 50 and see if it works ... thanks
