### ISSUE TITLE
filter_already_liked_items Working for ALS?

### ISSUE THREAD

**Issue by allard-jeff** [benfred/implicit#365]
I am not finding that there is any impact to the recommendations if I set filter_already_liked_items  True or False. It is version '0.4.2'
Its hard to create a reproducible example of this type but I can try if needed. Checking to see if this is a known issue? I am finding this using the recommend function:

model.recommend(cust_indx,cust_item_mat,N=10,filter_already_liked_items=True)

The cust_item_mat is the same as used for training the model except that I am transposing as it seems like .fit() request item_user and this function requires user_item. So I take the .fit() one and transpose: item_user_mat.transpose()

**Comment by ita9naiwa** [comment]
No, we didn't see this issue before. Could you reproduce this error again? 

I think this is caused for ItemItemRecommender, but I'm not sure.

**Comment by amargondaliya** [comment]
Hi @ita9naiwa 

I was also facing same challenge. I inspected code and found that in recommend function users liked items need to be corrected. It's not extracting user's liked item indices correctly. It's always returning array of 0s instead of indices of liked items

Current:
```
if filter_already_liked_items:
    liked.update(user_items[userid].indices)
```

Correction:
```
if filter_already_liked_items:
    liked.update(user_items[userid].nonzero()[1])
```

After this correction it is working fine now. Hope I am interpreting it in right way

**Comment by drsaunders** [comment]
This bug is causing problems for me too. @amargondaliya, would you please submit this as a pull request?

**Comment by amargondaliya** [comment]
@drsaunders I just submitted pull request

**Comment by ita9naiwa** [comment]
I think it works correctly if `user_items` is CSR Matrix. does it go wrong when it is a CSC matrix?

**Comment by julioasotodv** [comment]
Indeed, it looks like it works when `user_items` is CSR as the docs imply it should be...

**Comment by benfred** [comment]
user_items needs to be a CSR matrix for correct results. Going ```(user_items[userid].nonzero()[1]```  will have some performance implications so I'd rather leave as is.

I've added a check that will throw an error if you don't pass a CSR matrix in #504
