### ISSUE TITLE
Error Installing django-misaka, error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

### ISSUE THREAD

**Issue by Aryan-Mishra-Python** [benfred/implicit#368]
Hello Everybody,

I also got a error while, I was trying to install **` pip install django-misaka`** for one of my projects
But I got 2 Errors One Of them I Fixed It On My Own The Error Was Like This- 'error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://visualstudio.com/visual-cpp-build-tools"'

I Got The Build Tools For Microsoft C++ 14.0 Rebooted My Computer, But Unexpectedly I Got Another Error That Says- **error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2**

I Tried To Fix It, But I Could not find a fix for this,

MY ERROR:

![error](https://user-images.githubusercontent.com/64458999/87508199-75a9ba00-c68c-11ea-8ef6-3da721f365cc.png)

# PLEASE HELP WITH THIS!

**Comment by benfred** [comment]
This is unrelated to this project - try posting to [django-misaka](https://github.com/chiehtu/django-misaka) instead
