### ISSUE TITLE
ALS - model.user factors and model.item factors wrong dimensions

### ISSUE THREAD

**Issue by qinghua-liu-coopx** [benfred/implicit#370]
After my alternating least square model with 20 latent factors (named model) is trained, I was retrieving the item - and user- factors (using model.user_factors, model.item_factors). In my rating matrix, I have m users and n items; however, the user_factors' dimension are n * 20 (instead of m * 20); while item_factors' dimensions are m * 20 ( instead of n * 20).

**Comment by ita9naiwa** [comment]
als model in this library requires item-user matrix. Have you tried to feed M.T instead?

**Comment by qinghua-liu-coopx** [comment]
> als model in this library requires item-user matrix. Have you tried to feed M.T instead?

Ohhh I see :) So the rating matrix is supposed to be of the dimensions of (num_items * num_users), i.e. each row is an item and each column is a user,  is that right?

**Comment by ita9naiwa** [comment]
Yes
