### ISSUE TITLE
issues while installing pyaudio

### ISSUE THREAD

**Issue by Saishankar2001** [benfred/implicit#371]
when i type command :
pip install pyaudio

i have tried several times and installed VS Build tools,but no use....

it shows the error like-

(c) 2019 Microsoft Corporation. All rights reserved.

(venv) C:\Users\Administrator\untitled2>pip install pyaudio
Collecting pyaudio
  Using cached PyAudio-0.2.11.tar.gz (37 kB)
Using legacy setup.py install for pyaudio, since package 'wheel' is not installed.
Installing collected packages: pyaudio
    Running setup.py install for pyaudio ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\administrator\untitled2\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\
Local\\Temp\\pip-install-ikm8s3da\\pyaudio\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-ikm8s3da\\pyaudio\\setup.py'"'"';f=
getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' inst
all --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-ds3k0l5c\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\user
s\administrator\untitled2\venv\include\site\python3.7\pyaudio'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-ikm8s3da\pyaudio\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying src\pyaudio.py -> build\lib.win-amd64-3.7
    running build_ext
    building '_portaudio' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\administrator\untitled2\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"
'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-ikm8s3da\\pyaudio\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-ik
m8s3da\\pyaudio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code,
 __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-ds3k0l5c\install-record.txt' --single-version-externally-managed --c
ompile --install-headers 'c:\users\administrator\untitled2\venv\include\site\python3.7\pyaudio' Check the logs for full command output.

**Comment by benfred** [comment]
Maybe check these steps: https://stackoverflow.com/questions/52283840/i-cant-install-pyaudio-on-windows-how-to-solve-error-microsoft-visual-c-14

**Comment by Divesh143** [comment]
Collecting PyAudio
  Using cached PyAudio-0.2.11.tar.gz (37 kB)
Using legacy 'setup.py install' for PyAudio, since package 'wheel' is not installed.
Installing collected packages: PyAudio
    Running setup.py install for PyAudio: started
    Running setup.py install for PyAudio: finished with status 'error'
 Check the logs for full command output.

Help

**Comment by sachin-kumar-koli** [comment]
**First step** - _pkg install portaudio_ 
After install
**Second step** - _pip install pyaudio_

**Comment by H-Honarjoo** [comment]
install pyaudio from https://www.lfd.uci.edu/~gohlke/pythonlibs/
pip install \directory\of\wheel\pyaudio.whl

@Saishankar2001

**Comment by Saishankar2001** [comment]
@sachin-kumar-koli Thank you

**Comment by Saishankar2001** [comment]
@H-Honarjoo okay

**Comment by VeduChess** [comment]
> **First step** - _pkg install portaudio_
> After install
> **Second step** - _pip install pyaudio_

pkg  not correct

**Comment by lucdetellis** [comment]
On macOS / OS X:
`brew install portaudio`
then
`pip install pyaudio`

**Comment by denokenya** [comment]
pip install pipwin
pipwin install pyaudio

pipwin is like pip, but it installs precompiled Windows binaries provided by Christoph Gohlke. Saves you a lot of googling and manual downloading.

**Comment by Saisantosh2004** [comment]
> On macOS / OS X: `brew install portaudio` then `pip install pyaudio`

Thank you it worked

**Comment by saifujasoor** [comment]
For Ubuntu 18.04, Python 3.7.2, pyaudio 0.2.11   try 
```
$ sudo apt-get install portaudio19-dev python-pyaudio python3-pyaudio
```
  
For Ubuntu 20.04    try 
```
$ sudo apt install portaudio19-dev python3-pyaudio

```

This Should help. Thank you.

**Comment by falgun23** [comment]
> For Ubuntu 18.04, Python 3.7.2, pyaudio 0.2.11 try
> 
> ```
> $ sudo apt-get install portaudio19-dev python-pyaudio python3-pyaudio
> ```
> 
> For Ubuntu 20.04 try
> 
> ```
> $ sudo apt install portaudio19-dev python3-pyaudio
> ```
> 
> This Should help. Thank you.

This was very helpful, thank you @saifujasoor

**Comment by YSyashsharma** [comment]
> On macOS / OS X: `brew install portaudio` then `pip install pyaudio`

"zsh: command not found: brew" is showing

**Comment by UTFeight** [comment]
> > On macOS / OS X: `brew install portaudio` then `pip install pyaudio`
> 
> "zsh: command not found: brew" is showing

you need to find out the "package manager" you use for your system.

If you are not using homebrew (`brew` command) package manager you may be:

- Not using MacOS:    figure out the package manager you use (e.g apt, pacman, dnf, yum etc.)
- Not using HomeBrew: Just do the above_.-^^^^^^
