### ISSUE TITLE
transform interface

### ISSUE THREAD

**Issue by inkrement** [benfred/implicit#373]
Hi, have you planned a transform interface? Would be great if one can infer the item matrix (given latent factors/user matrix) or vice versa. I am not sure how to handle the item-bias terms, but I guess they are also optimized (or assumed to be zero?!).

**Comment by benfred** [comment]
There is a bit of discussion about this happening here https://github.com/benfred/implicit/issues/467 - but in the last commit there we've added support for calculating the item matrix given a fixed user matrix (and vice versa).

As an example given a user_items sparse matrix containing interactions, and a existing_item_factors dense matrix containing precalculated item factors:

```python
# Train an ALS model with pre-existing item factors, but calculating user factors
model = AlternatingLeastSquares()
model.item_factors = existing_item_factors
userids = np.arange(user_items.shape[0])
model.partial_fit_users(userids, user_items)
```
