### ISSUE TITLE
Silent NaN's in AlternatingLeastSquares when the number of factors is larger than the number of items/users

### ISSUE THREAD

**Issue by Focus** [benfred/implicit#377]
Alternating least squares silently produces NaN's for the factors whenever the number of factors > n_items/n_users. Minimal example:

```python
import implicit
from scipy.sparse import coo_matrix
import numpy as np

item_user_matrix = coo_matrix((np.ones(10), (np.arange(10), np.arange(10))))
item_user_matrix.todense()
als = implicit.als.AlternatingLeastSquares(factors=15)
als.fit(item_user_matrix)
als.item_factors # All NaN's
als.recommend(0, item_user_matrix.tocsr().T, 10) # Happy to produce non-sensible recommendations
```

Tested on 0.4.2

**Comment by srinivascnu166** [comment]
Hi, I'm getting this error while testing the implicit in Docker.

**Exception during training: NaN encountered in factors
Traceback (most recent call last):
  File "/opt/program/train", line 228, in train
    model.fit(sparse_item_user * alpha_val)
  File "/usr/local/lib/python3.7/dist-packages/implicit/als.py", line 189, in fit
    self._check_fit_errors()
  File "implicit/recommender_base.pyx", line 381, in implicit.recommender_base.MatrixFactorizationBase._check_fit_errors
implicit.recommender_base.ModelFitError: NaN encountered in factors**

Implicit Version: **0.4.4**

The same code worked with the previous version(**0.4.2**)
How can I avoid this error??

**Comment by benfred** [comment]
@Focus  I've added your example as a unittest in #512 - but I'm not getting any NaN's when I run this myself (on my local development machine, or on the github actions runners testing out on osx/windows/linux).

Does this problem still happen for you, or can we close this issue?

**Comment by Focus** [comment]
> @Focus I've added your example as a unittest in #512 - but I'm not getting any NaN's when I run this myself (on my local development machine, or on the github actions runners testing out on osx/windows/linux).
> 
> Does this problem still happen for you, or can we close this issue?

@benfred Just tested this on 0.4.8 and happy to say I am no longer getting NaN's. I am happy to close the issue :)

**Comment by milanABI** [comment]
@benfred @Focus Currently i am using 0.6.2 version and I am getting an error while implementing grid search. 
`clf = GridSearchCV(als_pipeline, parameters,cv = 2, verbose=True, error_score='raise')
clf.fit(data_als,data_als)`
below is the screenshot attached for the same.
<img width="871" alt="Screenshot 2023-03-30 at 11 50 36 AM" src="https://user-images.githubusercontent.com/115446899/228747397-9fd0ac87-62d9-4b6a-a3a5-78457f4f7005.png">
