### ISSUE TITLE
model fit stuck on more than 2^31 elements in rating matrix

### ISSUE THREAD

**Issue by nishanthrao24** [benfred/implicit#380]
This was unresolved in this issue - https://github.com/benfred/implicit/issues/86#issuecomment-386305569

@benfred The snippet of code you referenced in the previous issue might be incorrect (https://github.com/benfred/implicit/issues/86#issuecomment-373093742). The number of elements of the COO matrix which is specified to be of size 2.2 billion might be getting reduced to lesser than 2^31 after converting to a CSR matrix because you are using numpy random and indices may be duplicated (see this - https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.tocsr.html#scipy.sparse.coo_matrix.tocsr)

I tried it on a slightly larger matrix of 2.5 billion and the model fit is stuck.

Can you please look into this?

**Comment by nishanthrao24** [comment]
Update - The issue only exists for ALS. I tested BPR and it worked fine for me.

This is the code snippet I used to test following this (https://github.com/benfred/implicit/issues/86#issuecomment-373093742)

```
import numpy
import scipy.sparse

import implicit.als

import logging
logging.basicConfig(level=logging.DEBUG)

# create a large sparse matrix
count = 2500000000
colids = numpy.random.randint(5000, size=count, dtype=numpy.int32)
rowids = numpy.random.randint(80000000, size=count, dtype=numpy.int32)
vals = numpy.ones(count, dtype=numpy.float32)
m = scipy.sparse.coo_matrix((vals, (colids, rowids)), shape=(5000, 80000000))

# create model using 
model = implicit.als.AlternatingLeastSquares()
model.fit(m)
```

**Comment by benfred** [comment]
Thanks for the bug report!  The previous fix just made BPR work unfortunately, and there were similar problems with the ALS model.

This PR should fix: https://github.com/benfred/implicit/pull/400
