### ISSUE TITLE
How to compute rank_items for all my users? 

### ISSUE THREAD

**Issue by ManuelRios18** [benfred/implicit#384]
Hello, 

I would like to know the best way to rank a handful of items for **all** my  users, I currently have a huge number of users (around 5 million different users) and I need find the fastest way to rank 200 items to all of them. 

Which is the best way to do this ? 
calling the method rank_items() for each user sounds like a bad idea, I guess that there is a better factorized way to do this.

Can someone give me an advice ? 

Thanks in advance.

**Comment by mohjeih** [comment]
Hello,

One solution could be implementing your own `rank_item_all` method with a custom C++ function filling numpy arrays in parallel, similar to `recommend_all` method.

**Comment by ManuelRios18** [comment]
> Hello,
> 
> One solution could be implementing your own `rank_item_all` method with a custom C++ function filling numpy arrays in parallel, similar to `recommend_all` method.

@mohjeih 
Where can I get the recommend_all method written in C++ ? And where is the current "rank_items" method implemented ?
In order to have a guideline

**Comment by mohjeih** [comment]
@ManuelRios18 Sorry for the confusion. `recommend_all` and `rank_items` are implemented in `recommender_base.pyx` (Cythonized module). Please see [here](https://github.com/benfred/implicit/blob/master/implicit/recommender_base.pyx) .`recommend_all` sorts array of scores in parallel using a C++ sorting function, `fargsort_c`, which is implemented in `topnc.cpp`. The wrapper to this sorting function is defined at the beginning of `recommender_base.pyx`.

**Comment by marinkreso95** [comment]
Hi
I have the same problem as @ManuelRios18 (if you found a solution for this, please share)
Here is a code snippet from my project. Does somebody have another way to do this properly? Because this solution is taking a lot of time
```
row = y.recipe_id_comb.astype(item_c).cat.codes
    col = y.user_id.astype(user_c).cat.codes
    
    item_user_matrix = csr_matrix((y["rating"], (row, col)), shape=(item_c.categories.size, user_c.categories.size))
    user_item_matrix = csr_matrix((y["rating"], (col, row)), shape=(user_c.categories.size, item_c.categories.size))
    
    # Train MF model
    mf_model = implicit.als.AlternatingLeastSquares(factors=opt_fac, regularization=opt_reg, iterations=opt_itr)
    mf_model.fit(item_user_matrix)

    # Extract outputs from MF model
    score_mf = row.copy()
    for ind_i in np.unique(col):
        mf_y = mf_model.rank_items(ind_i, user_item_matrix, row[col == ind_i].astype(int))
        score_mf[col == ind_i] = score_mf[col == ind_i].replace(dict(mf_y))
    score_mf = score_mf.to_numpy().reshape((len(score_mf), 1))
```

**Comment by ManuelRios18** [comment]
Hello, Sadly I couldn't find an efficient solution, what I ended up doing was simply multiply user and item embeddings, load those results into my company's Landing Zone, and then I ranked the items using basic SQL queries.

Happy coding!

@marinkreso95

**Comment by benfred** [comment]
@ManuelRios18 the latest main branch has support for this (though does have some breaking API changes ). see #481

```python

model = implicit.als.AlternatingLeastSquares()
model.fit(user_items)

# rank the first 200 items in the model for all the users
userids = np.arange(model.user_factors.shape[0])
items = np.arange(200)
ids, scores = model.recommend(userids, items=items)
```
