### ISSUE TITLE
How true negative feedback is treated in ALS

### ISSUE THREAD

**Issue by yuxinchenNU** [benfred/implicit#385]
Thanks for the amazing package. I would like to confirm how true negative feedback is treated in ALS implementation. 

In the documentation of implicit, it says
"Negative items can also be passed with a higher confidence value by passing a negative value, indicating that the user disliked the item."
Does this mean that if our rating matrix looks like
[2, -3, 3, 0, 0;
1, -2, 0, 0, 4], where negative values indicate how much users dislike the items and 0s are missing ratings, 
then the confidence value for those *true negative feedback* will be larger than 1 and proportional to their magnitudes? 

It seems the case in the following code in the function user_linear_equation, but would like to confirm. Thanks!
"
for i, confidence in nonzeros(Cui, u):
        factor = Y[i]

        if confidence > 0:
            b += confidence * factor
        else:
            confidence *= -1
"

**Comment by benfred** [comment]
Thats right - all missing items are assumed to be negative preference with 1 confidence (Pui = 0, Cui = 1) . Confidence elements less than zero are assumed to be negative preference as well (Pui = 0, Cui *= -1), whereas positive confidence values are positive items (Pui = 1).
