### ISSUE TITLE
segmentation fault: BLAS : Program is Terminated. Because you tried to allocate too many memory regions.

### ISSUE THREAD

**Issue by samtriolo** [benfred/implicit#387]
### Summary:
On an Ubuntu 18.04.4 LTS VM with 96 cores, implicit fails silently.  An strace reveals "+++ killed by SIGSEGV (core dumped) +++".  Running python inside an interactive shell reveals the following error: "BLAS : Program is Terminated. Because you tried to allocate too many memory regions.  Segmentation fault (core dumped)".  This was run with the recommended setting of `os.environ['OPENBLAS_NUM_THREADS'] = '1'`.

### Details
- this problem does not occur on vm instances with 32 or 64 cores; I did not test other configurations
- recommend executing within an interactive python shell or you will not see error output

<details><summary>Example / code to reproduce</summary>
<p>

```
Python 3.8.2 (default, Jul 20 2020, 23:28:08)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> from scipy import sparse
>>> import pandas as pd
>>> import implicit
>>> os.environ['OPENBLAS_NUM_THREADS'] = '1'
>>> counts = pd.read_csv(f'counts.csv')
>>> counts = counts.assign(user_id=counts.user_id.astype("category").cat.codes, content_id=counts.content_id.astype("category").cat.codes)
>>> sparse_content_person = sparse.csr_matrix((counts['count'].astype(float), (counts['content_id'], counts['user_id'])))
>>> data = (sparse_content_person * 30).astype('double')
>>> model = implicit.als.AlternatingLeastSquares()
>>> model.fit(data, show_progress=True)
  0%|                                              | 0/15 [00:00<?, ?it/s]
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
Segmentation fault (core dumped)
```

</p>
</details>

**Comment by ManuelRios18** [comment]
I have the exact same problem !!! how do we fix it ??

**Comment by benfred** [comment]
interesting - how big is your dataset? 

Can you get a stack trace me a stack trace when this occurs? Running your program GDB and wait for the segfault and then get the native trace.

Getting the python stack trace during the segfault would also be helpful. One easy way do to this is with [py-spy](https://github.com/benfred-py-spy). When you hit the segfault with GDB, you can run ```py-spy dump -p PROGRAM_PID --nonblocking``` to get the python stack.

Does this only happen using OpenBLAS ? If you swap out for MKL (say by using anaconda)  does this still happen?

@ManuelRios18 Whats the system you're running on? Is it also a 96 core machine?

@samtriolo What kind of cpu's are you running? Is this machine something I can access on a AWS/GCP ?

**Comment by samtriolo** [comment]
hey @benfred, I've been working around this issue by using alternate cpu counts in the interest of hitting various deadlines I'm under, so unfortunately I haven't had time to perform any of the recommended debugging steps you've requested.  Also, atm I can't provide you access to the environment where it's running.  

I'll leave it up to you to decide if the issue should be closed in the mean-time, in light of the fact that I'm not providing the info you need to troubleshoot further.

**Comment by benfred** [comment]
Hmm - I've tried on much larger datasets just now with both OpenBlas and MKL and didn't hit this problem on an 80 core machine (DGX1-V100).

I think this is probably a problem with OpenBlas - like you mentioned the solution is probably either to limit the number of active threads down to 64 (```num_threads=64``` to the model constructor) or to install the Intel MKL blas library. 

I'm going to close this for now since I don't think there is much I can do here
