### ISSUE TITLE
Failed to create Docker image as Implicit is not getting installed in python:3.8-slim-buster

### ISSUE THREAD

**Issue by shawrk3387** [benfred/implicit#388]
I have created a model and now trying to run it in Docker container. I am experiencing an issue with Implicit while trying to create the Docker image.
[error_log.txt](https://github.com/benfred/implicit/files/5065969/error_log.txt)

**Comment by shawrk3387** [comment]
@benfred kindly assist in solving this issue

**Comment by benfred** [comment]
@shawrk3387 you'll either need to install gcc in your docker container, or install a binary version of implicit through conda-forge instead of using pip (like ```conda install -c conda-forge implicit```)
