### ISSUE TITLE
[question] implicit recommendations + time decaying confidence

### ISSUE THREAD

**Issue by mdeland** [benfred/implicit#39]
I don't see much about this situation in the literature - but suppose we hypothesize that our confidence in user's implicit feedback should decrease as time passes (ie we are more confident that they're interested in an item they recently interacted with than one they interacted with days/weeks ago).  Any advice/thoughts on how to approach this?  Am currently applying a time decay function directly to the R_ui matrix, but if you have more experience with this setting I'd be happy to hear about it.

**Comment by benfred** [comment]
I think your approach might be the best option for using this library - there isn't a way to add in temporal features directly with this code.

There are a couple papers I've read on this : [Collaborative Filtering with Temporal Dynamics](https://pdfs.semanticscholar.org/8451/c2812a1476d3e13f2a509139322cc0adb1a2.pdf) and  [Towards Time-Dependant Recommendation based on Implicit Feedback](http://ids.csom.umn.edu/faculty/gedas/cars2009/BaltrunasAmatriain-cars2009.pdf) but I haven't tried out either approach.

**Comment by mdeland** [comment]
Thanks for the references - I've seen both of those papers, they seem to address slightly different setups.  I've had some success time decaying the confidence values, I'll continue to think about how these methods might be integrated into the implicit recommendation situation.
