### ISSUE TITLE
Cuda 11.0 setup incompatible 

### ISSUE THREAD

**Issue by tRosenflanz** [benfred/implicit#390]
Cuda 11.0 doesn't support `compute_30` option for compilation and throws error during pip install. 
Just removing 'compute_30' option from post_args fixes it:
https://github.com/benfred/implicit/blob/4dba6dd90c4a470cb25ede34a930c56558ef10b2/cuda_setup.py#L56

**Comment by ita9naiwa** [comment]
Does removing `compute_30` any other possible problems...?

**Comment by tRosenflanz** [comment]
Maybe incompatibility with much older GPUs. Works fine on P100

**Comment by benfred** [comment]
I think targeting a minimum of compute_60 (pascal and newer GPU's) is acceptable - We should also add options for v100/a100 chips in this list (compute_70/compute_80).

**Comment by benfred** [comment]
I've targeted compute_50 and newer here: https://github.com/benfred/implicit/pull/398 - this should work with cuda 11 now. Thanks for bringing this up!

**Comment by benfred** [comment]
This change is in the 0.4.4 release.

Fwiw - there are also prebuilt GPU packages on conda-forge now which can be installed with ```conda install -c conda-forge implicit implicit-proc=*=gpu```.  Unfortunately this doesn't support cuda11 yet - cuda 11 doesn't seem to be supported by condaforge, so there are only prebuilt packages going up to cuda10.2 there. You can still install from source using ```pip install implicit``` to get a Cuda11 package .
