### ISSUE TITLE
Support storing factors as FP16 on the GPU

### ISSUE THREAD

**Issue by benfred** [benfred/implicit#392]
One problem with training on the GPU is fitting the item/user embeddings into GPU memory.   If we could store factors in reduced precision formats like FP16 we could reduce the amount of memory needed for these factors.

**Comment by tangzhy** [comment]
what are all the data types that support gpu training? say fp16, int8, int16? 

I'm running into this trouble where #users=49108406, #items=55341998, #interactions=144997955.

I'll try fp16 first.

**Comment by benfred** [comment]
done w/ #661
