### ISSUE TITLE
New Release Of Implicit On Pypi

### ISSUE THREAD

**Issue by D-H** [benfred/implicit#395]
The [latest release](https://pypi.org/project/implicit/#history) of the implicit package on pypi was in October 2019. 

Would it be possible to create a new release on pypi?

**Comment by benfred** [comment]
There is a new version of implicit up on PyPi and conda-forge (0.4.4). 

The PyPi version is still source only (so involves compiling extensions from scratch when building). The conda-forge version has 
prebuilt binaries - and new in this release there are now pre-built GPU packages available on conda-forge.
