### ISSUE TITLE
How to optimise model parameters?

### ISSUE THREAD

**Issue by nicolaneo** [benfred/implicit#403]
Hi! I'm just starting out so this may be a basic question:
I'm using the lastfm dataset to get artist recommendations, with the lastfm.py example. I've removed 20% of each user's top-rated artists from the lastfm360k dataset (set their plays to zero in the plays matrix), and testing to see if they get recommended.
I'm assuming I need to optimise the model parameters, since I'm going to train the model on the modified dataset. But I don't know how to optimise these parameters: number of factors, iterations and regularization. Would someone be able to explain how to do this? Also, do I need to also change the b25 weighting parameters, K1 and B, if I'm using ALS?
Thanks!

**Comment by ita9naiwa** [comment]
It's just like other machine learning models do.

One of easist approaches is grid-search. Please refer to 
https://scikit-learn.org/stable/modules/grid_search.html

**Comment by kmcmearty** [comment]
@nicolaneo 

If you want to implement GridSearch like @ita9naiwa mentioned, you should probably take a look at this link:
https://gist.github.com/jbochi/2e8ddcc5939e70e5368326aa034a144e

**Comment by markdouthwaite** [comment]
@nicolaneo - You might find [Scikit-Optimize](https://github.com/scikit-optimize/scikit-optimize) useful too, in particular I've had some success with [BayesSearchCV](https://scikit-optimize.github.io/stable/auto_examples/sklearn-gridsearchcv-replacement.html) in the past (depending on problem-size).

**Comment by kmcmearty** [comment]
@markdouthwaite - thanks for the BayesSearchCV tip. Looks like the Bayes search is as easy as swapping out GridSearch. When you say problem size, what kind of dimensions are we talking? My dataset consists of 1-2m~ transactions per quarter ranging across a few thousand customers and unique items.

**Comment by markdouthwaite** [comment]
@kmcmearty - I've run BayesSearchCV with at least an order of magnitude more data on a moderately sized machine with no issues. Needed a bit of patience though!
