### ISSUE TITLE
how to specify cuda version?

### ISSUE THREAD

**Issue by tangzhy** [benfred/implicit#404]
I'm trying to install the package through conda, conda directly choose cuda10.2 to install. How to specify it to be cuda10.1?

**Comment by benfred** [comment]
You can specify the cuda version by setting the cudatoolkit version when installing: ```conda install -c conda-forge implicit implicit-proc=*=gpu cudatoolkit=10.1``` .

I will update the readme to note this

**Comment by tangzhy** [comment]
Thanks!
