### ISSUE TITLE
Sparse Matrix Broken using Confidence

### ISSUE THREAD

**Issue by tangzhy** [benfred/implicit#405]
I'm confused that the post below talks about how to bring in confidence matrix, but this operation could turn sparse matrix into dense?

As I've tried in movielens example:
```python
log_matrix = 1.0 + log(1.0 + ratings/epsilon)
```
It raised issue: NotImplementedError: adding a nonzero scalar to a sparse matrix is not supported

Maybe I missed something. How we are gonna properly set confidence matrix for models to fit?

Original Post
```
Sorry for the late response.

c_ui comes from the value of the matrix.

c_ui = 1 # for negative items
c_ui =  matrix[u, i]; for positive items

you may set log(1 + r_ui/epsilon) using like


epsilon = some real value
matrix = some csr_matrix
log_matrix = 1.0 + log(1.0 + matrix/epsilon)
model.fit(log_matrix)

```
_Originally posted by @ita9naiwa in https://github.com/benfred/implicit/issues/329#issuecomment-602000601_

**Comment by ita9naiwa** [comment]
For scipy CSR or COO matrix, 

```python
m = some csr_matrix, or coo_matrix
m.data = np.log(1 + m.data)
```

it will work as I stated.

**Comment by tangzhy** [comment]
thanks.
