### ISSUE TITLE
Add the ability to support other train/test split policies.

### ISSUE THREAD

**Issue by markdouthwaite** [benfred/implicit#419]
Hi there 👋 

Thanks for the creating & maintaining this great package!

## Desired feature

The current `evaluation` module implements a 'traditional' fully randomized train/test split policy (`implicit.evaluation.train_test_split`). It'd be useful to have the option of using other splitting policies too, in particular a leave-one-out policy would be ideal.

## Other notes

I've implemented a version of this for consideration, and will raise a PR shortly.

**Comment by markdouthwaite** [comment]
Raised PR #420.

**Comment by benfred** [comment]
done in #420
