### ISSUE TITLE
cuda error: OOM

### ISSUE THREAD

**Issue by tangzhy** [benfred/implicit#424]
I'm training an ALS model on matrix:
 - shape: (69127779, 59373715)
 - nnz: 477111383
 - dtype: np.uint8
 - no overflow occurs.

I'm using a tesla V100-16GB gpu.

My als model is configured such that:
 - factors: 32
 - factor dtype: np.float16

Therefore, I guess the gpu memory to store the user&item factors = (69127779 + 59373715) * 32 * 2 bytes = 7.6GB.

But still I get:
```
RuntimeError: Cuda Error: out of memory (implicit/cuda/matrix.cu:29)
```

What else would use the gpu memory? Any advice?

**Comment by ita9naiwa** [comment]
as far as i Know, float32 is used in GPU computations, thus it will take twice memory for storing user and item factors, leading OOM Error

**Comment by benfred** [comment]
We only support fp32 on the GPU - and require both the item factors and the sparse matrix input to fit on gpu memory.  You'll probably need to run on at least an A100 40GB to make this work right now.
