### ISSUE TITLE
Out of Bounds Index Error when using Evaluation functions

### ISSUE THREAD

**Issue by murphystout** [benfred/implicit#425]
Hi All,
First off, thanks so much for all the work in this great library.  I've learned so much and its truly a remarkable feat.

Now my issue:

I'm able to successfully train a model and interface with it using the RecommenderBase functions.  However when I doubled back to do some evaluation of the model performance I immediate ran into an annoying index error.  

Here is a reproducible example (from here: https://github.com/murphystout/implicit-feedback-ml/tree/main)

import numpy as np
import pandas as pd
import implicit
from implicit import evaluation as ev
import time
import scipy
import random
from sklearn import metrics
import scipy.sparse as sparse

df_wide = pd.read_csv("https://raw.githubusercontent.com/murphystout/implicit-feedback-ml/main/df_wide.csv")
csr = scipy.sparse.csr_matrix(df_wide.values)
train, test = ev.train_test_split(csr)
model = implicit.als.AlternatingLeastSquares()

model.fit(train)
ev.ranking_metrics_at_k(model = model, train_user_items = train, test_user_items = test)

It leads to the following error: 

  File "<ipython-input-15-1571189a2fdd>", line 17, in <module>
    ev.ranking_metrics_at_k(model = model, train_user_items = train, test_user_items = test)

  File "implicit/evaluation.pyx", line 251, in implicit.evaluation.ranking_metrics_at_k

  File "implicit/recommender_base.pyx", line 170, in implicit.recommender_base.MatrixFactorizationBase.recommend

  File "implicit/recommender_base.pyx", line 320, in implicit.recommender_base.MatrixFactorizationBase._user_factor

IndexError: index 3295 is out of bounds for axis 0 with size 3295

Any help is greatly appreciated!

**Comment by nicolaneo** [comment]
@murphystout I think I have the same issue at the moment, did you find a solution?

**Comment by murphystout** [comment]
Nope, unfortunately not.

**Comment by igorkf** [comment]
If I'm not wrong, when training with `fit()` method you have to pass a matrix of (rows: items, cols: users, values: ratings), but when I use the method `recommend()` I have to pass a matrix of (rows: users, cols: items, values: ratings).      
Seems that `ranking_metrics_at_k()` calls `recommend()` method, so I think you have to transpose the matrix when evaluating or recommending.

**Comment by LorenzoMinto** [comment]
#433 seems the same. Dimension inconsistency is most likely the issue

**Comment by LorenzoMinto** [comment]
Duplicate of #433

**Comment by murphystout** [comment]
Works! Thank you!
