### ISSUE TITLE
Clarify or rename `filter_items`

### ISSUE THREAD

**Issue by thorbjornwolf** [benfred/implicit#43]
Hi, thanks for this nice package!

[`AlternatingLeastSquares.recommend`](https://github.com/benfred/implicit/blob/master/implicit/als.py#L90) has a parameter called `filter_items`, which, apart from the source code, does not have any documentation.

The same parameter is found in [`RecommenderBase`](https://github.com/benfred/implicit/blob/master/implicit/recommender_base.py#L16), [`AnnoyAlternatingLeastSquares`](https://github.com/benfred/implicit/blob/master/implicit/annoy_als.py#L91), and [`ItemItemRecommender`](https://github.com/benfred/implicit/blob/master/implicit/nearest_neighbours.py#L23).

Before reading the source, I thought it was a whitelist of items that the recommendation should select from (which suited my usecase), but as it turns out, it is a blacklist. So, I have a two suggestions I'd like to hear your thoughts on:

1. Deprecate `filter_items`, and make a more descriptively named parameter such as `skip_items`, `ignore_items`, or `item_blacklist`.
2. Put an explanation in the docstrings: `filter_items: A list of items that should not be recommended`.

I would think the second one is a no-brainer - of course it should be documented. The first one, however, is a bit more bold. Thoughts?

As another remark (should I move it to another issue?), the line `if filter_items:` [such as here](https://github.com/benfred/implicit/blob/master/implicit/nearest_neighbours.py#L34) doesn't work with numpy arrays. I would suggest moving to `if filter_items is not None:` instead.

**Comment by benfred** [comment]
Thanks for the feedback! I totally agree - the documentation here has been lacking, and we should have full docstrings for all the methods.

I started on this a little today:https://github.com/benfred/implicit/commit/64135ccfed24cde818168f53007549706e72323c .

These docs are hosted at [http:///implicit.readthedocs.io/en/latest/](http:///implicit.readthedocs.io/en/latest/). While the docs still need fleshing out, all the common methods and parameters are now documented.

I also agree that switching the filter_items logic to work with numpy arrays makes sense - I'll add that in soon.

**Comment by NTAWolf** [comment]
Wow, very nice! This looks great :-) Thanks a bunch!

**Comment by dminovski0** [comment]
Is it possible for the parameter `filter_items` to be added to the `AlternatingLeastSquares.similar_items` method, and a parameter names `filter_users` to be added to the `AlternatingLeastSquares.similar_users` method, so that the sent items and users are not returned?

**Comment by dminovski0** [comment]
@benfred Thank you.

**Comment by benfred** [comment]
#481 implements both the filter_items for similar_items/similar_users as well as working with numpy arrays.

**Comment by P-Light** [comment]
Hello! Can you explain how filter_items works? When I pass a list with item indices in similar_items method I get these indices with -inf weight. It is not filtering really
