### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by iAlpha77** [benfred/implicit#432]
Building wheel for pycares (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\alpha\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\alpha\\AppData\\Local\\Temp\\pip-install-j5jdtd2m\\pycares\\setup.py'"'"'; __file__='"'"'C:\\Users\\alpha\\AppData\\Local\\Temp\\pip-install-j5jdtd2m\\pycares\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\alpha\AppData\Local\Temp\pip-wheel-6m8i5_12'
       cwd: C:\Users\alpha\AppData\Local\Temp\pip-install-j5jdtd2m\pycares\
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\pycares
  copying src\pycares\errno.py -> build\lib.win-amd64-3.9\pycares
  copying src\pycares\utils.py -> build\lib.win-amd64-3.9\pycares
  copying src\pycares\_version.py -> build\lib.win-amd64-3.9\pycares
  copying src\pycares\__init__.py -> build\lib.win-amd64-3.9\pycares
  copying src\pycares\__main__.py -> build\lib.win-amd64-3.9\pycares
  running build_ext
  generating cffi module 'build\\temp.win-amd64-3.9\\Release\\_cares.c'
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  building '_cares' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for pycares
  Running setup.py clean for pycares
Failed to build pycares
Installing collected packages: pycares, aiodns, proxybroker, colorama, certifi, urllib3, requests, asyncio
    Running setup.py install for pycares ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\alpha\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\alpha\\AppData\\Local\\Temp\\pip-install-j5jdtd2m\\pycares\\setup.py'"'"'; __file__='"'"'C:\\Users\\alpha\\AppData\\Local\\Temp\\pip-install-j5jdtd2m\\pycares\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\alpha\AppData\Local\Temp\pip-record-gmk_s_bn\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\alpha\appdata\local\programs\python\python39\Include\pycares'
         cwd: C:\Users\alpha\AppData\Local\Temp\pip-install-j5jdtd2m\pycares\
    Complete output (17 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\pycares
    copying src\pycares\errno.py -> build\lib.win-amd64-3.9\pycares
    copying src\pycares\utils.py -> build\lib.win-amd64-3.9\pycares
    copying src\pycares\_version.py -> build\lib.win-amd64-3.9\pycares
    copying src\pycares\__init__.py -> build\lib.win-amd64-3.9\pycares
    copying src\pycares\__main__.py -> build\lib.win-amd64-3.9\pycares
    running build_ext
    generating cffi module 'build\\temp.win-amd64-3.9\\Release\\_cares.c'
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    building '_cares' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\alpha\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\alpha\\AppData\\Local\\Temp\\pip-install-j5jdtd2m\\pycares\\setup.py'"'"'; __file__='"'"'C:\\Users\\alpha\\AppData\\Local\\Temp\\pip-install-j5jdtd2m\\pycares\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\alpha\AppData\Local\Temp\pip-record-gmk_s_bn\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\alpha\appdata\local\programs\python\python39\Include\pycares' Check the logs for full command output.
i need help please

**Comment by benfred** [comment]
Looks like you are trying to install pycares - which isn't this package
