### ISSUE TITLE
Problem with number of factors in gpu mode

### ISSUE THREAD

**Issue by alexeigor** [benfred/implicit#439]
I think, in this line we have a problem with number of factors.
Should we change this line
https://github.com/benfred/implicit/blob/80f0e4d372c9808f39e8d72af4aa8403a119e2a3/implicit/gpu/bpr.py#L64
to 
`if factors % 32:` 
?

**Comment by benfred** [comment]
We store the bias term with the factor matrices - which is why we need the extra '1' in that check. I believe this is correct =)
