### ISSUE TITLE
Same code+same machine+different Python environments result in 10x difference in execution time of ALS fit

### ISSUE THREAD

**Issue by skotaro** [benfred/implicit#440]
I have two Python environments on my six-core MBP:
- Python 3.7.3 (Anaconda)
  - implicit  0.4.4
  - numpy  1.19.4
  - scipy  1.5.2
- Python 3.8.6 (pyenv+pipenv)
  - implicit = "0.4.4"
  - numpy = "1.19.4"
  - scipy = "1.5.4"

When I run my .py file which uses `implicit.als.AlternatingLeastSquares` in the two environments, there is a significant difference in execution time for `fit` method. With Python 3.7, it takes 50 seconds. But with 3.8 it takes 500 seconds. I noticed when it comes `fit`, Python 3.7 uses 100% CPU in Activity Monitor, and Python 3.8 uses 600% = six 100% cores.
This seems strange because the latter uses more computational power but takes 10x longer time.

I confirmed that the code includes MKL and OpenBLAS setting parameters shown below and no warning is shown.
```
os.environ['MKL_NUM_THREADS'] = '1'
os.environ['OPENBLAS_NUM_THREADS'] = '1'
```

Another strange behavior which may be related to this issue is that setting `num_threads=1` in Python 3.8 environment does not change 600% CPU usage.

In addition to the execution time difference, I found that `similar_items` gives slightly different scores (and ranking order as a result) as well despite the fixed `random_state`.

It looks like a multiprocessing issue but I'm not familiar with it. I would like to have coherent results and performance between the two environments to convince myself.

Is there any workaround ? or did I miss something?

**Comment by benfred** [comment]
Can you check the BLAS config for the slow version?  I'm wondering if you're running the OSX accelerate blas: https://developer.apple.com/documentation/accelerate/blas - 

```python
import numpy as np
np.__config__.show()
```

If your are running accelerate, there is probably a similar environment variable to disable its internal multithreading - maybe try setting VECLIB_MAXIMUM_THREAD .

If you're not running accelerate can you try setting the environment variables outside of the python code (like ```export MKL_NUM_THREADS=1``` etc  in your shell before running). Setting the environment variables with python might not get them set in time when the blas framework initializes.

**Comment by skotaro** [comment]
Fast environment:
```
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/skotaro/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/skotaro/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/skotaro/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/skotaro/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/skotaro/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/skotaro/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/skotaro/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/skotaro/anaconda3/include']
```

Slow environment:
```
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
```

Seems Apple's Accelerate is not used. (Well, actually I've never heard of the framework...)

By following your advice to `export` the environment variables before running .py, the slow environment now marks 70 seconds which is comparable to the faster one. I also confirmed that putting two `os.environ[...] = '1'` before `import implicit`, which were put AFTER `import implicit` in the original code, does have the same effect as setting the variables outside the python code.

Thank you for the advice. Now it's clear. I'll make PR to mention this pitfall in README.md.

**Comment by benfred** [comment]
Glad that you got this working !
