### ISSUE TITLE
Option to install implicit without GPU support

### ISSUE THREAD

**Issue by epetrovski** [benfred/implicit#446]
It would be great if there was an option to install implicit without GPU support. 

I'm currently not able to install implicit seemingly because running `pip install implicit` detects CUDA but then install fails with `/usr/bin/ld: cannot find -lcublas`.

**Comment by epetrovski** [comment]
I was able to fix my lcublas issue. But still, it would be nice if the user could opt out of GPU support at install time.

**Comment by caijunjieNick** [comment]
@epetrovski Hello, i have also met this problem. I have installed implict in my Server (Ubuntu),but it showed me "cuda extension is built, but disabling gpu support because of '{e}'". Do u know how to fix it. Thanks a lot

**Comment by benfred** [comment]
@epetrovski - I've added some code in #561 to allow building implicit with the GPU extension.  You can go `export IMPLICIT_DISABLE_CUDA=1` and then the GPU extension won't get built.

However,  we have prebuilt binary wheels on pypi now - and going `pip install implicit` will install both the CPU and GPU code on linux.  If you don't have a GPU/cuda/cublas  the GPU extension will be automatically disabled though, so this shouldn't be a big deal.
