### ISSUE TITLE
linux or docker implicit compilation slowdowns

### ISSUE THREAD

**Issue by victusfate** [benfred/implicit#452]
I ran into some slowdowns compiling implicit and building docker images on ubuntu.
My setup is a 2020MBP running Docker and running on a container with Ubuntu 20.04

Here's where it starts slowing down immensely (often taking 30min+ to compile):
```
 => => #   x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protec
 => => # tor-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-se
 => => # curity -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c implicit/_als.cpp -o build/temp.linux-x8
 => => # 6_64-3.8/implicit/_als.o -Wno-unused-function -Wno-maybe-uninitialized -O3 -ffast-math -fopenmp -std=c++11 
```
I wonder if I can force it use another faster compiler on linux, and what others recommend?
I started looking at installing [llvm/clang](https://apt.llvm.org/).
And am checking [this](https://stackoverflow.com/questions/7832892/how-to-change-the-default-gcc-compiler-in-ubuntu) for how to ensure which compiler has priority.

on my local system (mac) it builds with g++-9 in a couple of minutes or less.

**Comment by benfred** [comment]
I'm not sure why this would take 30+ minutes to compile for you - on my linux box this package compiles in about 90 seconds (including the GPU code) . On my 2020 MBP this compiles in about 40 seconds (g++-10).  I'm guessing this is something about your environment - do other packages compile slowly with your setup? 

I have prebuilt binaries on conda-forge if you don't want to compile from source.

**Comment by victusfate** [comment]
It only appears to build slowly with docker so I suspect its related. I haven't tested it must recently but will definitely share anything I find. What I ended up doing was building it in a separate image so it cached + rebuilt quickly.
