### ISSUE TITLE
ALS generate zero embeddings when unseen user or item in evaluation data

### ISSUE THREAD

**Issue by MaiziXiao** [benfred/implicit#457]
When using ALS to train on our data, we are using random train test split. We found out that after evaluation, the model will automatically assign zero embeddings for those product or user that does not exist in train data (although a very small proportion), and this cause our downstream application to throw an error. 
So I have two questions:

1.  Is this the expected behavior of ALS implementation? 
2.  I think random train test split is not the best fit in ALS model. What is the best practice to do evaluation for ALS model.

**Comment by ita9naiwa** [comment]
Sorry for the late response.

1. Yes.
2. Removing zero rows and  cols are not that expensive operation.
 suppose that `mat` is our CSR matrix and  p_mat is reduced matrix,

it'll be done like
```
# Filter users w.o 10 clicks
_mat = mat.tocsr()[np.asarray((mat.sum(1) >= filter_u)).ravel(), :]
_mat = _mat.transpose().tocsr()
# Filter items w.o 10 clicks
__mat = _mat[np.asarray(mat.sum(0) >= filter_i).ravel(), :].transpose()
__mat.shape
p_mat = __mat
```
