### ISSUE TITLE
change the implicit information

### ISSUE THREAD

**Issue by yustiks** [benfred/implicit#461]
Hello!
I would like to change the implicit feedback given for the matrix of ratings.
Namely, I would like to exclude certain values from the implicit matrix information: for example, if the rating is equal 4, I don't want to include it into the implicit information.
How to do it properly?

**Comment by yustiks** [comment]
> In the movielens example, we exclude everything less than a 4 star rating by going like :
> 
> https://github.com/benfred/implicit/blob/2588869bc17df922ac03dcada78f3cca9557bd50/examples/movielens.py#L40-L46
> 
> .

thank you, @benfred, for fast reply. I have an additional question:
I have a matrix of ratings, where the ratings can be from 1 to 7.
I would like to exclude rating '4' from implicit feedback, and to leave all the other ratings.
How would you recommend to do it?

**Comment by benfred** [comment]
> thank you, @benfred, for fast reply. I have an additional question:
I have a matrix of ratings, where the ratings can be from 1 to 7.
I would like to exclude rating '4' from implicit feedback, and to leave all the other ratings.
How would you recommend to do it?

You can filter out ratings in the same way 
``` python 
 ratings.data[ratings.data < min_rating] = 0 
 ratings.eliminate_zeros() 
 ratings.data = np.ones(len(ratings.data)) 
```
