### ISSUE TITLE
Evaluating accuracy / metrics for Item-to-Item recs?

### ISSUE THREAD

**Issue by kmcmearty** [benfred/implicit#462]
Are there metrics or techniques to evaluate the accuracy of Item-to-Item recommendations?

**Comment by dlont** [comment]
I would be also interested in evaluation metrics for item-item recommendations.

**Comment by kmcmearty** [comment]
@dlont 

This is all I could find regarding [item-item metrics](https://docs.microsoft.com/en-us/azure/machine-learning/studio-module-reference/evaluate-recommender#bkmk_RelatedItems). I haven't implemented it yet but its a start.

**Comment by dlont** [comment]
Great page! Thanks a lot!
