### ISSUE TITLE
Freeze pretrained weights

### ISSUE THREAD

**Issue by phiweger** [benfred/implicit#467]
Following up on #341 : Is it possible to freeze the pretrained weights, so that they are not changed during training?

**Comment by benfred** [comment]
Is the use case here incremental retraining ?  I'd like to add support for that at some point - though I was thinking of a different API than freezing items you don't want to update

**Comment by slowwavesleep** [comment]
It seems that I came up with same idea as @phiweger.

I think adding something like `if not self.freeze_item_factors` before [this line](https://github.com/benfred/implicit/blob/809674f02baa1898a21acf3a4f6f410cb8e727b2/implicit/cpu/als.py#L168) would do the trick. Which would make Alternating Least Squares not alternating any more, I guess? But still it would be nice to be able to use an existing library for this. For example, to be able to easily evaluate the effect of using existing item factors.

I do realize though, that it would take quite a bit more more work than that to implement.

**Comment by benfred** [comment]
There is a PR here which should make this possible #527 (as well as let you incrementally retrain models on subsets of users/items).

As an example given a `user_items` sparse matrix containing interactions, and a `existing_item_factors` dense matrix containing precalculated item factors:

```python
# Train an ALS model with pre-existing item factors, but calculating user factors
model = AlternatingLeastSquares()
model.item_factors = existing_item_factors
userids = np.arange(user_items.shape[0])
model.partial_fit_users(userids, user_items)
```
