### ISSUE TITLE
implicit.cuda.HAS_CUDA returns false while gpus are installed correctly on linux

### ISSUE THREAD

**Issue by mhajiaghayi** [benfred/implicit#470]
hi, implicit.cuda.HAS_CUDA in my linux machine returns false while i have got gpu and cuda installed on my machine. 

implicit==0.4.4

 NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2  

thanks, Mahdi

**Comment by benfred** [comment]
How did you install implicit?  If you're installing from source - was there any messages in the build output?

I've just pushed a new version out - that will include prebuilt binaries on conda for  cuda 11.2 (the previous version only had up to cuda 11.2). If you're installing from conda can you try the latest version?

**Comment by benfred** [comment]
Going to close this as I haven't heard back - and there have been a couple fixes to the CUDA build process recently that may have fixed this.

Let me know if this is still occurring,
