### ISSUE TITLE
Recommend_all Value error

### ISSUE THREAD

**Issue by Patos91** [benfred/implicit#471]
Hello everyone, i'm trying to use recommend_all but i'm getting this error:

ValueError: output array is not acceptable (must have the right datatype, number of dimensions, and be a C-Array)

I'm using the model like this:

model.recommend_all( sparse_person_content,  N=10,
                       filter_already_liked_items=True, filter_items=None,
                       show_progress=True   )

My sparse person content is:
sparse_person_content = sparse.csr_matrix((df['eventstrength'].astype(float), (df['customer_id'], df['product_id'])))

recommend for a single user work just fine
 
Please help

**Comment by slarrain** [comment]
I'm getting the same error.

**Comment by benfred** [comment]
Can either of you share some dummy test data that will reproduce this issue? I'm not seeing this myself

**Comment by benfred** [comment]
Also does this happen on the api_refactor branch from  #481  ? The recommend_all method is substantially rewritten as part of this.

**Comment by benfred** [comment]
I've merged the API changes in #494 - let me know if this is still happening

**Comment by slarrain** [comment]
I will check it and get back to you. Thanks!
