### ISSUE TITLE
Failure installing in Windows10

### ISSUE THREAD

**Issue by shirishr** [benfred/implicit#48]
OS: Windows 10
Python Version: 3.5.2
Cython Version: 0.26
scipy Version: 0.19.1

pip install implicit as well as python setup.py install result in errors:

  gcc: error: /O2: No such file or directory
  gcc: error: /openmp: No such file or directory

I thought openmp was only relevant for OSX. Any suggestions?

**Comment by benfred** [comment]
Are you using GCC on windows? The compile flags there (/02 /opemp) are valid for Visual Studio, but not for gcc. 

I believe if you build with visual studio this will work. I don't have a windows box to test on unfortunately, but there is some basic CI for windows running on appveyor: https://github.com/benfred/implicit/blob/master/appveyor.yml
