### ISSUE TITLE
Evaluation on GPU

### ISSUE THREAD

**Issue by bakachan19** [benfred/implicit#485]
Hi. First of all thank you for all the work you have been putting into this project.
I am still new to this library and I was playing around just to get a better hang of it.

I am encountering some issues when I try to evaluate a model that has been trained with ALS and flag use_gpu =  True.
Basically what I want to do is to train a recommender model using the GPU and then call the evaluation metrics such as precision, etc on the trained model. I was trying to make it work on the following piece of code:
```
from implicit.evaluation import precision_at_k, train_test_split
from implicit.als import AlternatingLeastSquares
from implicit.datasets.movielens import get_movielens


movies, ratings = get_movielens("1m")
train, test = train_test_split(ratings)

model = AlternatingLeastSquares(factors=128, regularization=20, iterations=10, use_gpu = True)
model.fit(train)
p = precision_at_k(model, train.T.tocsr(), test.T.tocsr(), K=10, num_threads = 4)
```

I manage to train the model, but then i get the following error when calling the precision@k:
```
RuntimeError                              Traceback (most recent call last)

<ipython-input-41-0154afb20e6c> in <module>()
     10 model.fit(train)
     11 
---> 12 p = precision_at_k(model, train.T.tocsr(), test.T.tocsr(), K=10)
     13 

implicit/evaluation.pyx in implicit.evaluation.precision_at_k()

implicit/evaluation.pyx in implicit.evaluation.ranking_metrics_at_k()

/usr/local/lib/python3.7/dist-packages/implicit/gpu/matrix_factorization_base.py in recommend(self, userid, user_items, N, filter_already_liked_items, filter_items, recalculate_user)
     49         # calculate the top N items, removing the users own liked items from the results
     50         # TODO: own like filtering (direct in topk class
---> 51         ids, scores = self._knn.topk(self.item_factors, self.user_factors[userid], count)
     52         return list(
     53             itertools.islice((rec for rec in zip(ids[0], scores[0]) if rec[0] not in liked), N)

implicit/gpu/_cuda.pyx in implicit.gpu._cuda.KnnQuery.topk()

RuntimeError: Cuda Error: invalid device function (implicit/gpu/knn.cu:336)
```

I am using implicit on Google Colab and I tried with ```!pip install implicit``` and also with ```!conda install -c conda-forge implicit implicit-proc=*=gpu``` after installing miniconda on colab. At the time of the testing, this is what colab provided as GPU and CUDA version.

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.74       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P0    57W / 149W |    591MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

If i try using use_gpu=False, everything works just fine and I am able to compute the precision value, which in this case is ~0.38.

Does anyone have an idea on what I am doing wrong?
Could someone please explain how should I do the evaluation with GPU?

Thanks in advance for any advice and help.
Have a great day!.

**Comment by benfred** [comment]
Can you try building from source? I think we might need something like 

```-gencode=arch=compute_37,code=sm_37``` to the list of architectures here https://github.com/benfred/implicit/blob/52a307e97da0a3c2bc1af6ee082d032ad460a157/cuda_setup.py#L64

**Comment by benfred** [comment]
The latest version (v0.5.1) has support for the K80's found on google colab. 

I've verified that both training and inference work on the GPU on google colab - with the gpu inference being substantially faster than cpu:

<img width="562" alt="Screen Shot 2022-01-28 at 11 02 27 AM" src="https://user-images.githubusercontent.com/69536/151606053-b89e4e54-7444-4e6c-b109-cd93be09f989.png">

(note that you'll have to go `pip install cmake --upgrade` on google colab before installing implicit right now to get the GPU extension built - until there is a new released version with this https://github.com/benfred/implicit/pull/534 change included).
