### ISSUE TITLE
Apple Silicon build

### ISSUE THREAD

**Issue by jmsmcniff** [benfred/implicit#490]
Add an Apple Silicon build of Implicit to miniforge.

Thank you!

**Comment by benfred** [comment]
I've enabled building apple silicon wheels in #553 - these will get pushed automatically to pypi during releases. Note that this is only enabled for python v3.8+ right now.  

You can download these wheels from the 'artifacts' link here https://github.com/benfred/implicit/actions/runs/2045980810 - and `pip install implicit` should install these wheels after the next release. Note: I don't have an apple silicon machine to test these out on, so please let me know if these work out for you or not.
