### ISSUE TITLE
Recommend users per product

### ISSUE THREAD

**Issue by Patos91** [benfred/implicit#492]
Hello everyone , i'm looking to find users per item like inverse type of the usual recommendation.
IE: For item SKU 45667 -> Recommended users  are (John, Pedro, Mike, Jesse , Hank )

Is valid to use the other way around the sparse content matrix and user to achieve this?

model.fit(sparse_person_content*alpha)
model.recommend(45667, sparse_content_person, 5,False)

Thanks

**Comment by benfred** [comment]
Yup - that should work and is probably the easiest way to build this out right now.
