### ISSUE TITLE
Questions about "cufoff" or "threshold" for positive prediction, and associated implications for evaluating performance

### ISSUE THREAD

**Issue by chenrocky** [benfred/implicit#519]
Does `implicit` use a "cutoff" or "threshold" to determine whether or not a user*item score is a positive prediction/recommendation?

**Illustrative example:**
After fitting a model, I'm able to get the `user_factors` and `item_factors` to get scores for the user*item matrix. The minimum score or element value in my matrix is -1.04155 while the maximum score or element value is 2.0477026. This was a model which was fit on data that considered confidence (i.e., the targets were not just 0s and 1s)

Is there a cutoff used in `implicit` to determine which of these values are considered positive predictions (recommendation) as opposed to the negative predictions (non-recommendation)? Should the values in my matrix that are greater than 0 be considered positive predictions (i.e., recommendations)?

I'd like to be able to calculate evaluation metrics by "sliding" (increasing/decreasing) this threshold, and I'd like to understand the details of the default cutoff in `implicit` (if this exists)

**Comment by benfred** [comment]
There isn't a cutoff defined - we're ranking items, so the `model.recommend` calls will return items with the highest scored items first, without filtering values below a given score.

What are you trying to build ? Like is this for a notifications service - where you only notify a user when an item comes in with a sufficiently high score? Also which model are you using?

> This was a model which was fit on data that considered confidence (i.e., the targets were not just 0s and 1s)

 For the ALS model, we're trying to learn to predict a '0' for items the user hasn't interacted with and a '1' for the items the user has interacted with. The confidence values will affect how much weight is given to that example - but the target values will still be 0 or 1. For the BPR model the confidence values are ignored entirely.

> Should the values in my matrix that are greater than 0 be considered positive predictions (i.e., recommendations)?

We're not trying to do ratings prediction or binary classification here, so I wouldn't necessarily make that assumption.

**Comment by chenrocky** [comment]
> Also which model are you using?

ALS

> What are you trying to build ? Like is this for a notifications service - where you only notify a user when an item comes in with a sufficiently high score?

I see your point, and for what I'm building, the cutoff isn't needed since all scores will be considered. I was mainly asking about the cutoff for evaluating my ALS model, but I'm now realizing that the traditional evaluation metrics for classification models (i.e., accuracy, precision, recall, f1) can't be applied in the same way to a recommender model. I should just stick with p@k, r@k, and the other evaluation metrics specifically used for recommender systems.

I think the better questions for me to ask are: How do I interpret the user*item matrix scores properly? How should I interpret a score of 0? How should I interpret the negative scores? How should I interpret larger negative scores?

And are the ALS scores just all relative? Could I normalize/scale the entire matrix of ALS scores so that they're between 0 and 1 and still interpret the scores in the same relative way when my min was -1.04155 and my max was 2.0477026?

**Comment by ita9naiwa** [comment]
> I think the better questions for me to ask are: How do I interpret the user*item matrix scores properly? How should I interpret a score of 0? How should I interpret the negative scores? How should I interpret larger negative scores?

in models of this framework, and as in most other recommender models, Score alone itself is really hard to interpret (I believe it has no meaning alone.) They are understood relatively, (or in ranking e..g,  the score of item A is higher than the score of item B.

> And are the ALS scores just all relative? Could I normalize/scale the entire matrix of ALS scores so that they're between 0 and 1 and still interpret the scores in the same relative way when my min was -1.04155 and my max was 2.0477026?

yes, if you normalize scores preserving their orders.
