### ISSUE TITLE
nmslib recommend 

### ISSUE THREAD

**Issue by datascienceit** [benfred/implicit#52]
I've been running the [movielen](https://github.com/benfred/implicit/blob/master/examples/movielens.py) example, trying to use `approximate_als.NMSLibAlternatingLeastSquares` instead os the `AlternatingLeastSquares`.
The recommend function returns indexs I can't decipher what they means.
I think there might be a bug.
It fails when I try to use the `movie_lookup[movie]`.

**Comment by jbochi** [comment]
[`.recommend`](http://implicit.readthedocs.io/en/latest/als.html#implicit.als.AlternatingLeastSquares.recommend) returns a `List of (itemid, score) tuples`

**Comment by benfred** [comment]
Also checkout out  the last.fm example - which has the ability to generate recommendations for each user now: https://github.com/benfred/implicit/blob/master/examples/lastfm.py#L120
