### ISSUE TITLE
Get user factors per id

### ISSUE THREAD

**Issue by datascienceit** [benfred/implicit#53]
I can see the the first entry for user_factors is for new user.
But if I know which user id I want, how can I retrieve it per user? how to match each user to it's factors?

**Comment by datascienceit** [comment]
I get we can have the features with the `explain` function, but I get (100,100) array, shouldn't it be only the 100 factors?

**Comment by jbochi** [comment]
`users_factors` is a matrix. Each col is the latent vector for that user.

`explain` returns 3 parameters: See the documentation [here](http://implicit.readthedocs.io/en/latest/als.html#implicit.als.AlternatingLeastSquares.explain). Only the last one is a matrix and you can ignore it if you don't need to call this method multiple times for the same user.

**Comment by datascienceit** [comment]
How do yo define the user `i`? 
For example for this matrix
```
| user | item | rating |
|------|------|--------|
| 3    | 1    | 1      |
| 3    | 2    | 1      |
| 1    | 2    | 3      |
```
What is user `i=1`?
