### ISSUE TITLE
Installation process hangs for 0.5.2

### ISSUE THREAD

**Issue by chekhovana** [benfred/implicit#537]
pip installation starts and never ends, its true for installing in colab or locally on macos
![Screenshot 2022-01-30 at 13 00 32](https://user-images.githubusercontent.com/6779698/151695288-d748edf8-ff32-4496-95d1-fd7cb6ecde70.png)

**Comment by benfred** [comment]
Can you try running this with `pip install implicit -v` to display debug output? I'm suspecting that its not hanging, just talking longer than expected. The packages on pip are doing a source install - so by going `pip install implicit` you need to compile all the code - and then new version includes GPU inference code that can take some time to install. 

You can speed this up a bit by only compiling for the GPU architecture that you're on - for instance if you're on colab and have a K80 gpu you can go `IMPLICIT_CUDA_ARCH=37 pip install implicit -vv` which should finish quite a bit faster

**Comment by chekhovana** [comment]
Yes, you are right, according to debug output, it just takes too long to compile.

Thank you.

**Comment by benfred** [comment]
@chekhovana - I've added pre-built binaries to pypi with #546 , this should install in a couple of seconds on google colab now,

**Comment by chekhovana** [comment]
Thanks a lot, Ben
