### ISSUE TITLE
No iteration log

### ISSUE THREAD

**Issue by clockwiser** [benfred/implicit#54]
Tried the following source to get iteration log.

model = AlternatingLeastSquares(factors=20, 
                                regularization = 0.1,
                                calculate_training_loss=True,
                                iterations = 150,
                                num_threads=4)

Strangely there was no log of iteration loss. Checked the source als.py, but don't know why.
It runs OK. Just no log to check the output.

**Comment by clockwiser** [comment]
I found the reason, because I run implicit on jupyter  notebook. Now the problem is how to get around it.

**Comment by jbochi** [comment]
try this:

```
import logging
log = logging.getLogger("implicit")
log.setLevel(logging.DEBUG)
logging.basicConfig(format='%(asctime)s %(levelname)s:%(message)s', level=logging.DEBUG, datefmt='%I:%M:%S')
```

**Comment by clockwiser** [comment]
Oh, it is working. Thank you.
