### ISSUE TITLE
Consider exposing evaluation functions

### ISSUE THREAD

**Issue by jperiodlangley** [benfred/implicit#540]
Hi,

I've been using the implicit library for some exploratory work, and noticed that the implicit.evaluation functions are not exposed publicly. I have my own version of the train_test_split, precistion_at_k, and auc_at_k - but likely much slower than your cython implementation. Do you think it would be advisable to expose the evaluation functions, or make them available through a model?

I would be happy to provide a pull request and help test if you think this is advisable.

**Comment by ita9naiwa** [comment]
Sorry for late response.

you can see code here;
https://github.com/benfred/implicit/blob/main/implicit/evaluation.pyx

you can wrap your recommendation module to be compatible with evaluation modules here and you can plug it in.

**Comment by jperiodlangley** [comment]
Thanks for doing this! I appreciate it.
