### ISSUE TITLE
MAP and DCG metrics >1 when using bm25-weighting on rating-list

### ISSUE THREAD

**Issue by olivergernetzke** [benfred/implicit#545]
Hey guys,

so when I'm using the bm25-weighting-algorithm on my rating list and then evaluate my models the map and ndcg metrics are above 1:
![image](https://user-images.githubusercontent.com/74661634/154726098-d8d4c489-7b24-4119-9b8f-633f7286e02f.png)

I basically first build a list of users and items with quantities as implicit feedback. Then, I wanted to try weighting the ratings using the bm25-weighting algorithm as proposed in the tutorial.
Lastly, I splitted that weighted list into train and test data using the leave_k_out_split.

I always thought that these metrics can only have values ranging from 0 to 1, or am I missing something here?
Thanks for your help.

**Comment by ita9naiwa** [comment]
Sorry for the late response. could you check that `K <= num_items`?
