### ISSUE TITLE
recommend function in MatrixFactorizationBase cannot set num_thread in topk function

### ISSUE THREAD

**Issue by Crayon-ShinChan** [benfred/implicit#554]
`recommend` function in `MatrixFactorizationBase` class cannot control the num_thread in `topk` function

https://github.com/benfred/implicit/blob/cad50195962a0d14dfd113c98d9ec341a6733bbe/implicit/cpu/matrix_factorization_base.py#L75-L81

https://github.com/benfred/implicit/blob/42895fcc7e3ceab5add9e3860e6c3fa07594245c/implicit/cpu/topk.pyx#L15

Because the num_thread set to be 0 in default, I met the problem "BLAS : Program is Terminated. Because you tried to allocate too many memory regions." with Spark on yarn. The reason behind was that I didn't have enough memory for the number of cpu I had in the containers.

Therefore, I want to set `num_thread` to limit the number of cpu to use, which can avoid the error "you tried to allocate too many memory regions."

**Comment by benfred** [comment]
@Crayon-ShinChan yeah, each CPU core is doing a batch of 100 items - which will require `100 * num_items * sizeof(float)` bytes. If you're running with a lot of items and not much memory this could exhaust the available memory.

I have a fix in https://github.com/benfred/implicit/pull/562 that will use the 'num_threads' parameter on the model to control how many threads are used in the topk calls.
