### ISSUE TITLE
ItemItemRecommender recommend the same items for all users

### ISSUE THREAD

**Issue by ahmedushka7** [benfred/implicit#555]
ItemItemRecommender is working wrong. It's recommend the same items for every user.
<img width="828" alt="Screenshot 2022-03-30 at 02 06 11" src="https://user-images.githubusercontent.com/36453684/160720820-98c2d869-f43e-4806-b62d-ac1e40bbc299.png">

**Comment by benfred** [comment]
The API has changed in implicit v0.5.0 - and you're hitting this change https://github.com/benfred/implicit/pull/526 =(.

The Item-Item models look up the interactions for each user in the input batch, using the 'user_plays' to look up items.  

```python
model.recommend(0, user_plays[0], N=5)
model.recommend(1, user_plays[1], N=5)
model.recommend(223, user_plays[223], N=5)
```
The MF models throw an error when the number of rows in user_plays sparse matrix doesn't match the number of rows in the userids, we should update the ItemItem models to also do the same thing.

**Comment by benfred** [comment]
closing - let me know if you have any other questions!
