### ISSUE TITLE
The latest version installed without save and load

### ISSUE THREAD

**Issue by yexiao1107** [benfred/implicit#559]
I use pip install implicit, but the latest version installed without save and load

**Comment by yexiao1107** [comment]
Thanks reply, and I have another issues, when I use "partial_fit_users" , I find the user vector is very small after training, and the recommad result is same, I do not know how to solve this. Is there a length limit of the click items?

**Comment by benfred** [comment]
>  Thanks reply, and I have another issues, when I use "partial_fit_users" , I find the user vector is very small after training, and the recommad result is same, I do not know how to solve this. Is there a length limit of the click items?

Can you create a new issue for this - and maybe a sample script to replicate?  I find that after partial_fit_users the recommendations are the same as if called during 'fit'

**Comment by benfred** [comment]
v0.6.0 should have the save/load functionality -
