### ISSUE TITLE
Optimize for ranking instead of rmse

### ISSUE THREAD

**Issue by datascienceit** [benfred/implicit#56]
In many cases, ranking the items is an easier problem then solving the matrix.
That can be implemented by optimise the precision-recall instead of the RMSE.
Another cool feature.

**Comment by benfred** [comment]
I added a BPR model here https://github.com/benfred/implicit/pull/81 that optimizes for a pairwise ranking loss. I might add some other learning to rank models at a later date - but I'm closing this for now.
