### ISSUE TITLE
Documentation link on PyPi is out of date

### ISSUE THREAD

**Issue by lanej5** [benfred/implicit#564]
I'm sure this isn't the ideal place to raise this, but I just wanted to flag for you that the [pypi page](https://pypi.org/project/implicit/) for version 0.5.2 has a documentation link on it that points at [some old documentation which seems to be out of date](https://implicit.readthedocs.io).

Great package, thanks!

**Comment by benfred** [comment]
Thanks for raising!

I don't see this problem myself though - the readthedocs.io site is out of date, but I don't see a link to that on the pypi page, and all the docs links I see got to https://benfred.github.io/implicit/ which has the up to date documentation.

Can you post a screenshot to the link that's pointing to the wrong place? I even scanned the html source and didn't see any readthedocs references =(

**Comment by lanej5** [comment]
I don't see the link to the readthedocs.io site anymore either. Problem solved I guess. ¯\_(ツ)_/¯

**Comment by benfred** [comment]
Nice!
