### ISSUE TITLE
[Question] How to deal with Big Data 

### ISSUE THREAD

**Issue by leviethung2103** [benfred/implicit#566]
I am wondering that how can I use the implicit with a very large dataset. 
Suppose that I have over 300 million records of users x items x ratings (3GB on disk)

Previously, I used the pandas to load the csv files to combine into one gaint dataframe. However, the processing time on this dataframe was too slow and sometimes whole dataset could not fit memory. My machine is about 8GB in RAM 

Do you have any ideas to deal with problem? Thank you

**Comment by ddofer** [comment]
Keep the data in a binary format on disk, like parquet or feather. And look into training in minibatches. And use a machine with more ram, e.g. 16 or 32 GB. easy
