### ISSUE TITLE
ImportError: No module named approximate_als

### ISSUE THREAD

**Issue by learningplussharing** [benfred/implicit#58]
Hi Ben,

First let me thank you so much for this amazing software!  I really appreciate the time and effort that went into it.  I'm excited to try the changes that permit quick recommendations but I'm getting the following error when I try to run the lastfm.py example:

`Traceback (most recent call last):
  File "lastfm.py", line 27, in <module>
    from implicit.approximate_als import (AnnoyAlternatingLeastSquares, NMSLibAlternatingLeastSquares,
ImportError: No module named approximate_als`

PyCharm also says `cannot find reference 'approximate_als' in __init.py__`

Note that the line numbers may be off by a few as I added: `import os
os.environ["OPENBLAS_NUM_THREADS"] = "1"` in light of a related OpenBLAS warning I received.

I'm on Xubuntu that I installed a few days ago (not a VM).

I can comment out the approximate_als import and the subsequent reference to it, and the code then runs fine (giving a quick test with bm25).  I tried to figure out a solution and it's probably really obvious but I haven't figured it out.

Probably unhelpful stuff I did to try to fix it: I tried adding "from . import approximate_als" to the top of __init__.py and "approximate_als to "__all__ =" but that didn't work.  I also tried blanking out __init__.py but that didn't work.  I did a pip install nmslib and pip install annoy after combing through your blog but that didn't help.

Thanks for any thoughts you might have!

**Comment by benfred** [comment]
Sorry about that - I forgot to update the version on pypi, so if you installed from there you would be missing the latest approximate_als code. I've updated pypi to version 0.2.7 and it should work now.
