### ISSUE TITLE
zsh: illegal hardware instruction - Mac M1 - OS Monterey 12.3.1

### ISSUE THREAD

**Issue by LeGabriel** [benfred/implicit#582]
Hi there !

I am using implicit to make reco (duh haha).

Here is something I am trying to do.

```
import numpy as np
from implicit.approximate_als import NMSLibAlternatingLeastSquares

model = NMSLibAlternatingLeastSquares(factors=128, dtype=np.float32)
```
But when I run it, I get "zsh: illegal hardware instruction". 
Any idea on how to solve this ?

My computer : 
MacBook Pro
Apple M1 
OS Monterey 12.3.1
python : 3.8.0

Thanks in advance :) !

Gabriel

**Comment by LeGabriel** [comment]
https://github.com/allenai/scispacy/issues/372

Found my solution here ! :)

**Comment by benfred** [comment]
Glad you sorted this out @LeGabriel - and thanks for linking out to the fix

**Comment by LeGabriel** [comment]
You are welcome, but I feel kinda dumb that I found the fix a few hours later haha :)
