### ISSUE TITLE
AttributeError: module 'implicit' has no attribute 'cpu'

### ISSUE THREAD

**Issue by portkeys** [benfred/implicit#589]
Hi @benfred 
I've been using implicit 0.4.8 for more than a year. With the update to 0.5.2, I'm having trouble to apply the ALS model to both my data and the lastfm data.

For example, below is an attempt trying to follow the tutorial in example folder:

<img width="1140" alt="Screen Shot 2022-07-06 at 3 33 25 PM" src="https://user-images.githubusercontent.com/16803550/177654392-57b0ac64-c35e-4d82-a98f-253ebf022c3c.png">

==============================
**If I remove the `alpha`**, I got the error indicating no attribute 'cpu', which is also the same error we got in our production system.
@benfred It'll be really appreciated if you could point me to the right direction. Thanks so much for all your work!

<img width="1132" alt="Screen Shot 2022-07-06 at 3 35 35 PM" src="https://user-images.githubusercontent.com/16803550/177654594-f7247ce3-634c-498b-9d59-77ea06a540dc.png">

=================================
I even tried to import this way `from implicit.cpu.als import AlternatingLeastSquares`, and then it will return another error as 
`TypeError: Can't instantiate abstract class AlternatingLeastSquares with abstract method rank_items`

**Comment by ita9naiwa** [comment]
Hi. the `alpha` argument in ALS is updated in the main branch and it's not been released yet. ALS in `0.5.2` version does not contain `alpha` argument yet.

**Comment by ita9naiwa** [comment]
Hi. 0.6.0 version has released and did you check it... as I checked, it worked well in your case.

**Comment by portkeys** [comment]
> Hi. 0.6.0 version has released and did you check it... as I checked, it worked well in your case.

Yes it works! Thanks so much!!!
