### ISSUE TITLE
tf.SparseTensor

### ISSUE THREAD

**Issue by Weiyinyin11** [benfred/implicit#595]
Can you put Tf.sparsetensor in model.fit()? How do you do that?

**Comment by ita9naiwa** [comment]
you can get data, indice, indptr from tf.sparsetensor and can construct `scipy.sparse.csr_matrix`
https://en.wikipedia.org/wiki/Sparse_matrix
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html
