### ISSUE TITLE
pip install missing 32-bit factor support

### ISSUE THREAD

**Issue by misterwindupbird** [benfred/implicit#6]
Hey Ben, looks like when I install via pip I'm not getting your recent changes to support 32 bit factorization -- the dtype argument is not part of the `alternating_least_squares` method signature. (Among other things, this means I can't download and run the tests.)

**Comment by benfred** [comment]
I haven't updated pypi with that change yet - if you want it you should clone and run 'python setup.py install' to use it.

I have a couple other changes in the works here that I was going to bundle up before creating a new release. If you're free want to grab lunch next week and we can discuss then? I'm interested in hearing how you're using this

**Comment by benfred** [comment]
should be there now
