### ISSUE TITLE
Website missing on GitHub repository details

### ISSUE THREAD

**Issue by andresribeiro** [benfred/implicit#600]
The docs website could be added to GitHub repository details

**Comment by benfred** [comment]
The website is already set to the docs website afaict - 

<img width="787" alt="Screen Shot 2022-08-17 at 10 36 44 AM" src="https://user-images.githubusercontent.com/69536/185205637-3e3116d3-2fed-4f1f-85f0-ff0c54c48c50.png">


where else would you want to see it?

**Comment by andresribeiro** [comment]
strange. the website does not appear in the right sidebar, as it does in other projects:

![image](https://user-images.githubusercontent.com/63297375/185260755-1c542025-a30f-424c-8dcb-b229236621e9.png)

React Native sidebar:

![image](https://user-images.githubusercontent.com/63297375/185260692-5f4dc3e8-5808-4aed-a503-51ce030917df.png)

**Comment by benfred** [comment]
:facepalm: The text I was seeing there was the defaultValue for the html input, rather than a value I had entered. It should be showing up now

Thanks for following up,
