### ISSUE TITLE
On Mac M1, models are hanging

### ISSUE THREAD

**Issue by josh-ashkinaze** [benfred/implicit#603]
Let's say I try to run this code:

```
import implicit
import random
from scipy import sparse
import numpy as np

n = 100
k = 100

M = np.zeros((n, k))
for i in range(n):
    for j in range(k):
        M[i][j] = random.uniform(1,10)
        
sparse_M = sparse.csr_matrix(M)
als_model = implicit.als.AlternatingLeastSquares(factors=10, regularization=0, random_state=123)
als_model.fit(sparse_M)
```
At the fit step, Implicit just hangs on 0% and I get this picture: 
<img width="964" alt="image" src="https://user-images.githubusercontent.com/52294640/184501078-d4c300d2-5c74-4c52-ada7-4f05ab4af9a2.png">

**Comment by benfred** [comment]
Do you have a stack trace where its hanging on? Using https://github.com/benfred/py-spy with ```sudo py-spy dump -p PID``` should show the line thats hanging

I don't have a M1 mac to test out myself on unfortunately =(

**Comment by josh-ashkinaze** [comment]
Fixed it by reinstalling this package and reinstalling scipy oddly
