### ISSUE TITLE
Correct Way Of Matching Recommended Item IDs to Items

### ISSUE THREAD

**Issue by gfleetwood** [benfred/implicit#604]
I was following the tutorial (https://benfred.github.io/implicit/tutorial_lastfm.html#Getting-the-Dataset) with my own data, and was unsure how to use the ids from...

```
ids, scores = model.recommend(userid, user_plays[userid], N=10, filter_already_liked_items=False)
```
...to my original data set. Can I assume that the ids match the order of the columns in the original data? My data was a 9167 x 7964 dataframe that I converted to a sparse matrix - following the tutorial - with:

```
from implicit.nearest_neighbours import bm25_weight

artist_user_plays = bm25_weight(original_data, K1 = 100, B = 0.8)
```

**Comment by benfred** [comment]
Yup! the ids there will be the item ids passed in to the `model.fit` method (that is the columns of the sparse matrix you passed in)

**Comment by gfleetwood** [comment]
Great. Thanks!
