### ISSUE TITLE
Argument u is never used in recommend() method in NearestNeighboursScorer class

### ISSUE THREAD

**Issue by slavafive** [benfred/implicit#610]
https://github.com/benfred/implicit/blob/d57b0b6f4dcd98c2a170de4c0bcd40122c71cdf2/implicit/_nearest_neighbours.pyx#L52
I wonder what is the point of passing argument **u** in this case since it is not used in this method. This method is called on 77-th line in ItemItemRecommender where we recommend items to specific user denoted by **userid**.

**Comment by benfred** [comment]
The `u` param was necessary in this method at one point - but isn't now after the changes in https://github.com/benfred/implicit/pull/526 .

We could drop this parameter now I guess - this class isn't meant to be part of the user facing API, and people shouldn't be depending directly on it directly.
