### ISSUE TITLE
Conda package for v.0.6.1

### ISSUE THREAD

**Issue by josp70** [benfred/implicit#614]
The latest release tag is v.0.6.1. On conda-forge the latest published is 0.5.2 https://anaconda.org/conda-forge/implicit.

Do you know how many days takes since releasing a new version in github until it gets published on conda-forge?

Thanks!

**Comment by benfred** [comment]
There were some build issues with the GPU code - but the new 0.7.0 branch is now pushed out to conda-forge. Let me know if you have any problems with it!
