### ISSUE TITLE
Pip installation fails for linux/arm64 platform

### ISSUE THREAD

**Issue by aditya-batheja** [benfred/implicit#622]
Hey!

I really appreciate the work you guys are doing. I would greatly appreciate if you could help me with this. Im unable to pip install implicit v0.6.1 on an linux/arm64 platform(running docker on Apple silicon). Im able to locally install it on my m1 macbook and it seems to work for everyone in my team using an intel chip as well. The issue seems to be only relevant to linux/arm64. The issue might be related to lack of wheels for this configuration [here](https://github.com/benfred/implicit/releases/tag/v0.6.1). It would be really helpful if you could provide pip support for it. Thanks!

Duplicate issue [611](https://github.com/benfred/implicit/issues/611).

**Comment by danieldorosz** [comment]
I've run into this issue as well. Can't install Implicit into a docker container on an M1 mac. It would be useful to generate the linux/arm64 wheel in addition to the others in order to support this scenario.

**Comment by AFimin** [comment]
Hello guys, I would add, that the problem lies beneath a fact, that there is no 0.6.1 package (for example) for ubuntu arm64.
Im also awaiting this to be fixed.

**Comment by benfred** [comment]
We're building wheels for arm64 linux packages now as part of CI - and this will be in the next version

**Comment by benfred** [comment]
Linux aarch64 wheels are up on pypi for the v0.6.2 release https://pypi.org/project/implicit/#files . Please try them out and let me know how it goes! I don't (yet) have a aarch64 machine to test these out on - though I am thinking picking up a Jetson Orin dev kit at some point for testing things like this out.

Note that the aarch64 wheels don't yet have GPU support yet - I'm using cibuildwheel to cross compile for aarch64, and didn't manage to get this going.
