### ISSUE TITLE
Erro in (pip install PyAudio)

### ISSUE THREAD

**Issue by LuizFernandoDeveloper** [benfred/implicit#623]
pip install pyaudio
Collecting pyaudio
  Using cached PyAudio-0.2.12.tar.gz (42 kB)
  Installing build dependencies ... [?25ldone
etting requirements to build wheel ... e
g wheel metadata ... e
uilding wheels for collected packages: pyaudio
  Building wheel for pyaudio (PEP 517) ... [?25lerror
  ERROR: Command errored out with exit status 1:
   command: /home/luiz/anaconda3/bin/python /home/luiz/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpx7e59mzv
       cwd: /tmp/pip-install-iw0q3k38/pyaudio_2890c577ce6543b39c1950aaaa0440f4
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-cpython-39
  copying src/pyaudio.py -> build/lib.linux-x86_64-cpython-39
  running build_ext
  building '_portaudio' extension
  creating build/temp.linux-x86_64-cpython-39
  creating build/temp.linux-x86_64-cpython-39/src
  gcc -pthread -B /home/luiz/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/luiz/anaconda3/include -I/home/luiz/anaconda3/include -fPIC -O2 -isystem /home/luiz/anaconda3/include -fPIC -I/usr/local/include -I/usr/include -I/home/luiz/anaconda3/include/python3.9 -c src/_portaudiomodule.c -o build/temp.linux-x86_64-cpython-39/src/_portaudiomodule.o
  src/_portaudiomodule.c:31:10: fatal error: portaudio.h: No such file or directory
     31 | #include "portaudio.h"
        |          ^~~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for pyaudio
ailed to build pyaudio
ERROR: Could not build wheels for pyaudio which use PEP 517 and cannot be installed directly
Note: you may need to restart the kernel to use updated packages.

**Comment by LuizFernandoDeveloper** [comment]
help

**Comment by benfred** [comment]
Maybe contact the pyaudio maintainers for help? This is an unrelated project

**Comment by LuizFernandoDeveloper** [comment]
obrigado
