### ISSUE TITLE
Nearest Neighbour Models recommend items is not sorted

### ISSUE THREAD

**Issue by yejiahaoye** [benfred/implicit#627]
when i use Nearest Neighbour Models to do recommend() in moive lens data, i find the return ids  are not sorted by scores

the return scores is like below:
2.40876593, 2.62870017, 2.43301657, 3.13649946, 2.7855705

**Comment by benfred** [comment]
Thanks for reporting! This is definitely a bug - I have a fix in https://github.com/benfred/implicit/pull/629
