### ISSUE TITLE
Can we do recommend without using user_items matrix ?

### ISSUE THREAD

**Issue by gdg456** [benfred/implicit#642]
This is not an issue as such but a query. 
I am using implicit for my production and i want to save the model after being trained. 
Then another job loads the model and want to calculate recommendations for selected users. 
Can I do it without using user-items interaction matrix ?

**Comment by benfred** [comment]
It depends a bit on the model - the ALS/BPR models only require the user-item interaction if you are either filtering already  liked items, or are recalculating the user embedding. For these models, if you pass `recalculate_user=False` and `filter_already_liked_items=False`, you can set the user_items parameter to None.

The KNN models require this to be passed all the time.
