### ISSUE TITLE
Implicit Issue - IndexError: index 11964631 is out of bounds for axis 0 with size 11960480

### ISSUE THREAD

**Issue by brnofeli** [benfred/implicit#645]
Hi ! 

I'm trying to get recommendation from a list of user but I'm ending up with the following issue : 
"IndexError: index 11964631 is out of bounds for axis 0 with size 11960480" 

Below, the code that I'm using : 

```
sparse_user_item_train = sparse.csr_matrix((df['nb_events'], (df['user_id'], df['item_id'])))

#Model recommendation creation
model_reco_als = implicit.als.AlternatingLeastSquares(factors=25, regularization=0.01, iterations=50, random_state = 13454)
alpha = 10
data_train = (sparse_user_item_train * alpha).astype('double')

model_reco_als.fit(data_train)

#ITEMS THAT WE CAN'T RECOMMEND
not_recommendable_items = item_table.query("is_checked == 1")['item_id'].unique()

#list of userid that are in the table 
list_userid_table = df.user_id.unique()

#10 best recommendations per users
n_items_to_recommend = 10
list_reco, list_score_reco = model_reco_als.recommend(list_userid_table, sparse_user_item_train[list_userid_table], N=n_items_to_recommend, filter_items=not_recommendable_items)
```
From that recommend call, I get the following issue : **IndexError: index 11964631 is out of bounds for axis 0 with size 11960480**

The list of unique user_id that I'm creating is coming from the table that I've used to train the model so it's supposed to be the same scope of users between the training and the recommendation call.

I'm currently working on the version 0.5.2 of this library. 

How can I solve this issue ?

Thanks for your help

**Comment by guydepauw** [comment]
@brnofeli I'm having the same issue. How did you solve it?

**Comment by brnofeli** [comment]
@guydepauw, some of the user_id I used to make recommendations when I called the model were not in the training set
