### ISSUE TITLE
als implicit training and scoring slower 

### ISSUE THREAD

**Issue by Selva163** [benfred/implicit#649]
Noticed when we are training the model on 'ml.t3.medium' (vCPU - 2 and Memory - 4 GiB) took only 2 mins on Sagemaker notebook while when running in sagemaker pipeline on larger machine 'ml.t3.2xlarge' (vCPU - 8 and Memory - 32 GiB) taking 20 mins. Also noticed similar runtime when running on containers. 

Our idea is to get recommendations refreshed every 2 mins for the active users.

**Comment by benfred** [comment]
It's a little hard to say exactly what the problem is here - but can you verify that you've disabled internal threading on your BLAS library as suggested here  https://github.com/benfred/implicit#optimal-configuration ?

**Comment by Selva163** [comment]
Closing this issue as configuration helped.
