### ISSUE TITLE
Silent NaN's in implicit AlternatingLeastSquares while implementing Grid search

### ISSUE THREAD

**Issue by milanABI** [benfred/implicit#651]
@benfred  @Focus Currently i am using 0.6.2 version and I am getting an error while implementing grid search. I've double checked  there is no NaN's in the data.
```
clf = GridSearchCV(als_pipeline, parameters,cv = 2, verbose=True, error_score='raise') 
clf.fit(data_als,data_als)
```
below is the screenshot attached for the same.
<img width="871" alt="Screenshot 2023-03-30 at 11 50 36 AM" src="https://user-images.githubusercontent.com/115446899/228749165-a0cf01f2-44b4-4345-857e-44fbf710f56e.png">

**Comment by benfred** [comment]
Do you have a reproducer I can use here (dataset + ALS parameters that cause a NaN value)?

**Comment by benfred** [comment]
@milanABI - please re-open if this is still an issue for you
