### ISSUE TITLE
recommend method does not work for ALS

### ISSUE THREAD

**Issue by ManosL** [benfred/implicit#655]
Hello,

I fit an `AlternatingLeastSquares` model like this

```
model = implicit.als.AlternatingLeastSquares(factors=20, regularization=0.1, iterations=20)

alpha_val = 40
fit_data = (item_user_sparse_matrix * alpha_val).astype('double')
model.fit(fit_data)
```

and then I get the recommendations by running:

```
model.recommend(user_index, user_item_sparse_matrix[user_index])
```

where `user_item_sparse_matrix` is the transpose of `item_user_sparse_matrix`. However, when I run it I get an IndexOutOfRange error but I'm convinced that the index is correct. Checking the shape of Item Factors running `model.item_factors.shape`, I saw that its shape was `(num_users, 20)`, which I think is incorrect and I have the following question:

Is it a bug in the code that needs to be fixed or should I fit with `user_item_sparse_matrix`? I tried the latter and worked in terms of producing results.

**Comment by benfred** [comment]
> Is it a bug in the code that needs to be fixed or should I fit with user_item_sparse_matrix? I tried the latter and worked in terms of producing results.

The API changed in v0.5.0 https://github.com/benfred/implicit/releases/tag/v0.5.0 - you should pass in the user_item_sparse_matrix to the fit function now.  See also https://github.com/benfred/implicit/issues/641
