### ISSUE TITLE
Drop `setup_requires`

### ISSUE THREAD

**Issue by jakirkham** [benfred/implicit#671]
Currently `setup.py` makes use of `setup_requires`

https://github.com/benfred/implicit/blob/2268ac78d08e4ab94ce53bd48b08bcd012878559/setup.py#L59

This is used to configure the `cmake` dependency (when building wheels IIUC)

https://github.com/benfred/implicit/blob/2268ac78d08e4ab94ce53bd48b08bcd012878559/setup.py#L10-L16

Though it appears this dependency can just be `cmake>=3.17` and could be added to `build-system.requires`

https://github.com/benfred/implicit/blob/2268ac78d08e4ab94ce53bd48b08bcd012878559/pyproject.toml#L5-L12

Given all [the issues with `setup_requires`]( https://stackoverflow.com/a/58826468 ), maybe it could just be dropped?

**Comment by benfred** [comment]
@jakirkham - I've dropped the setup_requires in #674

**Comment by jakirkham** [comment]
Thanks Ben! 🙏

If it is desirable to list the `cmake` dependency, could add it to `pyproject.toml` here:

https://github.com/benfred/implicit/blob/a19df795e89ac0171fbd756be520b3906017d8db/pyproject.toml#L5-L12

**Comment by benfred** [comment]
thanks @jakirkham - done in https://github.com/benfred/implicit/pull/677
