### ISSUE TITLE
I encountered the following problem when I installed implicit

### ISSUE THREAD

**Issue by superrui0810** [benfred/implicit#68]
error: command 'cl.exe' failed: No such file or directory

**Comment by benfred** [comment]
I don't have easy access to a windows box - so this is a little hard for me to test. However, we do have CI set up for windows that builds this package and runs the tests: https://ci.appveyor.com/project/benfred/implicit 

Can you include the complete build output? Also what compiler are you using and what version of python?

**Comment by superrui0810** [comment]
![image](https://user-images.githubusercontent.com/33829421/33302767-9224852c-d439-11e7-8cec-e996c500dcb0.png)
my python version is 3.5.4

**Comment by benfred** [comment]
Interesting - 

Do you have visual studio installed? Also is it on the PATH ? This question has some steps you can take with someone else having a similar problem https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed
