### ISSUE TITLE
Next release date

### ISSUE THREAD

**Issue by xiangb** [benfred/implicit#684]
Hi, 

I was not sure where to ask the question, so I'm writing it here.

I was wondering if there is a planned date for the next official release of the package including the fix for Cython here https://github.com/benfred/implicit/pull/680? 

Thank you.

**Comment by benfred** [comment]
v0.7.1 is here https://github.com/benfred/implicit/releases/tag/v0.7.1 - and contains the cython fix.

**Comment by xiangb** [comment]
Thank you very much 🙏
