### ISSUE TITLE
Shoot up in model training time for implicit.bpr (10x)

### ISSUE THREAD

**Issue by SaifJawaid** [benfred/implicit#686]
I have been using this version of the library implicit==0.4.4, but since last month the training time for my data has shot up 10x. Was there any specific change in your code which caused this? What troubleshooting solution do you recommend?

**Comment by benfred** [comment]
Also - note that there were some breaking API changes in implicit v0.5.0 https://github.com/benfred/implicit/issues/481, that you should be aware of if you're updating to the latest version

**Comment by SaifJawaid** [comment]
@benfred changing the version of Cython to a previous version worked for me (v0.29.35). Thank you
