### ISSUE TITLE
Install implicit with conda-forge only for cpu (without gpu support)

### ISSUE THREAD

**Issue by franzoni315** [benfred/implicit#687]
Hi, I am trying to deploy a recommendation systems with implicit, and I am using miniforge as the base of my environment. I would like to make a deploy of this program, but I am noticing it is installing cudatoolkit, which is about 760 MB. Since, I do not have any gpu available, I would not expect miniforge to download this. Does anyone know how to make miniforge to download only cpu-related dependencies, while installing implicit?

**Comment by benfred** [comment]
Hmm - that doesn't seem great.  Does using the cpu meta-package still pull this in?

```
conda install -c conda-forge implicit implicit-proc=*=cpu
```

**Comment by franzoni315** [comment]
It worked! Thanks very much! For some reason it is necessary to explicitly set this metapackage.
