### ISSUE TITLE
ImportError: DLL load failed with error code 14001

### ISSUE THREAD

**Issue by LeoCuoghi** [benfred/implicit#71]
Hi,
I have a problem where I try to import the library. If I run any main.py with 

>> import implicit

I obtain:

>> Traceback (most recent call last):
  File "C:/Users/lcuoghi/Desktop/A_Gentle_Introduction/main.py", line 327, in <module>
    import implicit
  File "C:\Users\lcuoghi\AppData\Local\Continuum\anaconda2\lib\site-packages\implicit\__init__.py", line 1, in <module>
    from .als import alternating_least_squares
  File "C:\Users\lcuoghi\AppData\Local\Continuum\anaconda2\lib\site-packages\implicit\als.py", line 10, in <module>
    from . import _als
ImportError: DLL load failed with error code 14001
>>
>> Process finished with exit code 1

Can you help me? I had no problems with the installation... It ran successfully. I checked all the packages, and they look right. What is missing? What does ‘error code 14001’ mean?

Thanks in advance,

**Comment by benfred** [comment]
Unfortunately I don't have access to a windows box - the most windows support I have is getting a windows build running on appveyor =(. I'm guessing that some of the dependencies of _als.dll are missing though - can you open it up with [dependency walker](http://www.dependencywalker.com/) and check that it finds all the dependencies?

Sorry I can't be of more help here
