### ISSUE TITLE
gpu issue on colab  (implicit==0.7.2 / cuda ==12.1)

### ISSUE THREAD

**Issue by nnfuzzy** [benfred/implicit#712]
Hi,

i don't know exactly why (maybe a colab bump in cuda version?) , because it worked in the past , but I can't use  the GPU in colab anymore.
Installed wih pip the latest version (0.7.2) . 

I'm getting a: ValueError: No CUDA extension has been built, can't train on GPU.
But cuda ist available: Is CUDA available?  True / CUDA version:  12.1
 
Thanks in advance,
Christian

**Comment by nnfuzzy** [comment]
It works if you do:

```
!pip install -q condacolab
import condacolab
condacolab.install()

!conda install -c conda-forge implicit implicit-proc=*=gpu
```

**Comment by soot-bit** [comment]
this solution should probably be in the readme!, however this no longer works, it crashes  the session in colab
