### ISSUE TITLE
Error Implementing Implicit - AttributeError: 'DataFrame' object has no attribute 'tocsr'

### ISSUE THREAD

**Issue by erseema** [benfred/implicit#75]
While using implicit package , I am getting Attribute error .
I am fitting model on user-item matrix.

**Comment by benfred** [comment]
Including answer from other issue (https://github.com/benfred/implicit/issues/57#issuecomment-360018888):

It looks like you're passing a pandas dataframe to the fit function, when you should be passing a sparse matrix (like a scipy.sparse.csr_matrix or similar) in.

Check out the examples for how to convert: https://github.com/benfred/implicit/blob/master/examples/lastfm.py#L71
