### ISSUE TITLE
requires CUDA 9

### ISSUE THREAD

**Issue by statX** [benfred/implicit#79]
Hi Ben,  thank you for what looks like an amazing library. I just gave myself an unproductive hour trying to compile until I realised that the __activemask and __shfl_down_sync primitives were introduced in CUDA 9 and the Databricks machine I'm restricted to using has CUDA 8. Next time you look at this or update the code is it worthwhile adding a note to this effect? Only even leaving this here because I can't delete the issue. Thank you :)

**Comment by benfred** [comment]
I'm guessing you got this working - but for posterity, you need to have the NVidia CUDA toolkit installed before building to enable GPU support. The toolkit can be found here https://developer.nvidia.com/cuda-downloads

**Comment by statX** [comment]
yes, working now :) I moved on from the databricks CUDA 8 instances to a EC2 machine with CUDA 9. One Volta GPU crushes 30 spark workers ... as expected :D

**Comment by benfred** [comment]
Awesome! Glad that the GPU code is working for you!

**Comment by benfred** [comment]
Though, looking at your comment above again - I think I can get this working with CUDA 8 without too much effort, will take a look this afternoon. Also I will add some build instructions here for the cuda module too.

**Comment by benfred** [comment]
That last commit (https://github.com/benfred/implicit/commit/3d1f1801a8caa48a5865fb37dbaeae3c2dfc07c0) should make it possible to use CUDA 8 with this project.  It will be in the next version of implicit (0.3.1)

**Comment by statX** [comment]
Hi Ben, thank you very much for the modification. Unrequited but really appreciated.  👍
