### ISSUE TITLE
ImportError: No module named 'implicit.cuda._cuda'

### ISSUE THREAD

**Issue by TomScheffers** [benfred/implicit#85]
Hi there,

I get the following error while initializing the model as: self.model = als.AlternatingLeastSquares(factors=dim, regularization = regularization, iterations = iterations, **use_gpu = True**). Does anyone know how this error is caused?

python main.py
Traceback (most recent call last):
  File "main.py", line 53, in <module>
    cf.train(dim=20, regularization=0.0175, iterations=80)
  File "main.py", line 39, in train
    self.model.fit(self.purchases_sparse)
  File "C:\Users\TomSc\AppData\Local\Programs\Python\Python35\lib\site-packages\implicit\als.py", line 135, in fit
    return self._fit_gpu(Ciu, Cui)
  File "C:\Users\TomSc\AppData\Local\Programs\Python\Python35\lib\site-packages\implicit\als.py", line 158, in _fit_gpu
    import implicit.cuda
  File "C:\Users\TomSc\AppData\Local\Programs\Python\Python35\lib\site-packages\implicit\cuda\__init__.py", line 3, in <module>
    from ._cuda import *  # noqa
ImportError: No module named 'implicit.cuda._cuda'

I got the right CUDA package:
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Mon_Jan__9_17:32:33_CST_2017
Cuda compilation tools, release 8.0, V8.0.60

Thank you,
Tom

**Comment by benfred** [comment]
That's a pretty bad error message (I tried to fix that up in the last commit) - but what its complaining about is that that the CUDA extension isn't built. 

I'm not quite sure why it didn't build the extension for you =( Its possible that it didn't find nvcc on the path (in which case setting a CUDAHOME env variable to point to your cuda installation might work).

 I also added some extra logging to the build in the last commit, if you build from master it should say why the extension isn't getting built now. Can you try that out? (like running ```python setup.py install``` from the master branch of this repo).

**Comment by TomScheffers** [comment]
Thank you for the quick response. 

I tried the latter and indeed the problem is the nvcc path:
λ python setup.py install
WARNING:root:The CUDA nvcc path could not be located in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc
Failed to find CUDA toolkit. Building without GPU acceleration.

The nvcc file is in the right directory:
![image](https://user-images.githubusercontent.com/28607837/36510908-fa89fcc8-1764-11e8-830d-8f6ea48264b3.png)

I added the CUDAHOME env variable, so that's why it was able to find the path, but the problem seems to be in the nvcc.exe file. For your information the cuda variables are made under CUDA_PATH for me, so maybe you can add that as a path in the new build. See image below.

![image](https://user-images.githubusercontent.com/28607837/36510740-6f8b0996-1764-11e8-8f2b-3d23d1be65e8.png)

**Comment by benfred** [comment]
I'm thinking this is an issue with the cuda build on windows. I don't have access to a windows box with a GPU, so I've only tested the GPU code right now on ubuntu =(. 

One issue that I can see is that it was looking for nvcc instead of nvcc.exe - and I've attempted to fix here: https://github.com/benfred/implicit/commit/8b7874c21d5205b821adf372b620696f101bdfb1

**Comment by TomScheffers** [comment]
I cloned the most recent build to my desktop. Installed it using pip install -e 'local directory', I now get another error:
raise ValueError("No CUDA extension has been built, can't train on GPU.")
ValueError: No CUDA extension has been built, can't train on GPU.

Maybe I should add nvcc to the variables?

**Comment by benfred** [comment]
There were multiple issues with this building on windows, including the one you pointed out =(.

I installed windows on a desktop, and with the latest commit https://github.com/benfred/implicit/commit/ed706077e4908e5f42977350a3d74a9679f8237d it at least builds.

One weird thing is that there seems to be a performance hit on windows training the ALS model on the GPU, but not the BPR model. When I ran the ALS model on the last.fm dataset, it was only slightly faster on windows on the GPU (vs about 3-5x faster on the exact same hardware running ubuntu). The BPR model was about 10x faster on both windows and ubuntu for some reason.

Now that I have a windows environment to test on, I'll take a look more at the perfomance issues on windows later. That last commit should at least let you build the extension on windows though

**Comment by fporrata** [comment]
Hello benfred,   I have Windows 10.  I am using implicit 0.3.9 but still I cannot build.  I tried CUDAHOME = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0  and CUDAHOME = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin but did not work.  My Path variable has C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64  for the library.  Please let me know if you can help.  I am in the middle of a big project and need to use the GPU to get results faster.  Thank you very much
