### ISSUE TITLE
Rank only selected items w.r.t the user

### ISSUE THREAD

**Issue by ita9naiwa** [benfred/implicit#89]
Hi, first, thanks for this awesome framework!
I am using this library for my project.

`recommender.recommend()` provides nice functionality, but it will be more beneficial if it provides recommend or rank a few items from given set of items with respect to users. 

For example, I'd like to recommend (personalized!) an user only horror movies among 20,000 movies.

I know there is `filter_items` parameter, but I think it will be great to explicitly denote which item to include for recommendation. I think I could implement it...

Thanks.

**Comment by benfred** [comment]
Agreed - I think this would be useful! It shouldn't be hard to implement for the matrix factorization models anyways
