### ISSUE TITLE
How to mix implicit and explicit feedback?

### ISSUE THREAD

**Issue by dmitriyshashkin** [benfred/implicit#90]
I have explicit negative feedback for some of the items. Is there a way to make the model use it together with implicit feedback?

**Comment by benfred** [comment]
Its not currently possible here - the models here are only working with implicit feedback.

In theory, we could modify the ALS model to give a higher weight to known negative items (right now all zero elements of the passed in matrix are treated as negative with a confidence of 1). However, I've tried this out before and haven't found it to be that useful. 

I have found that using implicit feedback for ranking results to show the user - and then training a separate model on explicit feedback to filter the ranked results has worked well. However, this is out of scope for this project.

Its also worth reading this: https://github.com/maciejkula/explicit-vs-implicit  - implicit feedback usually results in a better ranking than using explicit feed back. 

Anyways, hope this helps!

**Comment by dmitriyshashkin** [comment]
Thank you very much for the information! I really appreciate it.

BTW, do I understand correctly that if I pass explicit negative feedback as zeroes, this might not influence the model that much, but at least it will exclude those items from the recommendations for the users that gave me that negative feedback?

Also, I've thought that the matrix I provide to the model is a confidence matrix, where each element specifies how confident I am that the user gave positive feedback for some item. In other words, the feedback is always positive, only the level of confidence might vary. Does handling of zeroes you described above constitute a special case or I'm just completely wrong in my assumptions?

**Comment by benfred** [comment]
You're right in that the matrix is the confidence matrix - where each element is how confident you are that each user gave positive feedback. The matrix is sparse, and we're using the missing entries as indicating something the user didn't like. I said 'zero elements' here when I should have said 'missing elements' here.

Passing a 0 confidence for the negative items during ```model.fit``` won't have the effect you want: it will learn that the user liked the item with 0 confidence (versus disliked the item with 1 confidence for missing items).

However, you can pass both the likes/dislikes as user_items to the ```model.recommend``` call and the known dislikes will get filtered with the known likes.

**Comment by dmitriyshashkin** [comment]
Nice! This workaround solves my main problem! Thank you for the suggestion and the detailed explanation
