### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

### ISSUE THREAD

**Issue by Dilshad737** [benfred/implicit#91]
I am using 
"Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32"

I tried to install "wordcloud" using 
pip install wordcloud

I faced that error!!!!
Any one here to help me how to get rid of it.
////////////////////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

C:\Windows\system32>pip install wordcloud
Collecting wordcloud
  Using cached wordcloud-1.4.1.tar.gz
Requirement already satisfied: matplotlib in c:\program files\python36\lib\site-packages (from wordcloud)
Requirement already satisfied: numpy>=1.6.1 in c:\program files\python36\lib\site-packages (from wordcloud)
Requirement already satisfied: pillow in c:\program files\python36\lib\site-packages (from wordcloud)
Requirement already satisfied: six>=1.10 in c:\program files\python36\lib\site-packages (from matplotlib->wordcloud)
Requirement already satisfied: python-dateutil>=2.1 in c:\program files\python36\lib\site-packages (from matplotlib->wordcloud)
Requirement already satisfied: pytz in c:\program files\python36\lib\site-packages (from matplotlib->wordcloud)
Requirement already satisfied: cycler>=0.10 in c:\program files\python36\lib\site-packages (from matplotlib->wordcloud)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\program files\python36\lib\site-packages (from matplotlib->wordcloud)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\program files\python36\lib\site-packages (from matplotlib->wordcloud)
Requirement already satisfied: setuptools in c:\program files\python36\lib\site-packages (from kiwisolver>=1.0.1->matplotlib->wordcloud)
Installing collected packages: wordcloud
  Running setup.py install for wordcloud ... error
    Complete output from command "c:\program files\python36\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\DILSHAD\\AppData\\Local\\Temp\\pip-build-s0v4o0v_\\wordcloud\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\DILSHAD\AppData\Local\Temp\pip-0ki_078y-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\wordcloud
    copying wordcloud\color_from_image.py -> build\lib.win-amd64-3.6\wordcloud
    copying wordcloud\tokenization.py -> build\lib.win-amd64-3.6\wordcloud
    copying wordcloud\wordcloud.py -> build\lib.win-amd64-3.6\wordcloud
    copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-3.6\wordcloud
    copying wordcloud\__init__.py -> build\lib.win-amd64-3.6\wordcloud
    copying wordcloud\stopwords -> build\lib.win-amd64-3.6\wordcloud
    copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-3.6\wordcloud
    running build_ext
    building 'wordcloud.query_integral_image' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command ""c:\program files\python36\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\DILSHAD\\AppData\\Local\\Temp\\pip-build-s0v4o0v_\\wordcloud\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\DILSHAD\AppData\Local\Temp\pip-0ki_078y-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\DILSHAD\AppData\Local\Temp\pip-build-s0v4o0v_\wordcloud\

**Comment by Dilshad737** [comment]
I am waiting for your kind suggestions!!!!

**Comment by benfred** [comment]
I think you just need to install at least v14 of microsoft visual c++ and then install again - you can download/install it from the link in the error message: http://landinghub.visualstudio.com/visual-cpp-build-tools. Also this seems like the problem you're having is in a different package =).

**Comment by vikash310** [comment]
Hey Dilshad!!

Such problem are basically solved by upgrading python setuptools.
Try these command:

pip install -U setuptools

**Comment by widedh** [comment]
hey vikash,

I tried the command but nothing has changed.

**Comment by GauravAg10** [comment]
You need to install the visual c++ build tools. The link in the error message seems like it's dead, but you can download them here: https://visualstudio.microsoft.com/visual-cpp-build-tools/

Note that while the error is calling for vc++ 14.0 - everything will work with newer versions of visual c++.

**Comment by Walt-H** [comment]
I was able to solve the problem doing the following:
1. Install [VS Buildtools](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017)
2. Choose the following options in the **Work Loads** -> **Visual C++ build tools** -> _Optional_
 ```
Windows 10 SDK (10.0.17763.0)
Visual C++ tools for CMake
Testing tools core features - Build Tools
Visual C++ ATL for x86 and x64
VC++ 2015.3 v14.00 (v140) toolset for desktop
```
3. Choose the following options in the **Work Loads** -> **Visual C++ build tools** -> _Individual Components_
 ```
Windows Universal CRT SDK
Windows 8.1 SDK
```
4. Restart the computer
5. Then as told by [Iagom](https://stackoverflow.com/questions/43858836/python-installing-clarifai-vs14-0-link-exe-failed-with-exit-status-1158), we need to copy  **rc.exe** & **rcdll.dll** from _C:\Program Files (x86)\Windows Kits\8.1\bin\x86_ to  _C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin_

6. We then need to run `pip install -U setuptools`
7. Now we can run the `pip install apache-airflow` command (I had to it in an **administrator** shell)

**Comment by vidb6** [comment]
It did not solve my issue

**Comment by bolak92** [comment]
This solved my problem. Thank you so much, have been struggling with this error for 2 days now.

**Comment by shravankumar9892** [comment]
Download a .whl file for your partcular python version and local machine version (https://www.lfd.uci.edu/~gohlke/pythonlibs/#mysql-python) and do pip install .whl. It worked for me!

**Comment by abhishekkagautam** [comment]
Hi everyone,

Here is a simple solution to get it worked on Windows. May not be a relevant topic to discuss here but would be useful for others, I hope :)

Install Visual C++ 2015 Build Tools from https://go.microsoft.com/fwlink/?LinkId=691126 with default selection.

Go to C:\Program Files (x86)\Microsoft Visual C++ Build Tools and run vcbuildtools_msbuild.bat

In Anaconda, run

pip install git+https://github.com/philferriere/cocoapi.git#egg=pycocotools^&subdirectory=PythonAPI

GLHF.

**Comment by PhilT** [comment]
Thanks @shravankumar9892. For those that have Chocolatey you can install with 

```
choco install visualcppbuildtools
```

**Comment by f0lie** [comment]
@PhilT 

I was trying to complie for a completely different project but I can confirm that `choco install visualcppbuildtools` is correct.
